### ISSUE TITLE
Word break is happening in the message tile

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#1010]
<img width="635" alt="image" src="https://user-images.githubusercontent.com/69431456/198797143-c1620727-172c-4b0a-a31c-36a4cefdaefd.png">

**Comment by foolo** [comment]
Seems to be working at the moment. See screenshot. May have been fixed together with #1064
![Screenshot_2022-11-08_17-21-52](https://user-images.githubusercontent.com/667227/200619903-3f338bb7-dd11-4ded-999e-dc50d322ceb4.png)
