### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by elmasdemircioglu** [lensterxyz/lenster#1022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The red spot on the notification button dont go away until i check two or three times even refresh the page. It is not that important but little bit annoying. If you fix this ill be happy for that. 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by naumanmehdi** [comment]
It happens every time I refresh the page. 
Steps: 
Read all the pending notifications > Refresh the page > Unred notifications mark appears again.

**Comment by bigint** [comment]
Should be fixed 🚀
