### ISSUE TITLE
Profile search fails to yield exact matches against queries including punctuation

### ISSUE THREAD

**Issue by saulmc** [lensterxyz/lenster#1028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Profile search fails to yield exact matches against queries including punctuation, such as `saulmc.lens` or `nick-molnar`. It appears that the query is being "split" on the punctuation. The behavior appears different in the case of a period or a hyphen.

### Splitting on period

|query: jazz|query: jazz.lens<br/>_Interleaves results for 'jazz' and 'lens'_|query: lens|
|-|-|-|
|<img width="457" alt="CleanShot 2022-10-30 at 19 46 18@2x" src="https://user-images.githubusercontent.com/510695/198920464-56730548-d6bb-4c0e-851f-94c695377e0e.png">|<img width="455" alt="CleanShot 2022-10-30 at 19 43 20@2x" src="https://user-images.githubusercontent.com/510695/198920396-5c84c5bb-4356-4a5c-9336-2ef3618bd8a8.png">|<img width="464" alt="CleanShot 2022-10-30 at 20 06 03@2x" src="https://user-images.githubusercontent.com/510695/198922671-83eeabf3-ac04-43ba-a52d-568ad5f63019.png">|

|query: saulmc|query: saulmc.lens<br/>_Shows results for 'lens' only_|query: lens|
|-|-|-|
|<img width="459" alt="CleanShot 2022-10-30 at 19 44 47@2x" src="https://user-images.githubusercontent.com/510695/198920292-1853ddab-d897-4ec6-9831-732007048e5c.png">|<img width="458" alt="CleanShot 2022-10-30 at 19 44 53@2x" src="https://user-images.githubusercontent.com/510695/198920304-6bbe2794-f70a-445e-afc2-739d967aa0bd.png">|<img width="464" alt="CleanShot 2022-10-30 at 20 06 03@2x" src="https://user-images.githubusercontent.com/510695/198922671-83eeabf3-ac04-43ba-a52d-568ad5f63019.png">|

### Split on hyphen

|query: nick-molnar<br/>_Shows results for 'nick' only_|query: nick-molnar.lens<br/>_'Interleaves results for 'nick' and 'lens'_|query: nick|
|-|-|-|
|<img width="527" alt="CleanShot 2022-10-30 at 19 32 57@2x" src="https://user-images.githubusercontent.com/510695/198920830-c7171dac-627a-426d-ad18-f478e66bf132.png">|<img width="458" alt="CleanShot 2022-10-30 at 19 43 43@2x" src="https://user-images.githubusercontent.com/510695/198922491-68fb7676-61d5-494a-935b-72e1bfcf6dac.png">|<img width="459" alt="CleanShot 2022-10-30 at 19 51 06@2x" src="https://user-images.githubusercontent.com/510695/198920950-c89fe3ae-12c3-47de-8a27-ac4dd182545e.png">|

### Expected Behavior

- Searching for `saulmc.lens` returns only [saulmc.lens](https://lenster.xyz/u/saulmc.lens).
- Searching for `jazz.lens` returns no results (4 character handles do not exist in Lens Protocol).
- Searching for `nick-molnar` returns only [nick-molnar.lens](https://lenster.xyz/u/nick-molnar.lens)
- Searching for `nick-molnar.lens` returns only [nick-molnar.lens](https://lenster.xyz/u/nick-molnar.lens)

### Steps To Reproduce

- [ ] Search for profiles using the the query examples provided above.

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome

**Comment by joshstevens19** [comment]
All solves the only one i do not have time to do is the ordering of a - in postgres search this is a split so ive added a ticket to relook at any special chars in the searching logic but all the other lookups in examples are perfect no.

![telegram-cloud-photo-size-4-5983486384108845355-x](https://user-images.githubusercontent.com/18472422/199269796-cccdc4cf-cbdb-4505-9982-825a0233230b.jpg)

**Comment by saulmc** [comment]
Closing issue since the .lens cases are confirmed resolved and Josh is tracking the - case separately.
