### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jacky1937** [lensterxyz/lenster#1030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

in subject "who to follow" 
it shows error. "Failed to load recommendations" Unknown row: polygon:0x951040Ba78702974d24AA48d4D388D43d0fB920a:wtf.

![image](https://user-images.githubusercontent.com/91002281/198930106-2d0cf981-86bf-4728-bb82-4b19c3322a9f.png)

### Expected Behavior

fix  soom

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Its an issue with the API and it should be fixed now 🙏🏼
