### ISSUE TITLE
Profile Posts Duplication 

### ISSUE THREAD

**Issue by naumanmehdi** [lensterxyz/lenster#1031]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am scrolling through my posts and they keep repeating in the same order as I have posted 

### Expected Behavior

Should show only once 

### Steps To Reproduce

Scroll your profile page and you would see all the posts duplication at least once 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

https://user-images.githubusercontent.com/100476953/198967172-b91c2865-ee7f-469e-b888-ea01f4069519.mp4

**Comment by martykan** [comment]
There seems to be an issue with the `merge` function in `lib/cursorBasedPagination`

Maybe this could be a possible solution? 
https://www.apollographql.com/docs/react/pagination/cursor-based/#using-a-map-to-store-unique-items

**Comment by bigint** [comment]
Interesting one, lemme debug first this is a backend issue or not 🙇🏼

**Comment by martykan** [comment]
Simple way to replicate is to log out, view your profile, log in. Posts should be duplicate afterwards

**Comment by AdamSHurwitz** [comment]
I'm observing the same behavior for adamhurwitz.lens too.

**Comment by bigint** [comment]
Fixed in #1395

**Comment by AdamSHurwitz** [comment]
Can confirm. My account is staying logged in after screen refreshes. Thank you! 🙏🏻
