### ISSUE TITLE
overwriting of posts while they index

### ISSUE THREAD

**Issue by mega7mega** [lensterxyz/lenster#1039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

posted a regular post to my profile and while it was indexing still i wrote a comment
under someone elses post
the comment never made it but the comment was replaced by the post. so i had it once on my profile page as a regular post 
but it also appeared as the comment under the other persons post. so like double.
i am not sure if it was just a front end caching problem or not. 

### Expected Behavior

to be able to comment under someones comment while another post is indexing and not having the two mixed up

### Steps To Reproduce

i guess the only way reproduce would be make a post and while its indexing comment under someone elses post.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Edge

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
