### ISSUE TITLE
Failed to load images and returning empty placeholder

### ISSUE THREAD

**Issue by lykhangky** [lensterxyz/lenster#1048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot uploading my new avatar. Although it do successful now, it took a lot of time before since it didnt reveal.

The same for my posts and my new feed. The pictures do not reveal.
![Ảnh chụp Màn hình 2022-11-01 lúc 11 30 00](https://user-images.githubusercontent.com/76061601/199159312-8b59e80b-78af-4469-bcd6-115a70e18fa5.png)
![Uploading Ảnh chụp Màn hình 2022-11-01 lúc 11.30.07.png…]()

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Should be fixed 🙇
