### ISSUE TITLE
Token gated posts

### ISSUE THREAD

**Issue by jounih** [lensterxyz/lenster#1052]
Josh and Zannis are working on an integration with Lit Protocol that will give the ability to token gate the viewing of posts based on NFT/token ownership.

This will enable features like:

1) You need to follow someone to see their token gated posts (could be a paid follow)
2) You need to collect a post before you can view the post (could be a paid collect)
3) You need to own a Bored Ape (or any NFT really) before you can view the post
4) You need to own a certain amount of token X before you can view the post

Or any combination of the above.

We need to add a frontend to this for Lenster to make it usable - here are WIP designs - will be updated this week.

![Image](https://user-images.githubusercontent.com/10109867/199222687-ec4c164e-ded2-477a-aa88-258006ad5aff.png)

![Image](https://user-images.githubusercontent.com/10109867/199222856-67e649ba-e849-4765-a07c-dcaa17451a09.png)

**Comment by bigint** [comment]
https://docs.lens.xyz/docs/gated
