### ISSUE TITLE
See the feed through the lens of someone else

### ISSUE THREAD

**Issue by jounih** [lensterxyz/lenster#1053]
Sometimes it's easy to get stuck in a bubble of only the people you're following, and you might be curious about what the feed looks like for someone else. 

We are proposing adding a feature where you can choose any profile to view the feed through.

The endpoint already exists for this, just need UI/FE development.

----Design to follow today----

**Comment by Night-Chan** [comment]
Love this idea! It sounds really cool. To my knowledge theres no other social media app that does this, right?

**Comment by TuanLedn** [comment]
Great, what do you think about the notification functions like Twitter.
We can choose to prioritize showing notifications to people we need to pay attention to.
