### ISSUE TITLE
Long links in message tile breaks the UI

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#1064]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/69431456/199472633-717470a5-bacb-41ad-a5aa-1360a394722a.png">

**Comment by foolo** [comment]
Is this on the /messages page? For me it looks good. See screenshot. Maybe some more conditions needed to reproduce?
![Screenshot_2022-11-06_10-11-20](https://user-images.githubusercontent.com/667227/200162924-f6695505-b61b-4a69-a797-6e8e17bedf6a.png)

**Comment by elisealix22** [comment]
Ah yes, this one should be good to go! Thank you for helping check @foolo !

**Comment by foolo** [comment]
> Ah yes, this one should be good to go! Thank you for helping check @foolo !

:) Seems like #1010 is resolved as well.
