### ISSUE TITLE
Improper loading of first/default DM and it leads to bad UX

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#1065]
https://user-images.githubusercontent.com/69431456/199473217-de47cfe2-6288-4a95-b351-1d28885bc2d6.mov

Better we don't select first DM

**Comment by saulmc** [comment]
@bigint Can you please clarify the unexpected behavior here? It looks like preselecting the first convo didn't work properly on the first load, but then once you refreshed it did work properly. Does that summarize the issue?

/cc @neekolas

**Comment by bigint** [comment]
@saulmc when opening DM for first time (/messages), it is trying to open the latest convo, that results in reloading the entire page, better we don't want to select the first convo by default, we can leave it like twitter's approach by just showing the empty placeholder

<img width="641" alt="image" src="https://user-images.githubusercontent.com/69431456/199554211-5d2bf62b-1df6-4227-98ba-8bf45b68fcf2.png">
