### ISSUE TITLE
Failed to load timeline

### ISSUE THREAD

**Issue by Xiangshi001** [lensterxyz/lenster#1105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Failed to load timeline

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![P0)R SV_6COUFW3CB5R84`2](https://user-images.githubusercontent.com/113326063/200098466-45e4373d-6fc8-41ad-97ce-86a169e1f51f.png)

**Comment by bigint** [comment]
This issue is on Lens API, raise it in https://github.com/lens-protocol/api-examples
