### ISSUE TITLE
DENIED ACCESS 

### ISSUE THREAD

**Issue by MarcLennon** [lensterxyz/lenster#1107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi  Lenster Team , I've tried to join lenster with my lens account
i tried logging in but i can't access  
a pop up is shown on the right hand side at the bottom

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Others

**Comment by zhanshu2** [comment]
****

**Comment by duongnta** [comment]
https://lenster.xyz/u/lovehh172516.lens

Same, pls check

**Comment by bigint** [comment]
@duongnta this is resolved by https://github.com/lensterxyz/lenster/issues/1114
