### ISSUE TITLE
post photo is not show

### ISSUE THREAD

**Issue by Gunayasa** [lensterxyz/lenster#1110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I want to post a photo, the photo doesn't appear

### Expected Behavior

I hope the photo can be displayed before posting so I can review it

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![image](https://user-images.githubusercontent.com/82763490/200164190-02c0b3ca-df41-4854-bdd7-37a254cefcc3.png)

**Comment by bigint** [comment]
Related to #1048
