### ISSUE TITLE
having an issue changing profile picture

### ISSUE THREAD

**Issue by anonhusky** [lensterxyz/lenster#1125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when the image is uploaded using the button to upload image, the avatar doesnt actually upload at all

### Expected Behavior

image should change once its uploaded and reflect on my profile

### Steps To Reproduce

.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Firefox

### Anything else?

.

**Comment by bigint** [comment]
It will take some time to update across the platform because of cache, and this is expected 🙏🏼
