### ISSUE TITLE
I can't see any post in "Timeline" area

### ISSUE THREAD

**Issue by SongShawn** [lensterxyz/lenster#1132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I write some post and send it.
I can see my post in profile page.
![image](https://user-images.githubusercontent.com/12530965/200549717-bde826e2-681a-42c4-abf8-89ea656da101.png)
But I can not see it in timeline area
![image](https://user-images.githubusercontent.com/12530965/200549815-2808e811-d333-46ed-8da5-0b0d53df0e79.png)

### Expected Behavior

show all my post in timeline

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
You need to follow peoples to see it, and this issue is not related to Lenster 🙏🏼

**Comment by SongShawn** [comment]
Sorry, I have a misunderstanding of timeline, I thought it would show my own post.
Thands for your reply.
