### ISSUE TITLE
(JS-0746) Prefer to accompany `onClick` with some elements

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#114]
## Description
Enforce `onClick` is accompanied by at least one of the following: `onKeyUp`, `onKeyDown`, `onKeyPress`. Coding for the keyboard is important for users with physical disabilities who cannot use a mouse, AT compatibility, and screenreader users. This does not apply for interactive or hidden elements

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lensterxyz/lenster/issue/JS-0746/occurrences/](https://deepsource.io/gh/lensterxyz/lenster/issue/JS-0746/occurrences/)

**Comment by piraces** [comment]
Hi! I have been working on this and I have opened a new PR to solve this deepsource issue.

**Comment by piraces** [comment]
Why is this closed? The PR is still opened #1217 @bigint
