### ISSUE TITLE
Can't mint a post

### ISSUE THREAD

**Issue by DanIsNearby** [lensterxyz/lenster#1142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cant collect a post i get an Error https://polygonscan.com/tx/0x0dd8bf42b1a376d9d3907b86aa3a5f20f3d5899fed1ea646cf87a6f8b1b84d22 it happened after i tried to collect a post with max cap already reached (i am not sure it is connected but it might be)

### Expected Behavior

The post should be collected and transaction confirmed

### Steps To Reproduce

Go to https://lensport.io/p/81134_1760# click collect confirm transaction

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Firefox

**Comment by bigint** [comment]
This issue is not related to Lenster
