### ISSUE TITLE
Stoped reciveing NFTs of following people

### ISSUE THREAD

**Issue by DanIsNearby** [lensterxyz/lenster#1143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After following somone on Lenster i dont recive the follower NFT i think it might be related to Supper follow as for me and for [@kleak.lens](https://lenster.xyz/u/kleak.lens) the problem ocured after intereacting with supper follow

### Expected Behavior

After following somone seeing an follower NFT in OS

### Steps To Reproduce

Go to any profile follow and wait 5 minutes go to OS see that the NFT isnt there

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Firefox

**Comment by DanIsNearby** [comment]
Cant refollow people as when i try to unfollow i get "You are not following this profile"

**Comment by bigint** [comment]
This is expected and not related to Lenster 🙏🏼

**Comment by Kleak** [comment]
Not receiving the FollowNFT is expected ?
