### ISSUE TITLE
People can't follow me

### ISSUE THREAD

**Issue by Aytunsky** [lensterxyz/lenster#1145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can follow people but they can't follow me back

### Expected Behavior

I supposed to be follow back 

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome, Brave

**Comment by bigint** [comment]
Please explain the issue 🙏🏼
