### ISSUE TITLE
Updated profile page tabs/filters and NFT gallery

### ISSUE THREAD

**Issue by jounih** [lensterxyz/lenster#1148]
Small tweaks to the tabs - and adding filters to "Feed" and Media" tabs.

Would be great to see what people have collected - so adding a new tab for "Collected" - would be the posts you've collected

and "Gallery" the current NFTs tab, but without Lens collected posts or follow NFTs - just normal NFTs. 

And the filters on feed allow you to choose between posts, mirrors and likes. Similarly filters on media allow you to filter between different media types.

![Image](https://user-images.githubusercontent.com/10109867/200794238-ef09c6dd-b208-4fd0-8773-bb91c74783a4.png)

![Image](https://user-images.githubusercontent.com/10109867/200794281-63e12637-3598-46ca-81d1-8cca00ef9990.png)

**Comment by sasicodes** [comment]
Media filters - https://github.com/lensterxyz/lenster/pull/1149

**Comment by sasicodes** [comment]
We need API changes for `Feed` and `Collected`

**Comment by bigint** [comment]
We can move this internally as an API request 🙇
