### ISSUE TITLE
(JS-0323) Detected usage of the `any` type

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#115]
## Description
The `any` type can sometimes leak into your codebase. TypeScript compiler skips the type checking of the `any` typed variables, so it creates a potential safety hole, and source of bugs in your codebase. We recommend using `unknown` or `never` type variable.

## Occurrences
There are 60 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lensterxyz/lenster/issue/JS-0323/occurrences/](https://deepsource.io/gh/lensterxyz/lenster/issue/JS-0323/occurrences/)

Also need to fix this https://github.com/lensterxyz/lenster/issues/116

**Comment by jelilat** [comment]
Rather than using the `any` or `never` type, can we create Lenster types for this? Something like in the screenshot 

@bigint 

<img width="584" alt="Screenshot 2022-07-27 at 14 54 35" src="https://user-images.githubusercontent.com/23613565/181265058-4f4f6137-78bb-428f-8ec5-c0c81f45ce2f.png">

**Comment by bigint** [comment]
@jelilat I don't think so, that file is to add only custom types, but in this case we don't want custom types in all places 🙇🏻

**Comment by adarshzpatel** [comment]
Hey , we have to just rename the `any`  with `unknown` ?

**Comment by bigint** [comment]
Hey @adarshzpatel no, we need to use proper types 🙇🏼

**Comment by izayl** [comment]
@bigint I have removed some `any` notation (still remain some API Level need to be removed), can you give me some review of it?

#537
