### ISSUE TITLE
(JS-0295) Found `// @ts-<directive>` comments

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#116]
## Description
TypeScript provides several directive comments that can be used to alter how it processes files. Using these to suppress TypeScript Compiler Errors reduces the effectiveness of TypeScript overall.

## Occurrences
There are 5 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lensterxyz/lenster/issue/JS-0295/occurrences/](https://deepsource.io/gh/lensterxyz/lenster/issue/JS-0295/occurrences/)

**Comment by piraces** [comment]
Hi @bigint ! I have been working on this and I have opened a new PR to solve this deepsource issue.
