### ISSUE TITLE
Post content displayed in link preview

### ISSUE THREAD

**Issue by chair28980** [lensterxyz/lenster#1160]
### Summary

Currently when sharing a post link from Lenster the preview content is the standard biolerplate text.

![Screenshot 2022-11-10 at 12 56 18 PM](https://user-images.githubusercontent.com/29414216/201170962-b1fc9577-08a8-4104-9269-dfe9149e8b69.png)

Please add post previews containing post content in shared links.

**Comment by bigint** [comment]
This is fixed now 🚀 

<img width="681" alt="Screenshot 2022-11-28 at 9 17 13 AM" src="https://user-images.githubusercontent.com/69431456/204189898-618178be-83ad-4155-85fb-1e9bc598f18b.png">
