### ISSUE TITLE
Add IPFS upload fallback

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#1166]
We are using 4everland for upload media, we need to add estuary in case the 4everland upload got failed

**Comment by obelisk-dev** [comment]
Hey @bigint Whats the idea behind this? Try to upload again, upload to another IPFS hosting service, use a backup solution?

**Comment by saurabhdoteth** [comment]
@bigint which IPFS client should we use? pinata, infura?

**Comment by bigint** [comment]
infura is good for now 🙇🏼

**Comment by Sagargajare** [comment]
@bigint is this issue still on?
I would like to solve it.

**Comment by bigint** [comment]
@Sagargajare yes you can pick this up 🚀

**Comment by darkstudy45** [comment]
I can do this. give me the file

**Comment by bigint** [comment]
@darkstudy45 https://github.com/lensterxyz/lenster/blob/main/apps/web/src/lib/uploadToIPFS.ts

**Comment by bigint** [comment]
This is done!
