### ISSUE TITLE
Open original opens post page

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#1176]
<img width="653" alt="Screenshot 2022-11-13 at 10 17 57 PM" src="https://user-images.githubusercontent.com/69431456/201533495-03a41e1c-88a9-4112-b275-071f434dd277.png">

On clicking the `Open original`, it opens the post as well

**Comment by foolo** [comment]
Seems like it may be an easy fix, if just a few more details is provided. What does "original" refer to?

**Comment by foolo** [comment]
@bigint Seems like it may be an easy fix, if just a few more details is provided. What does "original" refer to?

**Comment by bigint** [comment]
@foolo updated 🚀 

I think event.stopPropogation() might fix

**Comment by foolo** [comment]
@bigint You were right :)
