### ISSUE TITLE
Not eligible for gitpoap.

### ISSUE THREAD

**Issue by imranmahmudshoiball** [lensterxyz/lenster#1180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have contributed in lenster gitcoin grant 14. But I am not eligible for claim lenster gitpoap.

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Brave

### Anything else?

![IMG_20220704_001628](https://user-images.githubusercontent.com/66163409/201418768-50236aee-7bf4-43a8-a2b9-2bdfa1a33dbe.jpg)

![Screenshot_2022-11-12-00-50-51-718_com brave browser](https://user-images.githubusercontent.com/66163409/201419007-c7fa2cf6-083d-4481-a539-396f27526a11.jpg)

**Comment by imranmahmudshoiball** [comment]
How to claim lenster gitcoin contribution gitpoap?

**Comment by bigint** [comment]
You must contribute to code inorder to get gitpoap 🙏🏼
