### ISSUE TITLE
Client-side exception error

### ISSUE THREAD

**Issue by jelilat** [lensterxyz/lenster#1187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting this error when I visit the Homepage after logging in

“ Application error: a client-side exception has occurred (see the browser console for more information).”

### Expected Behavior

It should show my feed instead

### Steps To Reproduce

Login to Lenster, then go to “Home”

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome, Safari

### Anything else?

![4DEF7FAE-B7F4-4F71-B64E-213F612465F0](https://user-images.githubusercontent.com/23613565/201511927-ba300a52-e573-4517-95f6-ead4e78b021b.png)

**Comment by jelilat** [comment]
Checked the logs and here's what I got 
<img width="993" alt="Screenshot 2022-11-13 at 09 07 46" src="https://user-images.githubusercontent.com/23613565/201512221-6d9bf0ab-df20-40f3-9cc1-f69fcb8f9130.png">

**Comment by svitekpavel** [comment]
👍 The last error `Parser.replaceTokens` seems to be from `escape-html` 

<img width="525" alt="Screenshot 2022-11-13 at 14 51 35" src="https://user-images.githubusercontent.com/988706/201525286-3b0b195b-a577-4108-84d9-383de3df0bce.png">

**Comment by foolo** [comment]
@jelilat It may be related to some of the particular posts you see on the home page. Not sure if you do see any posts (maybe the error happens before), but if you do, maybe you can post links to the firsts posts you see?

**Comment by jelilat** [comment]
@foolo I didn't see any post before the error shows up. But I tried refreshing the page again just now to confirm and I can see that the error no longer shows up.

So yes, it may have something to do with the posts.

Although I can no longer recreate this, I think it should still be investigated further.

**Comment by svitekpavel** [comment]
@jelilat it's this post `http://localhost:4783/posts/0x5b8b-0x076f`. It's caused by string `***ENS***` -> when italic is wrapped in bold / bold is wrapped in italic. When you reverse the matchers in `Markup` component so that `MDItalicMatcher` is before `MDBoldMatcher`, the component doesn't crash, but bold is not parsed corectly.

```
new MDItalicMatcher('mdItalic'),
new MDBoldMatcher('mdBold'),
```

But this is the gist of the problem.

**Comment by jelilat** [comment]
@svitekpavel This makes sense. 

Great job investigating that. Should probably create a PR to fix it.

**Comment by foolo** [comment]
@svitekpavel Good find! I have already fixed some similar bugs related to the ordering of the matchers. For example https://github.com/lensterxyz/lenster/pull/1179
If any of you want to take on fixing this new bug, you may find some ideas from there :)

**Comment by svitekpavel** [comment]
@foolo I played with the Regex matchers and here's a solution. You can integrate it to #1179 

```tsx
// MDBoldMatcher.tsx

import type { ChildrenNode } from 'interweave';
import { Matcher } from 'interweave';

export class MDBoldMatcher extends Matcher {
  replaceWith(children: ChildrenNode) {
    return <b>{children}</b>;
  }

  asTag(): string {
    return 'b';
  }

  match(value: string) {
    return this.doMatch(value, /\*\*([^**]*?)\*\*/u, (matches) => ({
      match: matches[1]
    }));
  }
}
```

```tsx
// MBItalicMatcher.tsx

import type { ChildrenNode } from 'interweave';
import { Matcher } from 'interweave';

export class MDItalicMatcher extends Matcher {
  replaceWith(children: ChildrenNode) {
    return <i>{children}</i>;
  }

  asTag(): string {
    return 'i';
  }

  match(value: string) {
    return this.doMatch(value, /\*([^**]*?)\*/u, (matches) => ({
      match: matches[1]
    }));
  }
}

```

**Comment by jelilat** [comment]
@svitekpavel You should probably create a new PR for it #1179 has already been merged

**Comment by svitekpavel** [comment]
https://github.com/lensterxyz/lenster/pull/1189
