### ISSUE TITLE
can't claim gitpoap

### ISSUE THREAD

**Issue by dac0914** [lensterxyz/lenster#1191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have contributed lenster in gitcoin grants but I still can't claim gitpoap. Discord chat has been dead. Can you help me?

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Edge

**Comment by bigint** [comment]
You need to be a code contributor to get it 😌
