### ISSUE TITLE
Line break not working as expected

### ISSUE THREAD

**Issue by emptybrother7** [lensterxyz/lenster#1193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

its posting like this: ![image](https://user-images.githubusercontent.com/54287547/201581778-5e87a187-1bbf-42ef-b7e4-c84e54e6df65.png)

### Expected Behavior

when i input this: 
![image](https://user-images.githubusercontent.com/54287547/201581870-5c7828b2-ff1f-4511-9784-70c6ae61099d.png)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Edge

**Comment by foolo** [comment]
@bigint, I think for now, it would be enough to solve part 1 above (i.e. changing visual appearance of `<p>` and `<br>` in Editor), as it would give the user a predictable result. (Maybe in the future one could change the rendering part to an off-the-shelf markdown decoder.)

Any opinion on this change?

**Comment by bigint** [comment]
cc @harish-sethuraman is this related to Lexical? 🙇🏼

**Comment by harish-sethuraman** [comment]
We make the correct markdown in lexical editor. May be while rendering it is adding another line break? We can check this during rendering? @bigint 

@foolo  
`there is no visual difference between newline (<br>) and paragraphs (<p>).` did you check the markdown output? after clicking on the pubblish button? in that it should work well only?

**Comment by foolo** [comment]
@harish-sethuraman I meant that there is no visual difference in the editor, before publishing. User can make paragraphs or newlines (Enter, and Shift+Enter respectively) but you don't see the visual difference in the editor (but it's still there). I shows later, when rendering the post.
Yes, I checked the output. Paragraphs are converted to "\n\n" in markdown, (just as it should),  and newlines to "\n" (again, just as it should).

I guess the "correct" solution for problem 2 above, would be to do a full markdown decoding in the rendering, (since we do a full markdown encoding on publishing).

**Comment by harish-sethuraman** [comment]
We are not migrating to newer renderer. That should handle all these issues 🎉

**Comment by foolo** [comment]
> We are not migrating to newer renderer. That should handle all these issues tada

Migrating to a new renderer would probably solve problem 2. But problem 1 would still be there, that in the editor, user can't see the difference between newlines and paragraphs.
Btw, did you intend to write "We are **now** migrating" ? :)

**Comment by harish-sethuraman** [comment]
for 1. we can consider tweaking with line spacing that should be better I guess

**Comment by foolo** [comment]
> for 1. we can consider tweaking with line spacing that should be better I guess.
I agree.

> But also take a look at github's comment editor it works the same way too.
Hmm, for me it does not. For me Shift+Enter and Enter has the same effect in Github's editor. They both produce newline. To make a new paragraph, I need to press Enter twice.

**Comment by harish-sethuraman** [comment]
Can you provide a screen recording please? That will help me understand a bit more.

**Comment by foolo** [comment]
> Can you provide a screen recording please? That will help me understand a bit more.

A recording of what? Of Github or Lenster? What behavior do you want clarification on?

**Comment by foolo** [comment]
Not sure if I can create a video that adds anything useful. For me personally, I would consider the issue as fixed good enough if we modified the stylesheets for Editor to increase line spacing between `<p>` paragraphs.

**Comment by foolo** [comment]
Original problem still appearing when **pasting** tex:

**In editor:**
![Screenshot_2023-02-07_10-12-13](https://user-images.githubusercontent.com/667227/217263182-a721221b-be5f-4a61-b957-ad50bc0915a6.png)

**Published result:**
![Screenshot_2023-02-07_10-12-40](https://user-images.githubusercontent.com/667227/217263250-e1f2e0a3-63b6-4b15-8aff-860056a1e759.png)
