### ISSUE TITLE
Typo on Replies section

### ISSUE THREAD

**Issue by noctherion** [lensterxyz/lenster#1195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I think the following statement is not a correct English. 

@yagiz.lens hasn’t repliesed yet!
![lenster](https://user-images.githubusercontent.com/93202400/201604446-a7b66777-17c7-4727-97d3-a21e5dc45f16.JPG)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by foolo** [comment]
Same problem with Media:
![Screenshot_2022-11-15_18-38-25](https://user-images.githubusercontent.com/667227/201988487-8d1b1a3d-2766-49ae-8215-7fe5441edcd9.png)
