### ISSUE TITLE
Add rel="me" to a profile's website url.

### ISSUE THREAD

**Issue by haideralipunjabi** [lensterxyz/lenster#1234]
### Summary

Adding the `rel="me"` attribute to the website's link is used to verify that the profile page belongs to the user. This is a feature used by [Mastodon to verify websites](https://docs.joinmastodon.org/user/profile/)

Also, I would like to work on this issue.

**Comment by alandooz** [comment]
@haideralipunjabi maybe you can start working on this now that the labels were updated

**Comment by haideralipunjabi** [comment]
Sure. Thanks
