### ISSUE TITLE
content loading from ipfs doesn't redirect correctly with IPFS companion.

### ISSUE THREAD

**Issue by wanderer** [lensterxyz/lenster#1235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to load media from ipfs directly by using ipfs conpanion the following errors occur
```
Access to image at 'http://127.0.0.1:8080/ipfs/bafybeifmqwbntxydvauuqtuo36xlkhgaszcvtoqmbyaijazq6oxjc7sbtm' (redirected from 'https://lens.infura-ipfs.io/ipfs/bafybeifmqwbntxydvauuqtuo36xlkhgaszcvtoqmbyaijazq6oxjc7sbtm') from origin 'https://lenster.xyz' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
```

### Expected Behavior

that the media is load from ipfs

### Steps To Reproduce

- install ipfs and run it
- install ipfs companion

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
This is not related to lenster 🙇🏼
