### ISSUE TITLE
can't access my profile any more

### ISSUE THREAD

**Issue by sakulstra** [lensterxyz/lenster#1236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the app crashes

### Expected Behavior

it doesn't crash :)

### Steps To Reproduce

access https://lenster.xyz/u/sakulstra.lens

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![image](https://user-images.githubusercontent.com/4396533/202508782-94eca5ad-e08a-4abd-834f-8d3276068333.png)

**Comment by foolo** [comment]
This is the specific post that causes the crash https://lenster.xyz/posts/0x101e-0x07
Problem related to nesting code formatting and italic tags.
