### ISSUE TITLE
Wallet Login Issue

### ISSUE THREAD

**Issue by shunkakinoki** [lensterxyz/lenster#1239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It doesn't work, the auth query returns an invalid token

Before (commit: bca14ef14712abf5d6c8452e93dc48e3cfd23f2f) at https://lenster-git-selected-preview-item-background-lenster.vercel.app/

https://user-images.githubusercontent.com/39187513/202594518-5ea5ae97-0e20-46ad-b9f5-ad80dea0b43b.MP4

After (commit: 4360cc6e293b383217512fbc9569ca9c06ba058c at https://lenster.xyz

https://user-images.githubusercontent.com/39187513/202595126-124f3ed1-30ad-4ef3-820c-e12af63f898b.MP4

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Safari iOS

**Comment by bigint** [comment]
Wow weird issue, lemme try to reproduce it 🙇🏼

**Comment by shunkakinoki** [comment]
Thank you so much 🙇‍♂️
I'm using Light Wallet (full disclosure, I'm working on it)
If you're on iOS, you can install it here at: https://wallet.light.so
The github is at: https://github.com/LightDotSo/Wallet

**Comment by shunkakinoki** [comment]
@bigint 

Works after this pull request 🥳

https://github.com/lensterxyz/lenster/pull/1389

**Comment by shunkakinoki** [comment]
Thank you so much for this @bigint appreciate your love and support 🙇‍♂️
