### ISSUE TITLE
Follower Popup window.

### ISSUE THREAD

**Issue by lihanbok** [lensterxyz/lenster#1241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is no difference between me and others when showing the Followers popup window.

### Expected Behavior

There should be a difference between me and others when showing Followers popup window. 
Example: my account TCL change to TCL(Me)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
There is no follower popup in lenster
