### ISSUE TITLE
Cant read the text or contents when we are in dark mode

### ISSUE THREAD

**Issue by mrvje** [lensterxyz/lenster#1253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Its not a bug more of a UI issue

using black text on a darker screen layout doesnot seem to work please re-optimize the darkmode in Lenster.
Also please provide the light/dark mode directly on the top bar in the all pages that we can access.

Thanks.
dudewith.lens

### Expected Behavior

to be clearly identify the text when in dark mode.

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome, Brave

### Anything else?

![image](https://user-images.githubusercontent.com/113583751/202850218-aeaf56ce-a16d-4c79-9bff-1aa78473a369.png)
red highlighted area = black text & background conflicting.
green highlighted area = toggle for light/dark mode.

**Comment by foolo** [comment]
Created separate issue, #1268, about making dark mode option more available

**Comment by foolo** [comment]
@mrvje Any additional info on this? Does it still happen? For me it looks OK, see screenshot below. Maybe some extra conditions are needed to reproduce it.
![Screenshot_2022-11-22_14-27-02](https://user-images.githubusercontent.com/667227/203325725-003b16e6-12c3-47e8-bca9-aae7da101df4.png)

**Comment by mrvje** [comment]
![image](https://user-images.githubusercontent.com/113583751/203389329-c9675de4-62bf-41f1-97f0-4b11d33c3f39.png)
Now its the same on chrome browsers but it works fine with brave I think

![image](https://user-images.githubusercontent.com/113583751/203390831-9dc1122a-1560-41c2-9d37-b11e105a0451.png)

**Comment by foolo** [comment]
Similar question as in #1198: One guess is that it may be related to some browser extension. You could try disabling different extensions.

**Comment by foolo** [comment]
@bigint Is this up for grabs? even though marked with "addresszero" tag (what is that btw? 🙂)

**Comment by 0xchetan** [comment]
@bigint did you get chance to fix this?

**Comment by bigint** [comment]
Should be fixed
