### ISSUE TITLE
Darkmode problem

### ISSUE THREAD

**Issue by OHIRAH** [lensterxyz/lenster#1257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can not see the word on Dark mode. becase of Black

### Expected Behavior

white word is better. like twitter dark mode.

### Steps To Reproduce

.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![Screen Shot 2022-11-20 at 2 26 59](https://user-images.githubusercontent.com/90397620/202863751-ea7d10bd-d2c8-43e5-8af7-f7a52ac944f2.jpg)

**Comment by bigint** [comment]
Closing this in favor of https://github.com/lensterxyz/lenster/issues/1253 🙇🏼
