### ISSUE TITLE
The system allows users to follow him/herself

### ISSUE THREAD

**Issue by tann9949** [lensterxyz/lenster#1258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Generally, it doesn't make sense for social media to follow him/herself. However, it seems that I was able to follow myself in Lenster.

### Expected Behavior

It doesn't make sense for the recommendation engine to recommend your account and allow the user to follow your account. Additionally, I can't even unfollow myself on the page. I think this is a minor bug but an issue worth fixing.

### Steps To Reproduce

Here are the following steps I take to be able to follow my account. 

### 1. Write any text to the feed
I have a very limited number of followers/following. I think this is also an important parameter to reproduce this bug as well.

### 2. Browse to that feed posted in step 1. Looking for `following` recommendation
When I was looking at my feed, there was a recommendation on the right side tab to follow my account:

<img width="1440" alt="Screenshot 2565-11-20 at 14 41 55" src="https://user-images.githubusercontent.com/34812325/202891366-9537934d-fda3-4634-ab87-7c5f1d1fff79.png">

### 3. Follow yourself
So I decided to try to see if it's possible to follow my account. It turns out that I can. I am currently following myself, and I couldn't unfollow myself either.

<img width="1440" alt="Screenshot 2565-11-20 at 14 44 25" src="https://user-images.githubusercontent.com/34812325/202891392-423bb2c3-b3ae-4228-b864-5bf9868d1436.png">

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by bigint** [comment]
This is expected according to lens protocol

**Comment by kenio** [comment]
> This is expected according to lens protocol

Okey, so how i can unfollow myself? :)
