### ISSUE TITLE
Follow bug

### ISSUE THREAD

**Issue by Yns34** [lensterxyz/lenster#1266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am following a user. it succeeds and shows following. But when I refresh the page it shows unfollow. 
I don't always get this error. I very rarely get this error.

### Expected Behavior

This should not change if it seems that I follow the account

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
This should be fixed
