### ISSUE TITLE
Enable dark mode option also when not signed in

### ISSUE THREAD

**Issue by foolo** [lensterxyz/lenster#1268]
### Summary

Currently, dark mode mode is only available from the profile menu, which is only available when user is signed in.
Suggesting to move the dark mode toggle to a place where it is accessible also when user is not logged in.

**Comment by bigint** [comment]
Suggesting to use dark mode is not a good idea it seems, if a user loves light mode it will be like forcing to use dark mode 🙇🏼

**Comment by foolo** [comment]
Ahh, maybe I worded the issue badly :) I just wanted to give users the *possibility* to swich to dark mode if they want, even if they are signed out. (At the moment they must sign in to access dark mode). But of couse it's not a big problem because the user will normally be signed in :)
