### ISSUE TITLE
Show absolute timestamp when hovering mouse cursor over "x days ago"

### ISSUE THREAD

**Issue by foolo** [lensterxyz/lenster#1269]
### Summary

Show a popup label with absolute date and time when user hovers mouse cursor over a relative timestamp (e.g. "5 days ago").
The feature already exists on messaging page (added in #1137) but not in other places on the website.

Example:
![vlcsnap-2022-11-21-15h20m39s080](https://user-images.githubusercontent.com/667227/203078652-740c3a9d-18eb-46ac-a4cd-fa30f2db2020.png)

**Comment by foolo** [comment]
@bigint I can implement this, but I just want to check first if you think it's a good idea? To avoid doing unnecessary work :)

**Comment by bigint** [comment]
I don't think its good to show a tooltip for this, native tooltip is fine for this

**Comment by foolo** [comment]
> native tooltip is fine for this

@bigint I guess with "native tooltip" you mean it's OK to simply add for example a `title` html attribute tag , so that the browser's native tooltip is used?
Like here:
https://github.com/lensterxyz/lenster/pull/1137/files#diff-a70761abc7cee89a75a1bda903f5aa207d9a4cf04b825393cfa60f4c70efca92
