### ISSUE TITLE
"Method not found" error on any action

### ISSUE THREAD

**Issue by pshishkin** [lensterxyz/lenster#1271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to post something or comment; Also when I click Enable Dispatcher, I see the following error:
![tg_image_4028020519](https://user-images.githubusercontent.com/14850937/203113586-df3fa2e2-1eef-4ab8-8869-37d6889c0368.jpeg)

I've tried clearing cache, cookies, local storage. I've tried another browser. Didn't help.

### Expected Behavior

I can post or comment; comment or post appears after I do them.

### Steps To Reproduce

Login with wallet connect to https://lenster.xyz/
Try to create a post.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome, Brave

**Comment by bigint** [comment]
I can't reproduce this @pshishkin 🙇🏼
