### ISSUE TITLE
(JS-0465) Consider adding a `defaultProps` definition

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#128]
## Description
All non-required prop types of a component must have a corresponding `defaultProps` value.

## Occurrences
There are 98 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lensterxyz/lenster/issue/JS-0465/occurrences/](https://deepsource.io/gh/lensterxyz/lenster/issue/JS-0465/occurrences/)

**Comment by shanpriyan** [comment]
@bigint Do we even need to use `defaultProps` here? since we are already using `Typescript`.
![image](https://user-images.githubusercontent.com/42532987/181612822-7bbaec74-d65e-4c4b-92d8-7745e92957a5.png)
