### ISSUE TITLE
see through lens select ui looks weird

### ISSUE THREAD

**Issue by ercwangwh** [lensterxyz/lenster#1297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Login lenster on mobile, new feature of My Feed filter didn’t align with Timeline & Highlights. Click it shows drop down menu, but can’t see the full content.

### Expected Behavior

It should align with Timeline and Highlights. It should show the menu clearly. 
The bug occurs when the filter “show posts, mirrors, likes” is displayed.
I think it should be better to move My Feed to next line, right most to screen.

### Steps To Reproduce

1, login lenster on mobile
2, homepage My Feed display incorrectly 
3, click Highlights it display correctly, but the filter of “show posts, mirrors, likes” disappeared.

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Safari

### Anything else?

![94F73871-0FBD-4EED-A83C-24E70168B748](https://user-images.githubusercontent.com/45984686/203751387-893e9d9a-e835-4527-86d1-ae456ef13e52.jpeg)

**Comment by bigint** [comment]
cc @sasicodes 🙏🏼

**Comment by Sagargajare** [comment]
I fixed this issue already. 
but my pre-commit hook of linting is failing.

@bigint please help me.

**Comment by Sagargajare** [comment]
@sasicodes Can you help me with it?

**Comment by sasicodes** [comment]
@Sagargajare can you share the error?

**Comment by sasicodes** [comment]
> ![image](https://user-images.githubusercontent.com/56780589/205594248-97dbd0bd-d988-4bc1-becd-ec575c63e8cb.png)

what are those 134 errors? try fixing it by running lint fix.

**Comment by Sagargajare** [comment]
Thanks, @sasicodes. 
Lint fix worked

**Comment by 0xchetan** [comment]
@bigint seems like this is already fixed. Can we close this?
