### ISSUE TITLE
Subscribe to yourself

### ISSUE THREAD

**Issue by d1man322** [lensterxyz/lenster#1311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you click on followers with people and see your profile, you get the option to subscribe to yourself and writes successfully

### Expected Behavior

When you click on followers with people and see your profile, you get the option to subscribe to yourself and writes successfully

### Steps To Reproduce

Dont know code :(

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

Nope

**Comment by bigint** [comment]
This issue is related to lens api and not with lenster 🙏🏼
