### ISSUE TITLE
Support for ERC-1271 / smart contract wallet

### ISSUE THREAD

**Issue by PhABC** [lensterxyz/lenster#1320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not able to sign-in on lenster with smart contract wallets 

### Expected Behavior

Sign-in message signed by smart contract wallet should work

### Steps To Reproduce

Try to sign signature meSsage with smart contract wallet (e.g. Sequence or Argent)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome, Firefox, Brave, Safari, Edge

### Anything else?

You can use the following method from our sequence SDK to validate signatures from both EOAs and smart contract wallets:

```ts

// The sequence utils `isValidMessageSignature` method can validate signatures
// from any kind of wallet (ie. EOA or Smart Wallet) which includes Metamask, Coinbase,
// and Sequence.
const isValid = await sequence.utils.isValidMessageSignature(
  walletAddress,
  message,
  signature,
  provider,
  chainId // optional, as it will use the chain id from the provider
)
```

More info [here](https://docs.sequence.xyz/wallet/guides/sign-message#verifying-message-signatures)

**Comment by bigint** [comment]
We dont have any immediate plans for supporting now 🙏🏼 

We will create epic for this 🚀 

Feel free to create POCs with **sequence** if you have time

**Comment by gnardini** [comment]
Smart contract wallets can provide much better UX than MetaMask, is there a possibility to reconsider this? A lot of the innovation in the wallet space is happening around it and Account Abstraction. 

It should be a very small task, the only thing that needs to be changed is the place where you verify the signature, you need to call `isValidSignature` from the contract if the address is a smart contract.

I would love to implement it for you (I'm happy not to use any external libraries if that's preferred) but the signature verification is happening in the backend, which is not public. Here is were the GraphQL call is being made: https://github.com/lensterxyz/lenster/blob/main/apps/web/src/components/Shared/Login/WalletSelector.tsx#L81
Just need to fix it there :)

Any chance you will reconsider? @bigint This is a blocker for many growing wallets.
