### ISSUE TITLE
Make the dispatcher more forgiving for Hardware wallet users. 

### ISSUE THREAD

**Issue by Pippibob** [lensterxyz/lenster#1323]
### Summary

Using af hardware wallet like Ledger in combination with metamask makes signing very tiresome. Even with the dispatcher activated users still have to sign many times during a day checking Lenster, profile and following other users. 

Could the dispatcher be more forgiving?

**Comment by bigint** [comment]
This issue is related to lens api, lenster is just a frontend for lens protocol 🙏🏼 

Closing this as not related 🙏🏼
