### ISSUE TITLE
After changing user profile, click save without change

### ISSUE THREAD

**Issue by casuox** [lensterxyz/lenster#1331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After changed the user profile, the user profile did not change after clicking Save. Whether uploading a background image or changing the name, the same bug would appear

### Expected Behavior

Hope to solve this problem as soon as possible, after all, updating user information is very important

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
It will take some time to update 🙇🏼
