### ISSUE TITLE
Can't find who am I tagging along in the post section, Might be a font color issue

### ISSUE THREAD

**Issue by mrvje** [lensterxyz/lenster#1333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

I have been using lenster 
and just noticed that I cant see whom am I tagging other than their profile.
It's been a white BG, and the font is too white so there might be an mishap.
Look into it 
Thanks
dudewith.lens

![2 lenster bug 2](https://user-images.githubusercontent.com/113583751/204718478-15447c02-472e-4ab2-842d-c3b8b1852e9b.jpg)

**Comment by foolo** [comment]
Possibly same problem as #1253. I suspect it might be related to browser extensions. Have you tried disabling extensions, or tried with a different browser?

**Comment by foolo** [comment]
@bigint Looks like this issue can be closed. Should be fixed already, according to comment https://github.com/lensterxyz/lenster/pull/1354#issuecomment-1336771554
