### ISSUE TITLE
Add mastodon social link verification support

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#1339]
### Summary

Add mastodon social link support for users

<img width="535" alt="Screenshot 2022-12-02 at 10 59 40 AM" src="https://user-images.githubusercontent.com/69431456/205221603-dcbe5b46-2770-4f92-85cf-267954868cd7.png">

<img width="353" alt="Screenshot 2022-12-02 at 11 00 04 AM" src="https://user-images.githubusercontent.com/69431456/205221672-b71aabca-1076-439e-a22e-f596de6ea0fe.png">

https://mastodon.social/@wongmjane@macaw.social

**Comment by haideralipunjabi** [comment]
I don't think this works, despite my PR. I think it is because the user profile pages on lenster are rendered on the client, and Mastodon doesn't support JS rendered pages yet.

It should fix itself when Server Sided Components become stable on Next, and Lenster also adopts them
