### ISSUE TITLE
Migrate to rainbow wallet

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#1340]
### Summary

Migrate to rainbow wallet

**Comment by LyghtCode** [comment]
i have done this locally how do i confirm bounty?

**Comment by bigint** [comment]
You can drop your wallet address/lens address here, after we merge the PR I'll send the bounty there 🙇🏼

**Comment by agustif** [comment]
Is still available to work on?

**Comment by foolo** [comment]
> Is still available to work on? @bigint or has someone else fixed it already

There's an open PR for this: https://github.com/lensterxyz/lenster/pull/1613

**Comment by bigint** [comment]
Not a plan for now 🙇

**Comment by bigint** [comment]
@foolo Hope you got the bounty 🙇

**Comment by foolo** [comment]
> @foolo Hope you got the bounty bow

@bigint I did, yes, thanks!
