### ISSUE TITLE
Same image got duplicated when uploading multiple images

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#1341]
### Summary

Same image got duplicated when uploading multiple images

https://user-images.githubusercontent.com/69431456/205222104-fb83872b-e9bb-4f4a-af8c-169f6480364c.mov

**Comment by bigint** [comment]
https://docs.lens.xyz/docs/gated#erc20-token-ownership

**Comment by bigint** [comment]
@hungds99 drop your wallet address here so we can send bounty ASAP 🙏🏼

**Comment by hungds99** [comment]
@bigint 0x33eb679e966d117c8b2629088c7d9c013a8247d4 (Polygon)
Thanks you, I will keep contribute 🏗️

**Comment by bigint** [comment]
@hungds99 here you go https://polygonscan.com/tx/0x908b929beec9291b34bb94919acc1d1c2aa47fdd051e9e4a573310a97b8d9e08
