### ISSUE TITLE
Remove `.lens` everywhere

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#1342]
### Summary

- [ ] <Slug /> component
- [ ] URLs
- [ ] Mentions
- [ ] Mention in composer

But still we should not touch the service layer, all needs to be done in UI layer

**Comment by subhradwip01** [comment]
I would like to work on that issue... Can I give a try?

**Comment by bigint** [comment]
Fixed in https://github.com/lensterxyz/lenster/pull/1352
