### ISSUE TITLE
Shows multiple accounts for the same users

### ISSUE THREAD

**Issue by 0xchetan** [lensterxyz/lenster#1364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As displayed in the screenshot below. Switch to sections shows same username multiple times.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

<img width="230" alt="Screenshot 2022-12-06 at 10 54 19 PM" src="https://user-images.githubusercontent.com/11252918/205980200-c11a3234-0e88-4b0b-aba9-05673f53a4ff.png">

**Comment by bigint** [comment]
Thanks for the report @0xchetan, I just set $20 bounty for this

**Comment by bigint** [comment]
Fixed in #1395
