### ISSUE TITLE
Buy NFT Button

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#1368]
### Summary

A frontend button at a post level that renders when you input an opensea or other marketplace url link. This allows to purchase nft collection directly from lenster frontend.

https://lensverse.canny.io/lenster/p/buy-nft-button

**Comment by BowTiedHeron** [comment]
Thoughts on creating a bounty for this on [OpenQ](https://www.openq.dev/)? 
Bounty would be claimable by the contributor when the issue is closed through a PR.
OpenQ is free to use and Open Source. 
Happy to help you set it up and refer some devs to help out! :)

**Comment by BowTiedHeron** [comment]
Example of how I used this for Honey Finance:
https://app.openq.dev/contract/I_kwDOHB1JPc5Tux7f/0xe51ed089272f52fe2ca6b3070b4adfb8a0b7c221
https://github.com/honey-labs/honey-frontend/issues/188

**Comment by tobowers** [comment]
I think it would be nicer to support NFTs directly rather than through marketplaces.

**Comment by bigint** [comment]
Its on our roadmap @tobowers 🙇🏼

**Comment by BowTiedHeron** [comment]
Hey @bigint hope you don't mind me following up here.
Would you be open to list this bounty on [OpenQ](https://www.openq.dev/) (for free)?
I would love to help you find someone that pics this up for you.

I went through the Lenster discord as well to find a better way to follow up on this (sadly without success).
Please let me know if there are better ways to connect with the team!

**Comment by jordang7** [comment]
I'm interested in taking this on if the bounty is still open! @bigint

**Comment by bigint** [comment]
Not in plan for now
