### ISSUE TITLE
User is logged out/signed out when the view refreshes

### ISSUE THREAD

**Issue by AdamSHurwitz** [lensterxyz/lenster#1377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the view/web page refreshes or reloads my account, adamhurwitz.lens, is signed out of the account.

### Expected Behavior

When the view/web page refreshes my account, adamhurwitz.lens, remains signed into the account.

### Steps To Reproduce

1. Sign into a user account.
2. Refresh the web page.
3. Observe that the account is signed out.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Firefox

### Anything else?

**Attempted solutions**

- Disable Firefox protection and ad blocker.
- Add "https://lenster.xyz" to Firefox exception list for sites to delete cookies and clear data (Firefox should save any necessary cookies after this step).
- Disable computer's VPN.

**Comment by bigint** [comment]
Fixed in https://github.com/lensterxyz/lenster/commit/39dfe7129602ec5534a20348f06d8b60e8f18252
