### ISSUE TITLE
Mobile UX review

### ISSUE THREAD

**Issue by jounih** [lensterxyz/lenster#1381]
Audit mobile web experience and list issues

**Comment by bigint** [comment]
@jounih our aim is to release Lenster lite with PWA in the app and play store, so we need to do some work on improving the mobile view which looks more native

- [ ] Add bottom nav so it will look more native
- [ ] Remove all horizontal scroll

**Comment by civaaaaa** [comment]
Added bottom nav and re-structured IA to accomodate 'more' actions into profile.

<img width="1643" alt="Screenshot 2022-12-22 at 14 10 21" src="https://user-images.githubusercontent.com/36987969/209141377-30fe9f1c-8b02-4feb-911f-555e5c0d3e2e.png">

**Comment by bigint** [comment]
Shipped new navigation bars
