### ISSUE TITLE
Unable to connect to my wallet, please fix it 

### ISSUE THREAD

**Issue by iammendez100** [lensterxyz/lenster#1388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Inability to connect to my wallet

### Expected Behavior

Fast response on wallet connect 

### Steps To Reproduce

Work on it pls

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Chrome, Others

**Comment by bigint** [comment]
Please add more description
