### ISSUE TITLE
Infinite scroll of the same NFTs over and over again bug on the NFT tab of a Lenster Profile

### ISSUE THREAD

**Issue by GotchaGuy** [lensterxyz/lenster#1390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I went to the NFT tab of a lenster profile and scrolled down to see NFTs the account owns. I kept scrolling down and there keeps being more to scroll, however the account only has 5 NFTs and they keep being loaded and looped over and over again to infinity.

### Expected Behavior

The infinite scroll should work in a way that it allows partial loading of NFTs depending on how far you scroll down, however once you reach the end of the list, the already loaded NFTs should not load over and over again. To be concise, you should be able to get to the bottom and there should not be copies of the same unique NFT loaded.

### Steps To Reproduce

Go to NFT tab of a lenster profile and scroll down

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

<img width="1723" alt="Screenshot 2022-12-09 at 18 37 56" src="https://user-images.githubusercontent.com/43401549/206760494-2000e58b-e7cd-4e2c-a1a3-0a87558c9c1b.png">
<img width="1723" alt="Screenshot 2022-12-09 at 18 37 42" src="https://user-images.githubusercontent.com/43401549/206760564-447dbc33-e0f1-4f95-b809-8f636550e715.png">

As you can see, the same NFTs have been loaded over and over again

**Comment by bigint** [comment]
New implementation coming soon
