### ISSUE TITLE
Issues with domains already sold

### ISSUE THREAD

**Issue by jamie1314** [lensterxyz/lenster#1407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I sold fcofco7.lens five weeks ago. Today, two days of strange messages were automatically posted on my Twitter. After investigation, I found out that the news was posted by the domain name fcofco7.lens. The sold domain name is still bound to my Twitter.
![屏幕截图 2022-12-14 170813](https://user-images.githubusercontent.com/108017550/207554496-b91b3f9e-5124-44c0-bf51-9a6da38c4846
![屏幕截图 2022-12-14 171140](https://user-images.githubusercontent.com/108017550/207554504-26eac5d4-8b93-48bc-af42-1462d084f87b.png)
.png)
![屏幕截图 2022-12-14 171151](https://user-images.githubusercontent.com/108017550/207554511-f30291f2-cb10-4120-9ae0-fae24a03fc9a.png)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by sasicodes** [comment]
@jamie1314 https://twitter.com/settings/connected_apps

Remove access to `Reflect` account in your twitter.

**Comment by bigint** [comment]
cc @m1guelpf 👀

**Comment by bigint** [comment]
Closing as this is not related to Lenster 🙏🏼

**Comment by m1guelpf** [comment]
This should be fixed now too 😄
