### ISSUE TITLE
Pagination for Followers and Notications: subequent pages don't load

### ISSUE THREAD

**Issue by jMyles** [lensterxyz/lenster#1414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 On Firefox 108, Ubuntu 22.04, I'm experiencing broken behavior on the app insofar as it's only possible to load a list of 10 followers or 20 notifications.  The following seems to reliably occur:

* When opening the followers modal, the `PaginatedFollowersResult` type is loaded from the `/` endpoint.
* This object contains 10 items, each a `Follower`.
* These objects are rendered as followers and look normal.
* When scrolling to the bottom of the list, a new request is made, again to `/`, with `operationName: "MutualFollowers"`
* This request returns only a single follower object, which happens in this case to be the profile of Stani (@EthWarrior)
* This is not rendered, and instead the spinning wheel graphic persists.
![Screenshot from 2022-12-15 11-49-52](https://user-images.githubusercontent.com/311973/207925311-c7d6d9d4-73f5-4096-85b6-f109d7e0944a.png)
![Screenshot from 2022-12-15 12-05-40](https://user-images.githubusercontent.com/311973/207925314-e6f1ac3e-afce-42fe-b27f-7f6364419ed7.png)
* As you can see, there are some requests which are NS_BINDING_ABORTED - perhaps there is a cache malfunction related to these pages?

Trying to load Notifications produces identical behavior, except that the first page contains 20 objects instead of 10.

### Expected Behavior

For subsequent followers and notifications to load.

### Steps To Reproduce

Try to load the followers list on Firefox 108, Ubuntu 22.04.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Firefox

**Comment by bigint** [comment]
Fixed
