### ISSUE TITLE
Verification issue

### ISSUE THREAD

**Issue by OU63** [lensterxyz/lenster#1423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've downloaded Lenster for mobile to my cellphone (Xiaomi Redmi Note 8) But I cant connect.

### Expected Behavior

I want to use this application.

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Chrome

### Anything else?

![Screenshot_2022-12-17-23-34-40-832_com android chrome](https://user-images.githubusercontent.com/113309362/208265261-4284a862-4340-4285-94c7-6662f2622f25.jpg)

**Comment by bigint** [comment]
You need to be in polygon mainnet to use lenster, but we are working on removing network fricitions 🙇🏼
