### ISSUE TITLE
Webp NFT Avatars are not supported

### ISSUE THREAD

**Issue by Amory5727** [lensterxyz/lenster#1424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I try to select an NFT avatar that uses webp images then I get an error. 

### Expected Behavior

Selecting an NFT profile picture that uses webp images should not produce an error and show the desired image as my profile picture. 

### Steps To Reproduce

1. Login to lenster.xyz
2. Click your profile image on the top right
3. Select Your Profile from the menu
4. Press Edit Profile on the left
5. Select NFT Avatar
6. Select Ethereum as the chain
7. Use 0x9674739124d69d555712a30e0a44de648f4942 as the contract address
8. Use 1964 as the token id
9. Press Save
10. Sign the signature request
11. Receiving the following error
```
ERROR Download image - message: Not valid mime type - image/webp, tried downloading - https://meetnippy.mypinata.cloud/ipfs/QmNp8JeyTz6rN6ftnhcM5gpZEaePoXY4RWkJXQDeEhouFY/1965.webp
```

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome

**Comment by foolo** [comment]
@Amory5727 Trying to reproduce this. Seems like the address is missing "19" at the end. The address 0x9674739124d69D555712a30e0A44dE648F494219 exists however, but it doesn't seem to be a contract address: https://polygonscan.com/address/0x9674739124d69d555712a30e0a44de648f494219
Maybe you pasted the wrong address?

**Comment by foolo** [comment]
@Amory5727 Thanks!

**Comment by bigint** [comment]
cc @joshstevens19, it seems like an error from API 🙇🏼
