### ISSUE TITLE
Support for ENS' NFT avatars

### ISSUE THREAD

**Issue by danimesq** [lensterxyz/lenster#1460]
### Summary

Example: `eip155:1/erc721:{tokencontract}/{token-id}`

**Comment by bigint** [comment]
<img width="970" alt="Screenshot 2022-12-26 at 9 06 25 AM" src="https://user-images.githubusercontent.com/69431456/209496617-3edd8b74-e950-40b7-8d5f-c1a7217e96ca.png">

We already have this in profile settings https://lenster.xyz/settings

**Comment by danimesq** [comment]
@bigint not what I mean.

Its about automatically getting an ENS avatar from an user that didn't set an avatar yet.

**Comment by bigint** [comment]
@danimesq We are using stamp service for fallback avatars, if user don't have profile we check in multiple sources

https://github.com/snapshot-labs/stamp#resolvers

**Comment by danimesq** [comment]
And does it support ENS' NFT avatars (`eip155:1/erc721:{tokencontract}/{token-id}`)?

**Comment by bigint** [comment]
Why you wanna explicitly mention eip format? we get if from ENS resolvers, you don't need to think about tech behind it, if no lens avatar it will fallback to ens avatars
