### ISSUE TITLE
Self following

### ISSUE THREAD

**Issue by mahdi100r** [lensterxyz/lenster#1469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hey i am able to follow myself i think thats a bug and you should fix it. Thank you

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![Untitled](https://user-images.githubusercontent.com/30352722/209548498-ba954571-aa33-40ee-be9a-1a402c423679.png)

**Comment by bigint** [comment]
This is expected
