### ISSUE TITLE
Post URL Preview Error

### ISSUE THREAD

**Issue by DxNishan** [lensterxyz/lenster#1475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

So here is the issue. 

I have recently shared a website link in my lenster.xyz post ( https://lenster.xyz/posts/0x878e-0x12) .
After i posted that link, when i was checking my timeline posts, The other persons posts which are having Url are displaying my previous post website preview . Means The other person post's URL is showing the Preview of my URL, instead of actual URL preview.

Attached the snap here.I'll share more proof if required. 

<img width="531" alt="cc5" src="https://user-images.githubusercontent.com/98100787/209740206-08127cd5-2431-42d9-a689-526bae2953b3.PNG">

![image](https://user-images.githubusercontent.com/98100787/209740371-3b6120a3-8835-46ab-ac14-bbfed6ffa2e1.png)

### Expected Behavior

The Url Preview of the Other person's Post should display the actual preview of the URL .

### Steps To Reproduce

Post this Url https://beta.layer3.xyz/bounties/become-crypto-native .

Then comeback to timeline, scroll down till u find a other person post with URL . This other person's URL will show the Thumpnail (preview) of your posted URL's Preview instead of actual URL preview

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

<img width="531" alt="cc5" src="https://user-images.githubusercontent.com/98100787/209741861-865cb85c-2efc-433d-bdd7-72710088e1e5.PNG">
<img width="489" alt="cc2" src="https://user-images.githubusercontent.com/98100787/209741906-85638b9a-9687-4dfb-9ceb-0839602330e8.PNG">
<img width="463" alt="cc3" src="https://user-images.githubusercontent.com/98100787/209741939-35b2cd49-59b0-4654-96a4-51c07dd74085.PNG">

**Comment by bigint** [comment]
Thanks for raising this 🙏🏼 

should be fixed 🚀
