### ISSUE TITLE
Don't show user preview if it not exists

### ISSUE THREAD

**Issue by sasicodes** [lensterxyz/lenster#1481]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="415" alt="image" src="https://user-images.githubusercontent.com/29498872/209838914-99c1f5ac-d2eb-4372-8d9b-f97d65f092bf.png">

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
@sasicodes can you share the sample post link 🙇🏼

**Comment by sasicodes** [comment]
> @sasicodes can you share the sample post link 🙇🏼 

0x01a130-0x06

**Comment by harish-sethuraman** [comment]
I think this is likely a problem with rendering the mentions? @bigint can we check this in my lexical render branch? 🙈

**Comment by bigint** [comment]
@harish-sethuraman we already checked that on call, we still have some issue in the branch 🙈 

can we close that asap 🙏🏼, that will really improve the performance 🙇🏼

**Comment by sasicodes** [comment]
en placeholder image la oru ponnu varudhu 💭 😺

**Comment by harish-sethuraman** [comment]
Will look into it 🙈
