### ISSUE TITLE
"Something went wrong while uploading"

### ISSUE THREAD

**Issue by jMyles** [lensterxyz/lenster#1485]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While trying to upload a video, a small div appears with an error message, "Something went wrong while uploading".

### Expected Behavior

For the video to upload.

### Steps To Reproduce

It reliably occurs with the video I am trying to upload; not sure if there's something particular about this video that makes it reproducible?

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Firefox

### Anything else?

![Screenshot from 2022-12-29 17-43-10](https://user-images.githubusercontent.com/311973/210018265-8adee331-cd13-4797-a2c2-b368e7956785.png)
![Screenshot from 2022-12-29 17-43-22](https://user-images.githubusercontent.com/311973/210018267-0261434c-6817-477e-8109-54bb149ae187.png)

**Comment by foolo** [comment]
@jMyles I can't reproduce it. Maybe you can share the specific video?

**Comment by bigint** [comment]
Can't reproduce this 🙇🏼
