### ISSUE TITLE
Direct Messages with XMTP is not working

### ISSUE THREAD

**Issue by leiniercs** [lensterxyz/lenster#1492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Connect and sign
- Swith to DM section
- Appear a request to sign a XMTP Identity
- Sign the request
- The end. Everybody go to your houses, there is nothing more to see here.

### Expected Behavior

To detect and react to that and be able to send DM to other Lens users.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by foolo** [comment]
@leiniercs Can you post a screenshot of how it looks when nothing is displayed?
For me, it looks OK.

**Comment by bigint** [comment]
We can't reproduce this 🙇🏼
