### ISSUE TITLE
i can't sign in Lenster wed

### ISSUE THREAD

**Issue by mrtu7201** [lensterxyz/lenster#1493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by mrtu7201** [comment]
i can't sign in Lester wed

**Comment by mrtu7201** [comment]
<img width="800" alt="Screen Shot 2022-12-31 at 08 30 19" src="https://user-images.githubusercontent.com/116610553/210139589-eafbeeab-e199-47d7-b3a2-ce1403a98e04.png">

**Comment by bigint** [comment]
Fixed ✅
