### ISSUE TITLE
Not able to sign in

### ISSUE THREAD

**Issue by babydriver345** [lensterxyz/lenster#1494]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After connecting with wallet and trying to "Sign in with ethereum to lens", a popup is coming for a split second but login is not happening.
Tried with browser wallet and mobile wallet using wallet connect and same thing happened

### Expected Behavior

Sign in should have happened and user should see the wallet address at top right side instead of wallet icon showing as it is not connected yet

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Brave

**Comment by foolo** [comment]
I was able to reproduce this by trying to login with an Ethereum address that has no Lens account.
The popup window that shows for a fraction of a second is this:

![Screenshot_2022-12-31_19-37-10](https://user-images.githubusercontent.com/667227/210152840-21aeddd2-8bba-474c-afc6-8d9145f40b13.png)
(i had to do a screen recording to capture it :) )
@babydriver345 Could you check whether this is the case for you (that you are using an Ethereum address that has no Lens account)? The issue need to be solved in any case, of course, but it would be good to know if it's the same problem.
