### ISSUE TITLE
can't log in 

### ISSUE THREAD

**Issue by ZYRA-live** [lensterxyz/lenster#1498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I try to log in with metamask click sign but nothing happens

### Expected Behavior

be able to log in with metamask

### Steps To Reproduce

try to log in

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by foolo** [comment]
May be same as #1497
