### ISSUE TITLE
can not login even have signed successfully

### ISSUE THREAD

**Issue by jolish88** [lensterxyz/lenster#1500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I tried to login to my lens account, have already signed in my wallet and successed, but can not login to platform

### Expected Behavior

when signed wallet successfuly, it should be signed in the platform at the same time

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by foolo** [comment]
@jolish88 May be the same as #1497

**Comment by bigint** [comment]
sounds like @foolo 

thanks for the fix btw 🙇🏼
