### ISSUE TITLE
Expand the publication tap area 

### ISSUE THREAD

**Issue by desfero** [lensterxyz/lenster#1504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Right now you have to `click/tap` on the publication `content` box to be navigated to the full publication page (red box).

![image](https://user-images.githubusercontent.com/7031578/210243948-d2c1e6a4-81ef-4f13-bef4-b3f66abde5f7.png)

### Expected Behavior

Navigation should be triggered by tapping anywhere on the publication  (yellow box), except the places where we have a link (avatar, link in content, etc). 

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Agreed this is an annoying bug 🙇🏼 

will fix it asap 🚀
