### ISSUE TITLE
[Discussion] [Feature request] Default collect module

### ISSUE THREAD

**Issue by donosonaumczuk** [lensterxyz/lenster#151]
### Summary

Lot of people is missing the collect feature because of having revert collect module as default. I would personally choose to have free collect module as default, I don't see any disadvantage on that. 

Another option could be enforcing the user to choose a default module once posting for the first time. Or something similar.

I attach some examples, the second one was the saddest in my opinion :(

## Example 1
![image](https://user-images.githubusercontent.com/23125060/181363344-d23ac4c4-49b2-46df-8875-01c339082521.png)

## Example 2

![image](https://user-images.githubusercontent.com/23125060/181363889-f25d5157-243c-4afb-bad1-3d570be5df9c.png)
![image](https://user-images.githubusercontent.com/23125060/181363992-c086838f-e277-47da-9e61-f241324f73f3.png)

## Example 3
![image](https://user-images.githubusercontent.com/23125060/181363147-c62a798a-5f05-4de7-b17d-3d7fe609f7b2.png)

### What platform(s) does this occur on?

Web

**Comment by bigint** [comment]
@donosonaumczuk Now we are defaulted back to **Free Collect Module** 🚀
