### ISSUE TITLE
[Feature] Add support for 3rd party interactive content

### ISSUE THREAD

**Issue by tobowers** [lensterxyz/lenster#1512]
### Summary

Allow some markup (markdown?) in posts to embed 3rd party content (safely) using a secure iframe (without access to the parent page). This would allow the display of things like interactive NFTs (NFTs that use HTML as their image), or even full smaller "apps" embedded within posts.

I propose a syntax similar to this:

`<iframe src="https://blah.com" />` where the post is interpreted before display to take only the src, embed that in a standard sized, secure iframe.

Alternatively a specialized:
`<nft chainId=137 address=0xabc tokenId=123 />` specifically for embedding individual NFTs into a post.

**Comment by bigint** [comment]
We have a plans to support NFTs alone for now, iframe are very vulnerable 🙇🏼 

Closing this in favour of #1368

**Comment by tobowers** [comment]
I frames are only vulnerable if not done well... Even opensea supports full HTML based NFTs.
