### ISSUE TITLE
[Bug] Notification showing wrong mirrorer

### ISSUE THREAD

**Issue by donosonaumczuk** [lensterxyz/lenster#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The notifications show a mirror as if it was a self-mirror instead of showing the proper one.

### Expected Behavior

Showing the mirror notification displaying the actual account that mirrored.

### Steps To Reproduce

Not sure, this had happened in my post `0x08-0x3a`. Not sure if happens in other ones. But just checking the notifications after a mirror.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Firefox

### Anything else?

![image](https://user-images.githubusercontent.com/23125060/181477276-58ee36ed-9e0e-4857-9bb0-726cdce9bf63.png)

**Comment by bigint** [comment]
Thanks for the issue fren 🙏🏻 

This will be fixed in high priority 🚀

**Comment by 0xkeivin** [comment]
`NewMirrorNotification`  query doesn't seem to include data for the user mirroring the post. 

there is an API to list users that mirrored a post https://docs.lens.xyz/docs/get-profiles#get-by-who-has-mirrored-a-publication 
but it doesn't seem to be in order 🤔

**Comment by bigint** [comment]
@0xkeivin I thought this one is returning the mirrored user's profile! so no?

```graphql
{
  notifications(request: {
    profileId: "0x01"
  }) {
    items {
      ... on NewMirrorNotification {
        profile {
          id
        }
      }
    }
  }
}
```

**Comment by bigint** [comment]
Looping in @joshstevens19

Context: notification not returning the mirrored user profile 🙏🏼

**Comment by bigint** [comment]
Should be fixed 🚀
