### ISSUE TITLE
Trying to follow someone and gettin gthi 

### ISSUE THREAD

**Issue by jisharpmusic** [lensterxyz/lenster#1573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when i follow someone on lens it tells me this 
![Screenshot_20230108_022715](https://user-images.githubusercontent.com/69611515/211215005-425332fc-cac7-489f-ae3a-6c5b5239e527.png)

### Expected Behavior

Just follow them 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

### Anything else?

![Screenshot_20230108_022715](https://user-images.githubusercontent.com/69611515/211215072-710e8f15-c273-41e1-8119-f3b339e9b96a.png)

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
