### ISSUE TITLE
Profile.Feed.Scroll not working

### ISSUE THREAD

**Issue by hryhorii1** [lensterxyz/lenster#1618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i log into my profile and open the feed, I can see 2 of my posts only and I can not scroll down the page and see my other posts. Somehow scroll is not activated on the page. The same problem with different sections like media and NFTs scroll is not activated. Maybe the problem is with the touchpad but I have checked on other web pages the scroll is working the problem is on lenster.xyz

### Expected Behavior

It should be possible to scroll the content on the page in case there is the content that is not placed in the whole page

### Steps To Reproduce

Login > Sing in the wallet > Go to my profile > Open  Feed section or Media Section > Try to scroll > Observe the screen

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

<img width="1465" alt="sunrise777 (@sunrise777) • Lenster 2023-01-15 00-20-53" src="https://user-images.githubusercontent.com/37250271/212499670-331e3abd-edfa-4116-a4cf-a9220b684d3e.png">

**Comment by bigint** [comment]
Should be fixed 🙇🏼
