### ISSUE TITLE
Drag and drop media upload

### ISSUE THREAD

**Issue by suhailkakar** [lensterxyz/lenster#163]
### Summary

Currently Lenster doesn't support drag and drop upload for images and videos unlike other social media apps, i.e Twitter or Instagram. 

- I can work on this feature and open a pull request :)

Video for reference 

https://user-images.githubusercontent.com/56798748/181650353-c4f19b38-0f21-4736-8919-5d2861a7a6de.mov

**Comment by bigint** [comment]
That's great @suhailkakar I set `$10` bounty for this and assigned it to you 🙏🏻 

Try avoiding some third party dependencies 🙇🏻

**Comment by suhailkakar** [comment]
Hey @bigint 

Thanks you!

Maybe you can remove the bounty. I can work on this for free :)

Would love to contribute to lens community and open source ❤️

**Comment by bigint** [comment]
That's great @suhailkakar, excited to see your PR 🚀

**Comment by bigint** [comment]
@suhailkakar do you have plans to pick this? If not I'll set bounty again and publish it in Gitcoin 🙏🏼
