### ISSUE TITLE
Expected a value of type "ProxyActionId" but received: { reason: "REJECTED" }

### ISSUE THREAD

**Issue by angyts** [lensterxyz/lenster#1671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I received this message as an end user. I believe this happens when the relayer runs out of gas.

1) Perhaps there can be a more useful error message.
`The gas relay station is out of gas`.
`Please help to donate to the relay station`

2) Or it can fall back to,
`Would you like to proceed with the transaction by paying gas with $MATIC?`

3) Or just reject the transaction outright.

Instead of the current situation where the user will try and then fail, it provides a poor UX experience.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by roman-popenov** [comment]
How can I fund the relay?

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
