### ISSUE TITLE
follow request

### ISSUE THREAD

**Issue by maljaan32** [lensterxyz/lenster#1685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No one can follow me!
I've checked all the setting options but when users click on the follow bottom of my account, it says that 'The owner of this profile does not allow you to follow them'!

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![a](https://user-images.githubusercontent.com/102334689/214983280-3242714e-6abe-4496-9b00-db745c6ff677.JPG)

**Comment by DanIsNearby** [comment]
You can change to "anyone can follow" here https://lensfrens.xyz/
