### ISSUE TITLE
Publication draft lost if containing list items

### ISSUE THREAD

**Issue by foolo** [lensterxyz/lenster#1691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. On start page, write a draft with a list item (a line starting with a dash:  `- example`) without publishing 
2. Close the modal without publiishing
![Screenshot_2023-01-28_17-19-41](https://user-images.githubusercontent.com/667227/215277580-14e6ba7b-1226-43d6-b712-03d47c6d74fd.png)

3. Open the modal again

### Current Behavior

Modal is empty
Error message in console:

```
next-dev.js?36dd:20 Error: Create node: Attempted to create node ListItemNode that was not configured to be used on the editor.
    at errorOnTypeKlassMismatch (Lexical.dev.js?cb45:7415:1)
    at new LexicalNode (Lexical.dev.js?cb45:6705:1)
    at new ElementNode (Lexical.dev.js?cb45:7487:1)
    at new ListItemNode (LexicalList.dev.js?b341:615:1)
    at Object.$createListItemNode (LexicalList.dev.js?b341:1030:1)
    ...
```

### Expected Behavior

Should show the draft text from before (`- example`)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
is this still happening?

**Comment by foolo** [comment]
> is this still happening?

nope, i saw you closed it so you probably found that out too
