### ISSUE TITLE
Handle Link preview for link without (https)

### ISSUE THREAD

**Issue by sasicodes** [lensterxyz/lenster#1696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

No preview for link without https,

<img width="751" alt="image" src="https://user-images.githubusercontent.com/29498872/215423751-a859f7b8-441a-4f25-b4f1-c28d058ae2e4.png">

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by sasicodes** [comment]
Quick note: Sometimes its working 🤔 
<img width="836" alt="image" src="https://user-images.githubusercontent.com/29498872/215427685-600dfb22-a6ce-4a86-84ae-781b84dd4185.png">

**Comment by bigint** [comment]
Should be fixed 🙇
