### ISSUE TITLE
Different Reactions for post

### ISSUE THREAD

**Issue by bivesh0** [lensterxyz/lenster#1698]
### Summary

I just wonder if we could just describe our feelings through emojis for posts instead of comments or like only ,like Meta.

![Screenshot_2023-01-30-20-46-44-00_a23b203fd3aafc6dcb84e438dda678b6](https://user-images.githubusercontent.com/98143801/215517519-27d43a65-641f-4544-8d00-3e5c4a0c7c27.jpg)

**Comment by bigint** [comment]
This is an feature request for lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
