### ISSUE TITLE
Error on logout

### ISSUE THREAD

**Issue by foolo** [lensterxyz/lenster#1703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

Login to https://lenster.xyz/
Logout again

### Current Behavior

Page error
![Screenshot_2023-02-01_10-25-03](https://user-images.githubusercontent.com/667227/216003249-394803ab-82c2-4e40-86a2-236283d7eaeb.png)

### Expected Behavior

Should show home page

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

The crashing code line, from devmode:
![Screenshot_2023-02-01_10-18-22](https://user-images.githubusercontent.com/667227/216001936-477d9c2b-90c7-4b7e-b4ad-7bd1ce3077a5.png)

**Comment by bigint** [comment]
Yea thanks for raising, i saw this sometimes 🙇🏼

**Comment by foolo** [comment]
Some investigation:
Problem happens when publication.__typename is "Comment", but publication.commentOn is null,
this happens only for certain posts, (but when reloading the page, or opening the post, the same post is loaded successfully, with publication.commentOn defined)
See https://github.com/foolo/lenster/blob/error-on-logout-1703/apps/web/src/components/Explore/Feed.tsx#L68

**Comment by bigint** [comment]
Can be fixed with optional chaining i guess? no?

**Comment by foolo** [comment]
> @bigint Can be fixed with optional chaining i guess? no?

Not sure. The problem is that in these cases, we have the data for the comment, but not for the original post, and I guess it would be weird to just show a comment without the post on which it was made.

The `.commentOn` field is used to render the original post above the comment:
![Screenshot_2023-02-06_14-53-50](https://user-images.githubusercontent.com/667227/216990213-600561a8-d54d-484f-88a3-adfa9afce925.png)

When this error happens, `commentOn` is undefined, i.e. we don't have the data for rendering the original post.

**Suggested solution:**
I guess the easiest solution is just to hide the whole publication (post+comment), since this only happens for some posts, and only after a logout anyway.

**Comment by bigint** [comment]
I guess its no longer happening 🤔

**Comment by foolo** [comment]
> I guess its no longer happening thinking

I haven't seen it for a while. I'll close the issue! Can always open it if it happens again.
