### ISSUE TITLE
Server crash on startup in dev mode

### ISSUE THREAD

**Issue by foolo** [lensterxyz/lenster#1718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Server crashes with error:
![Screenshot_2023-02-02_12-36-41](https://user-images.githubusercontent.com/667227/216314985-ea11a269-132e-455c-a100-c89d238a059c.png)

### Expected Behavior

Server should start

### Steps To Reproduce

On main branch, start server with `yarn install` and `yarn dev`

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

Some investigation shows that the crash started happening on commit 387e5270c0ad28287912bb816069021fbe4d7457

**Comment by bigint** [comment]
This is happening because of wagmi, I reverted the upgrade, it should work now 🙇🏼 @foolo

**Comment by bigint** [comment]
I'll find a fix for this

**Comment by foolo** [comment]
Now it occurs randomly once every few minutes when I run the the server.
I can make it work by restarting the server a few times. (cancelling the process and running `yarn dev` again)

**Comment by foolo** [comment]
Fixed by #1726
