### ISSUE TITLE
execution reverted problem.

### ISSUE THREAD

**Issue by force22** [lensterxyz/lenster#1722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- when I am tryiny to mirror a post it is showing execution reverted problem.

### Expected Behavior

It must smoothly mirrored any post on lenster ,,, I assume.

### Steps To Reproduce

Please notice it.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

Lenster works really fine except it.

**Comment by bigint** [comment]
I can't reproduce this, send us a small screencast of this 🙏
