### ISSUE TITLE
Mirrors are labeled as Comments

### ISSUE THREAD

**Issue by emptybrother7** [lensterxyz/lenster#1734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Here is picture:

![image](https://user-images.githubusercontent.com/54287547/216828771-6f288256-7651-46eb-84f8-01dec60d9a9f.png)

### Expected Behavior

Expect to be labeled mirror but is being labeled as a comment in the notifications 

### Steps To Reproduce

someone mirrors your post

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Edge

**Comment by foolo** [comment]
Error introduced here:
https://github.com/lensterxyz/lenster/commit/71dfc68505573a4cc48b93fe0d33c36a7361fa5d#diff-ad9617ea2e755023ea4fffa277a1bc9a72b1d26641330aa7c7ad441f3e32879b
I'll fix it
