### ISSUE TITLE
Manually typed empty lines removed in published post

### ISSUE THREAD

**Issue by foolo** [lensterxyz/lenster#1739]
### Notes
Follow-up from https://github.com/lensterxyz/lenster/commit/3853c2ca9c9aa2715388bb3d7d490fe67bd1f3ab
and https://github.com/lensterxyz/lenster/issues/1193

### Steps To Reproduce

Publish a publication containing an empty line.
Important: Type the text **manually**. (If the text is pasted instead, paragraphs are preserved, and the published text will look OK.)
Example:
![Screenshot_2023-02-06_08-32-37](https://user-images.githubusercontent.com/667227/216912149-1fef1255-bb49-4515-b64e-5e2bf38b1e66.png)

### Current Behavior

The empty line disappears in the published post:
![Screenshot_2023-02-06_08-33-07](https://user-images.githubusercontent.com/667227/216912167-e527b871-c3bd-48b7-b5c4-64eb96c04bcd.png)

### Expected Behavior

The publication should include the empty line

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by foolo** [comment]
@bigint Proposed temporary solution for now:
On publishing, convert paragraphs to newlines (instead of just replacing double-newline with single-newline, as it does now). See proposed solution:
https://github.com/foolo/lenster/commit/d65a3fc23d6aaf88c40042a0f9154eb60d5d1062

(Suggested long-term solution to be implemented later: Do full markdown decoding when rendering, using some well-tested library. Then we can remove all hacks on the publish-side, although something similar to #1619 will need to be done to fix Tailwind's styling of paragraphs)

**Comment by foolo** [comment]
Update:
Now it seems to work for manually typed text, but instead, *pasted* text changes:

In editor:
![Screenshot_2023-03-03_10-08-54](https://user-images.githubusercontent.com/667227/222679681-20617699-b181-4d95-9b4e-02b162d72494.png)

Rendered result:
![Screenshot_2023-03-03_10-11-04](https://user-images.githubusercontent.com/667227/222679774-d0538a6a-ddc9-4981-890b-de178298b87e.png)

**Comment by bigint** [comment]
Yea we moved to react-markdown from interweave we no more have rendering problems it's all with lexical 🙈

**Comment by bigint** [comment]
If we move to slate js i'll be very happy, I'm going to set 500$ bounty for it

**Comment by foolo** [comment]
> Yea we moved to react-markdown from interweave we no more have rendering problems it's all with lexical 

@bigint There's a new problem now however :)
Look at the screenshots in https://github.com/lensterxyz/lenster/issues/1739#issuecomment-1453209048

**Comment by bigint** [comment]
Should be fixed
