### ISSUE TITLE
Do not send notifications about your own actions

### ISSUE THREAD

**Issue by ustas-eth** [lensterxyz/lenster#1740]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

You will be notified if you like or comment on your own post.
https://lenster.xyz/posts/0x8218-0x1e
![image](https://user-images.githubusercontent.com/82833595/216925696-593dcd4b-02c8-477f-8e48-3bf73a85f80a.png)

### Expected Behavior

Such notifications are redundant.

### Steps To Reproduce

Like or comment on your own post.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Firefox

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
