### ISSUE TITLE
Can't Activate Cross Posting to Twitter

### ISSUE THREAD

**Issue by Amory5727** [lensterxyz/lenster#1744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to activate cross posting to twitter I get a 500 server error.

### Expected Behavior

I expect to either not get an error when I activate cross posting to twitter or at least a better error message indicating what is wrong.

### Steps To Reproduce

1. Login to lenster.xyz
2. Click your profile image on the top right
3. Select Settings from the menu on the right
4. Select Account from the menu on the left
5. At the bottom of the page click Setup now under Cross post to Twitter
6. Click Let's do this
7. Click Authorize App (I'm logged in as amory5727 on twitter)
8. Login with lens
9. Select a Lens profile to mirror (amory5727.lens for me)
10. Click Start reflecting posts
11. Receive 500 server error. See screenshot and console log below:

<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/101778238/217050349-f013e03f-0ee6-48e8-96ee-282577baf194.png">

```
app.js:2          POST https://reflect.withlens.app/profiles 500
(anonymous) @ app.js:2
e.exports @ app.js:2
e.exports @ app.js:2
c.request @ app.js:2
(anonymous) @ app.js:2
r.visit @ app.js:2
r.post @ app.js:2
onClick @ 871.js?id=f396bc82820c3a1d:1
Ie @ app.js:2
ze @ app.js:2
(anonymous) @ app.js:2
Fn @ app.js:2
Bn @ app.js:2
(anonymous) @ app.js:2
lu @ app.js:2
Me @ app.js:2
Wn @ app.js:2
Qt @ app.js:2
Ht @ app.js:2
```

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

I've had this issue for at least 2 months, but probably longer than that.

**Comment by bigint** [comment]
Crossposting is deprecated in Lenster
