### ISSUE TITLE
NFT's As profile avathar

### ISSUE THREAD

**Issue by Deosaju** [lensterxyz/lenster#1746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we use non image type NFT's ( Like unstop domains):

It gives a unpleasant error message !

ERROR Download image - message: Not valid mime type - image/svg+xml; charset=utf-8, tried downloading - https://metadata.unstoppabledomains.com/image-src/324#@$.hi.svg

### Expected Behavior

If no Image is found so it should specify to select what kind of NFT's are they looking for Or Should give some nice Error toast message.

### Steps To Reproduce

Use Unstop domains as NFT avatar,

That's it 

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Brave

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
