### ISSUE TITLE
Notification dot is still there even after opening notifications

### ISSUE THREAD

**Issue by star1100** [lensterxyz/lenster#1753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a new fan is added or an article is liked and bookmarked, there will be a small red dot on the thunderbolt logo in the upper right corner. However, after the user has checked the reminder, a small red dot reminder will still appear when logging in again, causing the user to think that there is a new dynamic change.

### Expected Behavior

After the user has viewed this reminder, when he logs in again and there are no new followers or likes, the red dot reminder does not appear again.

### Steps To Reproduce

<path stroke-linecap="round" stroke-linejoin="round" d="M13 10V3L4 14h7v7l9-11h-7z"></path>

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Others

### Anything else?

![微信图片_20230208150128](https://user-images.githubusercontent.com/54355387/217457784-8666dd9b-7a0f-4372-aec9-cb3fffe09a8f.png)

**Comment by star1100** [comment]
Using Google Chrome

**Comment by bigint** [comment]
Fixed it 🚀
