### ISSUE TITLE
Posting Error 

### ISSUE THREAD

**Issue by ScalperhuBhai** [lensterxyz/lenster#1757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![lenster bug](https://user-images.githubusercontent.com/107799534/217547902-1be72d90-154f-4715-a982-c35f5d93bf76.PNG)

After doing  a regular transaction for about 50-60 posts one by one it gave me an error i am attaching the photo, Also it started asking to approve transaction while having the error , thanks

### Steps To Reproduce

![lenster bug](https://user-images.githubusercontent.com/107799534/217548317-88d0459b-4c9d-470d-a7f2-349b07613c30.PNG)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Edge

### Anything else?

![lenster bug](https://user-images.githubusercontent.com/107799534/217548284-d5e7f9b6-365e-4fbc-84d6-366b5607e73f.PNG)

**Comment by ScalperhuBhai** [comment]
Am also getting charged for posting why is that ?? 
![getting charged for posting ](https://user-images.githubusercontent.com/107799534/217554234-96aff691-9e49-4d63-a0d1-d1130e002495.PNG)

**Comment by bigint** [comment]
Have you enabled dispatcher in settings?

**Comment by bigint** [comment]
If so you might be rate limited, please try again later 🙇🏼 

Technically its working as expected aka if dispatcher fails we fallback to sign + gas

so closing this 🙇🏼
