### ISSUE TITLE
Post Not updated

### ISSUE THREAD

**Issue by Vishnuvikas888** [lensterxyz/lenster#1779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have posted a post in lenster and sign the gasless transaction. Later when icheck my post i can't able to find it. 

### Expected Behavior

Post should be available on my profile.

### Steps To Reproduce

Create a post and sign the transaction

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

None

**Comment by bigint** [comment]
Send the link to your post and profile

**Comment by Vishnuvikas888** [comment]
After few hours the post is posted, It is slow, You can close this issue.
