### ISSUE TITLE
404 - This page could not be found.

### ISSUE THREAD

**Issue by Vladexysys88** [lensterxyz/lenster#1781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After installing the dependencies, running the project in developer mode, in the browser, a white screen with an inscription in the center, compiled client and server successfully in 295 ms (150 modules)
"404 - This page could not be found."

### Steps To Reproduce

1. git clone lenster
2. yarn install
3. yarn dev
4. Open localhost in browser

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome, Firefox

### Anything else?

**Screen**
![image](https://user-images.githubusercontent.com/29161130/218147280-bfdbe59e-36ca-45e3-bdc1-16689f8e77ac.png)

**I am using**
Os: Windows 10
Node: 18.12.1

**Comment by bigint** [comment]
Try in port 4783

**Comment by Vladexysys88** [comment]
> Member

Not work
