### ISSUE TITLE
Experiencing problem with following accounts

### ISSUE THREAD

**Issue by xiaomi202104** [lensterxyz/lenster#1783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i try to "follow" any account now, i got this error message "Expected a value of type "ProxyActionId" but received: { reason: "REJECTED" }"
<img width="611" alt="截屏2023-02-11 21 39 43" src="https://user-images.githubusercontent.com/118245352/218261132-514cd6da-fbb2-4733-b3c4-12b7aa28b801.png">

### Expected Behavior

to be able to follow without an issue

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
