### ISSUE TITLE
Who to follow widget

### ISSUE THREAD

**Issue by DanIsNearby** [lensterxyz/lenster#1786]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 I have displayed people who i already follow 
![image](https://user-images.githubusercontent.com/91475837/218306110-d6061300-468f-488b-ba2c-90c443ce03ab.png)
![image](https://user-images.githubusercontent.com/91475837/218306116-26bd76d6-19f4-4fd5-936c-c5a4c45e2300.png)

### Expected Behavior

Displaying new people that could be interesting for me to check out 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by Irina198015** [comment]
Good

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
