### ISSUE TITLE
Unable to login with my lens profile

### ISSUE THREAD

**Issue by louisliuhk666** [lensterxyz/lenster#1787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I bought a len profile from opensea: chuckles.len,
but I cant login with it, and system shows: 
Claim your Lens profile 🌿
Visit [claiming site](https://claim.lens.xyz/) to claim your profile now 🏃‍♂️
Make sure to check back here when done!

### Expected Behavior

shoud able to login?

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Edge

### Anything else?

![lens](https://user-images.githubusercontent.com/124461620/218334088-67f84479-5c14-4350-a2f1-ff1745a4a6a3.png)

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
