### ISSUE TITLE
Following status  uncorrect

### ISSUE THREAD

**Issue by Fengzi429** [lensterxyz/lenster#1792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

following account, but https://guild.xyz/ tips i am not following, and back to lenster， the  status is following , when i unfollow, got an error , i am not following

### Expected Behavior

following status correct

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![截屏2023-02-13 14 49 42](https://user-images.githubusercontent.com/7960254/218390179-3b937a1c-2723-468a-9069-e2d4b75d1498.png)
![截屏2023-02-13 14 50 06](https://user-images.githubusercontent.com/7960254/218390186-265df004-6546-402b-b8c6-635b2751b3f3.png)
![截屏2023-02-13 14 50 22](https://user-images.githubusercontent.com/7960254/218390194-87a2e6e2-3772-4794-b63c-05b1204416a0.png)

**Comment by hzwong** [comment]
I have the same problem

**Comment by Fengzi429** [comment]
@bigint help me to check this ,now i can't unlock roles, thanks
![image](https://user-images.githubusercontent.com/7960254/218471042-9a8a95ff-67eb-481b-8d85-ade0c377eedb.png)

**Comment by Sunny1414** [comment]
This is exactly my issues
