### ISSUE TITLE
i could not unfollow an account

### ISSUE THREAD

**Issue by Tdee16** [lensterxyz/lenster#1799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i followed dumpling lens to collect the post but post couldnt be collected because of this respons " you have to be a follower to collect". Meanwhile dashboard shows i am following.

Then, when i decided to unfollow in order to re-follow, the process couldnt be completed. 

i logged out and back a couple of times but the situation persisted.

### Expected Behavior

i expect my account to unfollow dumpling's account when i unfollowed.

### Steps To Reproduce

none

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
