### ISSUE TITLE
I tried to unfollow Christina but it show the sign" You are not following this account" even I'm following her.

### ISSUE THREAD

**Issue by ITTY8** [lensterxyz/lenster#1803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I CANT DO ANYTHINGS ABOUT FOLLOW OR UNFOLLOW CHIRSTINA

### Expected Behavior

CAN FOLLOW ON UNFOLLOW

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

<img width="1680" alt="ภาพถ่ายหน้าจอ 2566-02-15 เวลา 03 29 17" src="https://user-images.githubusercontent.com/107593770/218855108-81fd60e3-1e06-420e-903e-17b2e523197d.png">

**Comment by GordonDr** [comment]
It seems to me that the chain is overloaded by lens transactions. This could be an issue

**Comment by Sunny1414** [comment]
What's the solution to this?

**Comment by yuansaki** [comment]
same here

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
