### ISSUE TITLE
follow lens @lensprotocol bug ?

### ISSUE THREAD

**Issue by leesendtou** [lensterxyz/lenster#1805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

have followed @lensprotocol but can not collect ,and mind me need followed @lensprotocol then there is a bug?
![2023-02-15_122521](https://user-images.githubusercontent.com/36722319/218930521-c8fcc1d8-6a26-4972-981d-916e20744667.png)
![2023-02-15_122521](https://user-images.githubusercontent.com/36722319/218930598-dae83406-ae94-4f78-bb7d-a037281fa4b5.png)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
