### ISSUE TITLE
Expected a value of type "ProxyActionId" but received: { reason: "REJECTED" }

### ISSUE THREAD

**Issue by TheMariniere** [lensterxyz/lenster#1808]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Expected a value of type "ProxyActionId" but received: { reason: "REJECTED" }

### Expected Behavior

Transactions not going through instead getting the above error

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by T1tanik** [comment]
I faced the same problem please help me to solve it

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
