### ISSUE TITLE
Message Box

### ISSUE THREAD

**Issue by Ferhatyilmaz0** [lensterxyz/lenster#1813]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Yesterday i was sending message but when you send the message you need to refresh the page after that you can see your message also you need to refresh too when other people send a message to you.

### Expected Behavior

I am expecting the after we send the message no need to refresh.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

https://user-images.githubusercontent.com/63142007/219297612-6d2244ef-e882-4067-9f16-bf03d44fbc55.mp4

Uploading bandicam 2023-02-16 10-29-47-117.mp4…

**Comment by bigint** [comment]
It's issue with XMTP API and not with lenster
