### ISSUE TITLE
Cannot update profile nor post anything

### ISSUE THREAD

**Issue by GordonDr** [lensterxyz/lenster#1817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't post anything the whole day... When is it going to change?

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
