### ISSUE TITLE
Contact bug

### ISSUE THREAD

**Issue by JuanL0pes** [lensterxyz/lenster#1820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Frens I tried to give a feedback through “Contact” on menu and when I sent my message a box with a message (“url not found”) appeared. I don’t know if my feedback was sent, should be nice to “contact” function be up not just for feedbacks but to others possibilities too.

### Expected Behavior

Would be nice a status message appeared, something like “your message has been sent, we will reach you out in some days” or “your message wasn’t delivered, try it again or contact support”.

### Steps To Reproduce

Click on menu on your profile picture, select “contact” and try to send a message.

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Others

### Anything else?

I was using it on Zerion mobile Wallet.

**Comment by bigint** [comment]
Fixed
