### ISSUE TITLE
Bug on collecting 

### ISSUE THREAD

**Issue by izkillaz** [lensterxyz/lenster#1821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot collect , required adding up profile, needs confirmation from the host. 

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Chrome, Others

**Comment by izkillaz** [comment]
Should have auto confirmation so that drops can be claimed.

**Comment by izkillaz** [comment]
https://ufo.mirror.xyz/jcZOHueEFPMtRH6kbOo63nMzS9aG6-ygzD0hco2nLts

**Comment by izkillaz** [comment]
Pls update

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
