### ISSUE TITLE
cant follow(cant unfollow)

### ISSUE THREAD

**Issue by yuansaki** [lensterxyz/lenster#1825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i cant unfollow someone.
in fact i followed someone but still cant comment his post(i followed him several days ago).today i try unfollow + follow to refresh and when i click unfollow UI tell me "You are not following this profile"

what i tried:
①go to settings click 4 cleanup botton.
②clear brower's cookie

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
