### ISSUE TITLE
I'm having hard time following people back

### ISSUE THREAD

**Issue by Mhizlisa** [lensterxyz/lenster#1830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm having hard time following people back on Lenster and I noticed even when I eventually follow them it doesn't reflect 

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Others

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
