### ISSUE TITLE
can not update profile

### ISSUE THREAD

**Issue by Call-Me-Uncle** [lensterxyz/lenster#1834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

setting -> profile -> change profile ->click  save button -> alert update success
refresh page,  profile not changed

### Expected Behavior

setting -> profile -> change profile ->click  save button -> alert update success
refresh page,  profile changed

### Steps To Reproduce

setting -> profile -> change profile ->click  save button -> alert update success
refresh page

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![image](https://user-images.githubusercontent.com/8119899/220035635-da713459-e5d3-446e-a756-27ed8f6ceb79.png)
![image](https://user-images.githubusercontent.com/8119899/220035724-414750b3-7dd5-4b97-84f9-8a7bb99b9b87.png)

**Comment by bigint** [comment]
Should be fixed 🚀
