### ISSUE TITLE
Unfollow button is not working

### ISSUE THREAD

**Issue by DxNishan** [lensterxyz/lenster#1839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unfollow is not working for few of the profile. 
When i click on the profile it says " You are not following the profile"
attached the snap. i could see the unfollow button is still showing even after clicking it. Also the **following** could also not changing

![image](https://user-images.githubusercontent.com/98100787/220111666-d536f209-b6c7-49c8-9d43-534de7939765.png)

### Expected Behavior

When we click the unfollow button, it should unfollow the profile. 

### Steps To Reproduce

Since this issue is occurring on random profiles, Please unfollow 5, 10 profiles. 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

Please reach me on sahayanishan.lens just incase you need further details about the bug :) . always ready for the cooperation :) 👍

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
