### ISSUE TITLE
 I can’t find the post after sending it/Updating personal information cannot be saved

### ISSUE THREAD

**Issue by zhu00004** [lensterxyz/lenster#1842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1）Create a new post and I can’t find the post after sending it. Before that, the account has sent 30 posts, but this problem has been going on for 2 weeks. Please help to solve it. Thank you
2）Updating personal information cannot be saved. After clicking save, the system prompts that the save is successful, but after refreshing, it is still the old information

### Expected Behavior

Please help me solve this problem as soon as possible, this account is very important to me, thank you

### Steps To Reproduce

1）Create a new post and I can’t find the post after sending it. Before that, the account has sent 30 posts, but this problem has been going on for 2 weeks. Please help to solve it. Thank you
2）Updating personal information cannot be saved. After clicking save, the system prompts that the save is successful, but after refreshing, it is still the old information

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
It was an intermittent issue, it should be solved 🙇🏼

**Comment by zhu00004** [comment]
> It was an intermittent issue, it should be solved 🙇🏼

It's a pity that this problem has not been resolved. I will verify it every few days, but the result is not satisfactory
