### ISSUE TITLE
Status setting bar not getting auto-closed

### ISSUE THREAD

**Issue by anseljohn12** [lensterxyz/lenster#1844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In lenster application, after setting the personalised status message by clicking the drop down option "set status" - the status window is not getting auto-closed even after the successfully updated. We are getting a status message saying the status is updated, however the dialog box is not getting auto-closed which makes the user to manually navigate to the cross button and click them to close the window.
<img width="1385" alt="Screenshot 2023-02-21 at 11 55 44 PM" src="https://user-images.githubusercontent.com/53964399/220429520-320486b5-d7f1-4938-b04d-908bdbe0f06e.png">

### Expected Behavior

The dialog/status box should auto-close once the action is success. If the action is not success, the dialog/status box can be open for the users to further make changes or retry the saving option.

### Steps To Reproduce

Step 1: Login to Lenster
Step 2: Navigate to the top right corner, click on the display picture
Step 3: Select the option "Set status" from the drop down (will open a dialog box)
Step 4: Update the required status in the box and click on "Save"

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

<img width="1385" alt="Screenshot 2023-02-21 at 11 55 44 PM" src="https://user-images.githubusercontent.com/53964399/220430147-20fdf491-a929-4c26-b6f4-5d320be4ad1e.png">

**Comment by bigint** [comment]
Closes T-6926

**Comment by bigint** [comment]
Fixed

**Comment by anseljohn12** [comment]
Wow.. Amazing.

Have tested again and can confirm that the issue is fixed.

Thank you for the prompt action.
