### ISSUE TITLE
notification issue on lenster 

### ISSUE THREAD

**Issue by ChintanV2** [lensterxyz/lenster#1864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

there's issue related to not getting any notifications from people who's following me, I'm not sure if it's limited to only follow notifications.

### Expected Behavior

it needs to be fixed as there's no knowing of who's following me and i have to search them in my follow list

### Steps To Reproduce

N/a

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

### Anything else?

N/a

**Comment by bigint** [comment]
This is issue on lens api and not on lenster UI 🙇🏼
