### ISSUE TITLE
About screen brightness

### ISSUE THREAD

**Issue by TIGGERLAND** [lensterxyz/lenster#1865]
### Summary

In dark mode I can't see the text, and in light mode it is too bright and tires my eyes.
I would like to set the screen brightness just in between.

**Comment by bigint** [comment]
Can you please attach screenshots 🙏🏼

**Comment by TIGGERLAND** [comment]
![2023-03-01_04h34_58](https://user-images.githubusercontent.com/99783550/221959954-95578246-eaf0-42cf-83b9-1013c196889e.png)
![2023-03-01_04h35_06](https://user-images.githubusercontent.com/99783550/221959976-2c7bf339-5898-4552-be17-cd00c5fc4c02.png)
It will look like this picture

**Comment by bigint** [comment]
We will fix this during revamp happening soon 🙏
