### ISSUE TITLE
Improve the Lenster emoji auto recognize

### ISSUE THREAD

**Issue by aligh98** [lensterxyz/lenster#1871]
### Summary

When we try to type an emoji in the text boxes, the Lenster will understand and convert it into an emoji🌞.
In my opinion, it is better that when the user hits the Back-Space button, that image emoji is removed and also that the phrase we typed ( for example  :(   ) is displayed in the text. Many Twitter users interact with text emojis more than image emojis :)
![image](https://user-images.githubusercontent.com/10244953/221629031-538c98c2-c101-4ab0-82ec-679019d8d3d1.png)

**Comment by bigint** [comment]
It's already supported 🙇 

https://user-images.githubusercontent.com/69431456/226121900-591e1074-f55a-4e68-a1a4-457a30b6129b.mov
