### ISSUE TITLE
Comments are missing and can not be searched

### ISSUE THREAD

**Issue by jolish88** [lensterxyz/lenster#1902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I comments some post, I found that my comments are all missing, can not appear on the comments place of the post.

And I wanna search some content about my post, I found I can not get the search result when I typed my handle or profile name

My profile is @78278

Can you help me check what the problem is?

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by jolish88** [comment]
I also found sometimes I can see my comments, but others can not see that

**Comment by jolish88** [comment]
I didn't post any illegal information or spam messages, so please help to check, thank you so much

**Comment by bigint** [comment]
Can you share the link to the post you commented so we can investigate easily

**Comment by jolish88** [comment]
https://lenster.xyz/posts/0x5881-0x0548  This is the post

https://lenster.xyz/posts/0x015722-0x027d  This is the comment

**Comment by jolish88** [comment]
Hi sir, has this problem been solved?

**Comment by jolish88** [comment]
Today when I wanna make a comment, it shows this:
Transaction failed!
Cannot read properties of undefined (reading 'toHexString')

And today's first mirror evoked my wallet to pay the gas, I think there must be some limition for my account, please help to check

**Comment by jolish88** [comment]
Transaction failed!
Internal JSON-RPC error.  

Wen comments will show this, my profile can not comment any time, have tried several days

**Comment by bigint** [comment]
I'm working on fixing this!! You will not see `toHexString` errors anywhere 🙇🏼

**Comment by bigint** [comment]
still transaction fail?

**Comment by jolish88** [comment]
No, everything is fine right now! Thank you so much!

**Comment by jolish88** [comment]
Really happy to see my profile comes back, haha, thank you sir! Very appreciate your help! Lens LFG

**Comment by jolish88** [comment]
Really happy to see my profile comes back, haha, thank you sir! Very appreciate your help! Lens LFG

**Comment by bigint** [comment]
Glad to hear it 👯
