### ISSUE TITLE
Can't log in - existing Lens profile not recognised

### ISSUE THREAD

**Issue by aspiers** [lensterxyz/lenster#1928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to log in, but after signing the login message with MetaMask, I see:

![image](https://user-images.githubusercontent.com/100738/224411116-c80656e1-0160-4654-b7cc-df1af5ccee6a.png)

However I already claimed my Lens profile quite a while ago, and when I follow the link to https://claim.lens.xyz/, it confirms that I already have a profile.

### Expected Behavior

My Lens profile should be recognised and I can log in successfully.

### Steps To Reproduce

1. Go to https://lenster.xyz/
2. Click Login button
3. Click "Sign-In with Lens"
4. Sign the message in MetaMask

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Drop your handle or wallet address here so it will be easy for me to debug

**Comment by aspiers** [comment]
aspiers.eth

**Comment by bigint** [comment]
Checking this 🙇🏼

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues

I reported already will be fixed soon 🙇

**Comment by aspiers** [comment]
@bigint Thanks but I'm a bit confused - you are saying you reported but I still need to report it myself as well?  Please can you share where you reported it?
