### ISSUE TITLE
GIFs not showing

### ISSUE THREAD

**Issue by iPaulPro** [lensterxyz/lenster#1937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Create a post with a GIF and it does not display. Eg https://lenster.xyz/posts/0xd8-0x42

### Expected Behavior

It displays

### Steps To Reproduce

Create a post with a GIF

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome, Firefox, Brave, Safari

### Anything else?

The GIFs are shown properly on all other apps. When you click on the missing image to see the image larger that actually works.

![Screen Shot 2023-03-11 at 5 35 24 AM](https://user-images.githubusercontent.com/354227/224479515-f21a860e-5f30-4960-b8fb-ec33c89deda6.jpg)

**Comment by bigint** [comment]
It's problem with our provider, will be fixed in couple weeks 🙇
