### ISSUE TITLE
Profile Following bug

### ISSUE THREAD

**Issue by sleek4** [lensterxyz/lenster#1946]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I followed Phaver app on lens
So tried to verify myself on their guild
An error occurred, that I don't follow Phaver

### Expected Behavior

I expected to be verified that I'm a follower of Phaver app

### Steps To Reproduce

I don't have idea

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Others

### Anything else?

![Screenshot_20230313-101617_Mises](https://user-images.githubusercontent.com/78409412/224841146-552b2bd0-2d30-4b25-8b97-e57b00bf282f.jpg)
![Screenshot_20230313-101627_Mises](https://user-images.githubusercontent.com/78409412/224841154-f583541b-cd5a-4592-9ec8-f807c19a28fb.jpg)

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
