### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by hwz0909** [lensterxyz/lenster#1979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Every time I want to follow someone, he will show a "Usage limit exceeded, please try again later" prompt, and then ask me to sign and pay GAS.

### Expected Behavior

Wanna solve it

### Steps To Reproduce

Usage limit exceeded, please try again late

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

No

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
