### ISSUE TITLE
[Feature request] search function for users/communities

### ISSUE THREAD

**Issue by 0xkeivin** [lensterxyz/lenster#202]
### Summary

What: 
- A search bar where users can search for users and groups

Existing:
- there is already a lazy search feature for users which can be reused

**Comment by bigint** [comment]
But communities are built on top of publications model 🤔 

I'm not sure how much the search API will be helpful 🙇🏼

**Comment by 0xkeivin** [comment]
noted. the idea is to allow smaller communities to be discovered more easily 🤔  
let me check around if there's a better way

**Comment by bigint** [comment]
We deprecated communities, so closing this 🙏🏼
