### ISSUE TITLE
重复显示我的推文

### ISSUE THREAD

**Issue by SYYDSN** [lensterxyz/lenster#2072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

网页进入一次，推文就重新在后面叠加显示一次，导致发帖一次会显示很多次

### Expected Behavior

应该就显示一次

### Steps To Reproduce

访问我的feed,然后浏览其他内容，再回到我的feed。会重复显示

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![uTools_1679146745283](https://user-images.githubusercontent.com/15910900/226109873-e1e259ad-5ef4-4256-bfda-651ab7386526.png)

**Comment by bigint** [comment]
Please post on English 🙇
