### ISSUE TITLE
Allow only 1 audio or 1 video or 4 images

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#2081]

**Comment by Seroxdesign** [comment]
@bigint I'd like to be assigned this bounty, I have a couple questions though:

1. This applies to posts, so when a user wants to post something to their feed we only allow them to choose 1 audio, 1 video, or 4 images, is this correct?

2. If a user chooses 1 audio, can they also add 1 video to the same post (same for images), or are we restricting them to only 1 type of content per post?

**Comment by bigint** [comment]
@Seroxdesign 

> This applies to posts, so when a user wants to post something to their feed we only allow them to choose 1 audio, 1 video, or 4 images, is this correct?

Yes exactly

> If a user chooses 1 audio, can they also add 1 video to the same post (same for images)

No if they choose 1 audio they can't choose video or images

> are we restricting them to only 1 type of content per post

yes for videos and audios, but for images (including gif) we accept 4 at a time
