### ISSUE TITLE
Fix nextjs 13.2.5 build problem

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#2084]

**Comment by THEREALMON** [comment]
gm can you tell more details about nextjs 13.2.5 build problem

**Comment by bigint** [comment]
@THEREALMON just bump the version and run yarn build 🙇

**Comment by THEREALMON** [comment]
sure I'll help

**Comment by bigint** [comment]
no one picked this! fell free to pick this @THEREALMON

**Comment by bigint** [comment]
@THEREALMON got any change to find the issue 🙇 ?

**Comment by THEREALMON** [comment]
sorry sir my account was compromised just clearing thing and get back on this.. they taken my lens acct. too 😭

**Comment by bigint** [comment]
It's issue with `@lingui/swc-plugin` https://github.com/lingui/swc-plugin/issues/39

**Comment by bigint** [comment]
Fixed
