### ISSUE TITLE
Showing Wrong Like Count for Comment

### ISSUE THREAD

**Issue by vishnu1258** [lensterxyz/lenster#2093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I post a comment on any post, Immediately  after listing it's showing wrong likes count for comments, If I refresh the page  then it's showing correct like count.

**Before Refresh:**
![Lens bug](https://user-images.githubusercontent.com/22417498/226156347-71d01fc6-4978-4da8-9e16-caebcf9f9d17.jpg)

**After Refresh:**

![Lens bug1](https://user-images.githubusercontent.com/22417498/226156385-298c8790-b935-4c31-8c83-90528e918c68.jpg)

**Another Example:**

Before Refresh:

![Lens bug3](https://user-images.githubusercontent.com/22417498/226156516-6d89ff59-ebc0-4740-b1b3-c41a8745601d.jpg)

After Refresh:

![Lens bug4](https://user-images.githubusercontent.com/22417498/226156648-94079777-d018-4dd7-af71-eb7eac5d3821.jpg)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
