### ISSUE TITLE
Unfollow button not working

### ISSUE THREAD

**Issue by Jason537** [lensterxyz/lenster#2094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After I follow an account, I want to unfollow, but it shows blank here

### Expected Behavior

Unfollowing works fine

### Steps To Reproduce

![微信图片_20230319140725](https://user-images.githubusercontent.com/75970087/226156943-1ebff820-6ab3-4d45-bd44-578a9c14156f.png)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
You can still go to their profile and unfollow 🙇🏼 

We hide it because the sudden follow and unfollow might cause some issues because the txn is still not indexed on lens API.
