### ISSUE TITLE
The operation couldn’t be completed. (TrustWalletConnect.WCError error 1.)

### ISSUE THREAD

**Issue by keatlyKHZ** [lensterxyz/lenster#2124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can log in with Trust Wallet mobile app but after that, any action I try results in this error "The operation couldn’t be completed. (TrustWalletConnect.WCError error 1.)"

Specifically, I've tried to update my profile and add pics and tried to mirror posts.
 
I've tried on Chrome & Safari on my Mac and also on Chrome on my iPhone

### Expected Behavior

I expect the option to sign transactions in my wallet and then use application as intended

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome, Safari

**Comment by bigint** [comment]
I can't reproduce this in trust wallet
