### ISSUE TITLE
Requesting signature (Expected a value of type "ProxyActionId" but received: { reason: rejected}

### ISSUE THREAD

**Issue by ddsweth** [lensterxyz/lenster#2125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

on Lenster, i could follow, mirror, like etc w/o signing and then out of nowhere it started asking me to sing every single action. when I sign it it returns the message on the title and also on the print below. I am not a programmer at all so I don't know if I'm reporting this right or not, but i'll be checking here in case you need further info. Sorry if this is some misunderstanding on my end.

![image](https://user-images.githubusercontent.com/127057524/226465024-0d55943a-8707-4ae1-822a-f1ec84aa4deb.png)

### Expected Behavior

Not needing my signiature on follows and likes, and if that's somehow now required, not display the error message.

### Steps To Reproduce

don't know what this meas 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![error message](https://user-images.githubusercontent.com/127057524/226465715-f61b09cb-20fa-43c2-bf8d-22b4a1d0e422.png)

**Comment by bigint** [comment]
Fixed
