### ISSUE TITLE
setting bug

### ISSUE THREAD

**Issue by xuchun130** [lensterxyz/lenster#2134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I set super follow, it doesn't work properly, the system prompts that super follow cannot be set

### Expected Behavior

The super-following account function can be used normally

### Steps To Reproduce

https://twitter.com/chunzhi130/status/1638090637076725763?s=19

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Chrome

### Anything else?

just one

**Comment by bigint** [comment]
Can you send the error screenshot please

**Comment by bigint** [comment]
Closing this! feel free to reopen with more details
