### ISSUE TITLE
[Feature Request] Delegate Lens profile to other wallet via dispatcher function

### ISSUE THREAD

**Issue by keivinonline** [lensterxyz/lenster#214]
### Summary

**Proposed feature:** 
- Allow users to post, comment, mirror, set follow module and change the profile picture on behalf of you using their wallet.

**Sample API usage:**
- https://docs.lens.xyz/docs/create-set-dispatcher-typed-data

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
