### ISSUE TITLE
The cid code of an image in a decentralized storage system is used incorrectly

### ISSUE THREAD

**Issue by tyangdd** [lensterxyz/lenster#2145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error example：https://twitter.com/sissi046/status/1638385067360927744?s=20  https://twitter.com/sissi046/status/1638385098482683904?s=20

### Expected Behavior

Stopping improvement

### Steps To Reproduce

https://twitter.com/sissi046/status/1638385067360927744?s=20

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![image](https://user-images.githubusercontent.com/112801250/226848127-97c5d518-8528-4cda-b53e-21bad43e2fcc.png)

**Comment by bigint** [comment]
Share what error you see

**Comment by bigint** [comment]
All CID in lenster are available on all gateways meaning it's decentralized 🙇
