### ISSUE TITLE
URLs in user bios lead to Lens profiles

### ISSUE THREAD

**Issue by geoist1** [lensterxyz/lenster#2147]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/92825012/226953279-5a2dc598-2826-40d9-885c-15ce2e9415ee.png)

### Expected Behavior

I would expect a link without the @ sign to lead me to the URL rather than a user profile.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by bigint** [comment]
Thanks for reporting! I can reproduce this issue.

**Comment by geoist1** [comment]
Cool! Btw. please check DMs on Lenster.

**Comment by bigint** [comment]
Fixed
