### ISSUE TITLE
number of like

### ISSUE THREAD

**Issue by AbdolCrypto** [lensterxyz/lenster#2150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I sent a comment and nobody liked my comment but its show 4 people liked me!

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![IMG__](https://user-images.githubusercontent.com/124624827/227063729-b36d6a4c-ac38-4edb-ba8f-ba20fb870cac.png)

**Comment by bigint** [comment]
This is an issue on lens API

Please report it here: https://github.com/lens-protocol/api-examples/issues
