### ISSUE TITLE
lensfren problem

### ISSUE THREAD

**Issue by Pawatz** [lensterxyz/lenster#2158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't follow anyone it just keeps showing Expected a value of type "ProxyActionId" but received: { reason: "REJECTED" }
and insufficient balance which I believe I have enough.

And I can't post anything on lenster too which similar to this problem.

### Expected Behavior

It should just follow the people I want to follow without any problem.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![image](https://user-images.githubusercontent.com/88139728/227420393-613470df-8588-49d3-a1e3-cfb58a0c7917.png)

**Comment by bigint** [comment]
This issue is not related to lenster 🙇🏼

**Comment by hanahem** [comment]
@Pawatz thanks for raising this, have you checked if you have enough balance of the right token (WMATIC and not MATIC, sometimes it's confusing)?

So the first issue is related to the proxy not letting you go through. Take some time and then retry (with a clean cache and all). If that happens again send here the error messages you get.

**Comment by Pawatz** [comment]
It's still showing this message Usage limit exceeded, please try again
later.

I understand the different between WMATIC and MATIC pretty well which I
have both, which I believe I have enough we these transaction.

PS. Already clear cache cookies and stuff. still not working.

In the communities many of us are having this problem.

ในวันที่ ศ. 24 มี.ค. 2023 เวลา 15:33 Wassim ***@***.***>
เขียนว่า:

**Comment by hanahem** [comment]
Thanks @Pawatz .
Looking into it with the team.
