### ISSUE TITLE
[Bug] Own profile and followed profiles are showing in "who to follow" section

### ISSUE THREAD

**Issue by 0xkeivin** [lensterxyz/lenster#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Example of a followed profile showing up:**
![image](https://user-images.githubusercontent.com/65915812/182437703-9ff2477d-618a-4c71-ad14-64f9fc12bc00.png)

**Example of own profile showing up (gotten feedback from discord):**
![image](https://user-images.githubusercontent.com/65915812/182438024-ec67ba21-9ec1-49e1-a1a5-57819cadb806.png)

### Expected Behavior

"who to follow" section
- should not show own profile as suggestion
- should show profiles that are not currently being followed as suggestions

### Steps To Reproduce

This would be slightly tricky to reproduce as it involves refreshing the homepage several times till it shows either
- own profile
- profiles that are currently being followed 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
For now this is hardcoded in Lens backend, when AI/ML in place this will not be the case, closing this because this does not fall in the scope of the project 🙏🏼 

cc @joshstevens19
