### ISSUE TITLE
can't find my username 

### ISSUE THREAD

**Issue by yitiaolaolrou** [lensterxyz/lenster#2165]
I can't find my username in the LENS search box, what's wrong? Is it blocked?

**Comment by bigint** [comment]
drop your username

**Comment by yitiaolaolrou** [comment]
doubeiyu.lens    thank u sir

**Comment by yitiaolaolrou** [comment]
> drop your username



> doubeiyu.lens thank u sir



> drop your username

doubeiyu.lens thank u sir

**Comment by bigint** [comment]
Hi @yitiaolaolrou 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
