### ISSUE TITLE
The lens name cannot be found in the lenser search

### ISSUE THREAD

**Issue by nftnfts** [lensterxyz/lenster#2166]
Name is: cion98
![111](https://user-images.githubusercontent.com/111410763/227500673-626240cd-76d8-4ee9-8eef-f4a3ed74789b.png)

**Comment by bigint** [comment]
Hi @nftnfts 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
