### ISSUE TITLE
The name cannot be found in Lenster

### ISSUE THREAD

**Issue by signineth** [lensterxyz/lenster#2167]
xmtp_.lens

**Comment by bigint** [comment]
Hi @signineth 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
