### ISSUE TITLE
Lenster can't find personal names

### ISSUE THREAD

**Issue by nftii** [lensterxyz/lenster#2168]
I don't know why I can't query the personal name hawku.lens

**Comment by bigint** [comment]
Hi @nftii 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
