### ISSUE TITLE
`linkifyRegex(urlRegex)` crash the browser

### ISSUE THREAD

**Issue by xbwl20** [lensterxyz/lenster#2183]
https://lenster.xyz/u/lens6

When I opened his lens profile, my browser couldn't load his posts, and weirder still, my browser crashed.

**Comment by foolo** [comment]
I looked at this a bit and the crashing post is https://lenster.xyz/posts/0x82b9-0x26

The crash seems to happen when the `linkifyRegex(urlRegex)` plugin is called in
https://github.com/lensterxyz/lenster/blob/main/apps/web/src/components/Shared/Markup/index.tsx

**Comment by bigint** [comment]
Weird @foolo got to know why it's crashing?

**Comment by foolo** [comment]
Yeah, I haven't figured it out. But some more investigation shows that it crashes when urlRegex is run (`exec()`) on the paragraph in the screenshot below. `urlRegex` is a super long string, 8820 characters. But it works for all other posts, so it must be a combination of the regex pattern **and** the text in question, that causes the exec() call to hang.
![Screenshot_2023-03-26_15-16-39](https://user-images.githubusercontent.com/667227/227778310-a37d90b4-175d-4944-9e62-9101c4dc5acb.png)

**Comment by bigint** [comment]
Fixed
