### ISSUE TITLE
post bug

### ISSUE THREAD

**Issue by ZHI00** [lensterxyz/lenster#2216]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

When I publish a post on the homepage, the post with the picture always needs to be sent several times before it succeeds. According to my guess, there is an error and no retry while queuing, or the posting fails due to jumping to other pages while queuing. Hope to fix it soon.

### Expected Behavior

Hope to publish successfully

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/46469429/227829756-371cf029-f822-4ace-be46-9ce49cfd50d9.png)

That's it, see my pictures for details.
my account: @btc8w8

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
After posting it will push to API and queued in the blockchain, you don't need to post again and again, even if you jump to another page the post will be posted.
