### ISSUE TITLE
insert text wrapped with ``` gets ignored

### ISSUE THREAD

**Issue by seviu** [lensterxyz/lenster#2237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Tried to post some code using a [Fenced Code Block](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) or ``` in hoping that lenser supports markdown.

Every text I wrap with ``` gets eaten and not displayed:

If trying to post:

Hello
```
World
```

... Only things people will see is World

### Expected Behavior

I would expect to see a message with the text Hellow and a World the line before (maybe with the ``` tag if markdown is not supported yet)

### Steps To Reproduce

Write 

Hello
```
World
```

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
cc @harish-sethuraman

**Comment by bigint** [comment]
We don't support this syntax
