### ISSUE TITLE
Not deleting old posts

### ISSUE THREAD

**Issue by geodiegofer** [lensterxyz/lenster#2239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I bought the profile @ybibm64yqmftvr8 in lens today and when I tried to delete old posts of the past owner profile the app show me that the post was deleted but it continue there 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by geodiegofer** [comment]
I sent an email with some screenshots in order to explain the problem. Please confirm me if you receive that and if it helped you.

**Comment by bigint** [comment]
Please share it here cuz issue is raised here 🙇🏼

**Comment by geodiegofer** [comment]
<img width="1357" alt="1" src="https://user-images.githubusercontent.com/26012115/228311496-f463d17b-c222-4905-bb18-39f282df0759.png">
<img width="1338" alt="2" src="https://user-images.githubusercontent.com/26012115/228311522-bba724db-b03e-4bd2-9bc6-be99d7972f5c.png">
<img width="1319" alt="3" src="https://user-images.githubusercontent.com/26012115/228311547-4e804497-1c30-45bf-824f-ea45da324e0c.png">
<img width="624" alt="4" src="https://user-images.githubusercontent.com/26012115/228311561-84b6f173-717d-45b1-ab9b-564111b341c6.png">

**Comment by bigint** [comment]
> I observed that the bug was fixed after I sent an email explaining step by step with screenshots. Thank you very much for the support. I hope that it was helpful for the project.

Hope all fixed 🚀
