### ISSUE TITLE
Can't change avatar

### ISSUE THREAD

**Issue by danielljanow** [lensterxyz/lenster#2243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I click the button to upload a new picture as the avatar, the system does not respond and the avatar cannot be changed

### Expected Behavior

Ability to change avatars normally

### Steps To Reproduce

![微信图片_20230328235358](https://user-images.githubusercontent.com/128162853/228296821-1ac04623-19ca-4d86-9e29-73095b80ad44.jpg)

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Others

**Comment by bigint** [comment]
cc @foolo can you reproduce this?

**Comment by foolo** [comment]
> cc @foolo can you reproduce this?

Nope, I tested it right now. For me it works fine. No freeze and the avatar gets updated.

**Comment by bigint** [comment]
Thanks for verifying 🚀 

Closing this
