### ISSUE TITLE
Change the profile name or do a new account

### ISSUE THREAD

**Issue by geodiegofer** [lensterxyz/lenster#2244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Dear team,

I just bought my profile in the market and the name corresponds to the last owner but not to me, I want to ask if is possible to change my current profile name "@ybibm64yqmftvr8" to "@geodiego"

If this is not possible, can you create a new profile for me with the name "@geodiego"?

Thank you,

Diego

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
It's not possible to change handle right now 🙇🏼
