### ISSUE TITLE
This may be a bug.

### ISSUE THREAD

**Issue by aimerrys01** [lensterxyz/lenster#2248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I clicked Unfollow, I was promoted, 'You are not following this profile' on the page of someone I need to follow "

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Hi @aimerrys01 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!

**Comment by aimerrys01** [comment]
[cid:cce74d63-e4d7-4c07-ad4e-ecf48e8f9c2f]


"I thought this problem has been bothering me for a long time, and I'm not sure who to find to solve it.". Can you tell me?

________________________________
发件人: bigint ***@***.***>
发送时间: 2023年3月29日 5:22
收件人: lensterxyz/lenster ***@***.***>
抄送: aimerrys01 ***@***.***>; Mention ***@***.***>
主题: Re: [lensterxyz/lenster] This may be a bug. (Issue #2248)


Closed #2248<https://github.com/lensterxyz/lenster/issues/2248> as completed.

―
