### ISSUE TITLE
i cannot comment a video

### ISSUE THREAD

**Issue by BernardoKonci** [lensterxyz/lenster#2269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

Expected a value of type "ProxyActionId" but received: { reason: "REJECTED" }

**Comment by bigint** [comment]
Hi @BernardoKonci 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
