### ISSUE TITLE
I can not collect

### ISSUE THREAD

**Issue by MChisholm27** [lensterxyz/lenster#2273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I try to collect it says I do not have enough allowance. I tried to raise my allowance, but it fails. I was trying to do a 3 WMatic collect to support Lenster, but I don't know what to do. I have 19 Matic available, 4 Matic as well.

### Expected Behavior

Collecting :) LOL

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

### Anything else?

<img width="357" alt="Screenshot 2023-03-30 at 10 54 27 AM" src="https://user-images.githubusercontent.com/83989897/228924923-c93aaf51-589e-44aa-ae6e-26b37ec1d5dd.png">
<img width="355" alt="Screenshot 2023-03-30 at 10 31 38 AM" src="https://user-images.githubusercontent.com/83989897/228924962-29c87497-99c4-4bb6-b682-cf2a3a152ce3.png">

**Comment by bigint** [comment]
Go to allowance settings and revoke and enable the module again

https://lenster.xyz/settings/allowance
