### ISSUE TITLE
Usability bug - Comment button scrolling to top and not working as expected

### ISSUE THREAD

**Issue by eddsaura** [lensterxyz/lenster#2276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This button is doing scrollTop and not focusing the input when clicking.

### Expected Behavior

I think this button should mention the person who wrote in that context. 
Scroll to the input and focus it.

### Steps To Reproduce

Just click the comment button in a reply

<img width="100" alt="image" src="https://user-images.githubusercontent.com/13334047/229067396-8cd5ff6f-73f6-4598-b67d-c7776a7a69df.png">

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

Lets make socials great again 

(?) lol sorry, but the feedback was real.

**Comment by bigint** [comment]
Cant repro
