### ISSUE TITLE
 Missing or invalid. request() method: eth_signTypedData_v4

### ISSUE THREAD

**Issue by djs11491** [lensterxyz/lenster#2287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When posting or interacting with enable dispatcher button I receive the error below. It appears in the bottom right of the screen
<img width="390" alt="Screenshot 2023-03-31 at 10 31 03 PM" src="https://user-images.githubusercontent.com/3449681/229261695-d7978522-55ef-4d11-b784-7e088079e01d.png">

Missing or invalid. request() method: eth_signTypedData_v4

### Expected Behavior

Not sure - I imagine I sign something on my wallet. 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by treethought** [comment]
getting same issue after signing in with wallet connect on brave and firefox even after clearing cache/local storage.

**Comment by cptnanon** [comment]
I am experiencing the same issue. I cannot even sign to upgrade to the new dispatcher

**Comment by bigint** [comment]
No longer happens
