### ISSUE TITLE
I found that my interaction is not working

### ISSUE THREAD

**Issue by 0xcheche** [lensterxyz/lenster#2295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I found that my interaction is not working
My posts, mirrors, likes and comments don't show up! But after hours and hours and hours it will suddenly show up

### Expected Behavior

I feel that my account is abnormal and is restricted. I take my account very seriously, it is a record of my journey. I just want to use my account normally.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

plz dm me：
twitter @0xcheche
discord： rubyouo#5581

**Comment by bigint** [comment]
Hi @0xcheche 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
