### ISSUE TITLE
I will put an image and stay a lot of time indexing

### ISSUE THREAD

**Issue by geodiegofer** [lensterxyz/lenster#2301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to publish some images but is not charging and say that is indexing. In annex screenshots about it.
<img width="870" alt="Screenshot 2023-04-01 at 16 22 49" src="https://user-images.githubusercontent.com/26012115/229310257-6d4205c2-eba0-44c8-a665-80293928bbb1.png">

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
