### ISSUE TITLE
Do not load all XMTP messages at once (direct messages pagination)

### ISSUE THREAD

**Issue by ustas-eth** [lensterxyz/lenster#2302]
### Summary

Current logic loads all the messages when users visit their DMs. It can be very frustrating because users have to wait a significant time when the message count is more than could be loaded in several requests.
For example, my DMs load about one minute (I have over a thousand messages, I believe).
I propose to make a lazy load or pagination for the DMs page.

![image](https://user-images.githubusercontent.com/82833595/229322718-16fe478e-3abf-42af-9277-62b3e12707c2.png)

**Comment by bigint** [comment]
cc @neekolas @bhavya2611

**Comment by neekolas** [comment]
We are talking specifically about the conversation list, right?

The message history of DMs is already paginated

**Comment by ustas-eth** [comment]
> We are talking specifically about the conversation list, right?
> 
> The message history of DMs is already paginated and lazy loading.

Yes, exactly, the conversations list
