### ISSUE TITLE
Why do all the messages I send are indexing? Is there something wrong with my account?

### ISSUE THREAD

**Issue by androidcde** [lensterxyz/lenster#2307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I sent a message yesterday, and until today I found that it is still in the indexing state

### Expected Behavior

I hope I can send the post normally

### Steps To Reproduce

It’s just a simple send, and then the send has been unsuccessful, and it has been in the indexing state

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

<img width="814" alt="2023-04-02 19 07 14" src="https://user-images.githubusercontent.com/22849608/229349102-d23e87de-1f86-4889-8234-e6eb086652b1.png">

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
