### ISSUE TITLE
Not save changes

### ISSUE THREAD

**Issue by BARIOPUBG** [lensterxyz/lenster#2308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

does not save changes to profile name and social network link

### Expected Behavior

no save change button

### Steps To Reproduce

Not

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome

### Anything else?

Not

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
