### ISSUE TITLE
Cannot change the profile picture, and profile cover

### ISSUE THREAD

**Issue by hxhp0809** [lensterxyz/lenster#2332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I try so many times just to change my profile picture, and profile cover. It always said that profile update successfully. However, the changes were never happened.

### Expected Behavior

It should be done pretty quick

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome, Others

**Comment by bigint** [comment]
Should be fixed
