### ISSUE TITLE
cant comment and follow users on phaver mobile app

### ISSUE THREAD

**Issue by Burakowsky** [lensterxyz/lenster#2333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ım having problem with sending posts and comments in mobile app of phaver. also ı cant follow people it just say your follow unsuccessful and your commenting unsuccessful 

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Raise this issue on phaver
