### ISSUE TITLE
I can't access my profile

### ISSUE THREAD

**Issue by VandersonMartinsSJC** [lensterxyz/lenster#2378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Looks like something went wrong!
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.

[Go to home](https://lenster.xyz/)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Please recreate with more details 🙇🏼
