### ISSUE TITLE
I can not collect a post

### ISSUE THREAD

**Issue by Runer13** [lensterxyz/lenster#2400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to collect a post of @yoginth and I have enough wmatic in my wallet but all the time when I try to collect there is an error message pops up and it fails.
<img width="1260" alt="Screenshot 2023-04-06 at 13 26 41" src="https://user-images.githubusercontent.com/107859142/230351705-ddb91b1e-98ca-4c43-ad22-66541ba6f7a3.png">

### Expected Behavior

I expect to collect post.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome, Firefox

**Comment by bigint** [comment]
Reload the page and try again 🙇🏼
