### ISSUE TITLE
No <title>

### ISSUE THREAD

**Issue by miohtama** [lensterxyz/lenster#2408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you Google Lenster, the website lacks title and description 

<img width="266" alt="image" src="https://user-images.githubusercontent.com/49922/230568315-254fb7d6-764d-4327-950d-fc83a0236925.png">

### Expected Behavior

Lenster is well-presented in a Google search

### Steps To Reproduce

Google Lenster

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Firefox

**Comment by bigint** [comment]
We gave a fix already, Google will take some time to fix this
