### ISSUE TITLE
Missing Posts

### ISSUE THREAD

**Issue by considrew** [lensterxyz/lenster#2415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Posts are prepared in both Orb on mobile or Lenster on desktop. Posts are inconsistently missing or not posted at all. Posts consist of seven images referenced within the post text.

### Expected Behavior

The post should have loaded and posted to my profile with the contents intact.

### Steps To Reproduce

Attempted posts on both platforms, unable to create on either consistently.

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
