### ISSUE TITLE
Message notification badge shown when there are no new messages

### ISSUE THREAD

**Issue by qingyiz** [lensterxyz/lenster#2442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I open the webpage every afternoon, and after logging in, the message on the interface reminds me that there is a new message, that is, there will be a red dot, but after I click it, I find that there is no new private message

### Expected Behavior

If there is no private message information, there should be no red dot prompt

### Steps To Reproduce

Use the account normally on the first day, then like, comment, and post articles. After logging in to the account on the second day, there will be a red dot prompting you to have private message information, but in fact there is no.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![WeChat08ccb4ff77685ac3d8e0ed3e613a94e9](https://user-images.githubusercontent.com/67898356/230717730-13a1dd1a-8c9f-4830-8ee4-1a850f9d51a9.png)
![WeChate7b869bda98eb686a9a6ef027eb3ec1e](https://user-images.githubusercontent.com/67898356/230717768-5329c1c7-5feb-458e-a320-54adff78ccfd.png)
![WeChatd5fd66caa15580ca0715ac8cbbcd1530](https://user-images.githubusercontent.com/67898356/230717784-5986c9a9-5909-4595-9408-75a8d1ddb146.png)

**Comment by luduvigo** [comment]
Hi  👋
The issue name is not clear to me.

Anyway, I am facing this bug as well.
Cheers.

**Comment by bigint** [comment]
Fixed
