### ISSUE TITLE
page changes

### ISSUE THREAD

**Issue by Guoxtwo** [lensterxyz/lenster#2482]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I was surfing in "interesting-images" page. suddenly, i find something intereted me,so i clicked and commented.
then i click page go-back button, it lead me to "interesting-all post".

### Expected Behavior

i need to go back from where surfing at "the post" i was found interesting before enter in to comment.

### Steps To Reproduce

i don't know code.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

i believe you understand me.

**Comment by bigint** [comment]
This seems like not related to lenster
