### ISSUE TITLE
Can't Post Anything

### ISSUE THREAD

**Issue by abhishekgg1** [lensterxyz/lenster#2489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I posted some post 5 days ago it is still pending and now i can't Do Another Post Anymore

### Expected Behavior

It Should Be Posted 

### Steps To Reproduce

I don't know Anything 
Please Solve this

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

Nope
Nothing More

**Comment by bigint** [comment]
Please share the error and reopen the issue
