### ISSUE TITLE
Show arweave content uri in single publication page

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#25]

**Comment by jayantdahiya** [comment]
Hi @bigint, I want to contribute to this project. Can you give me some more details on this issue so I could start working on it.

**Comment by bigint** [comment]
Sure @jayantdahiya, if u have checked mirror.xyz they show the arweave hash in the bottom of the article, we need to show something like that 🙇🏼 

https://dev.mirror.xyz/5gt60vKFJZ_tR1BjoJ7-Y0sNw7REebStHjzFU5x73J0

![Screenshot 2022-08-14 at 5 28 14 PM](https://user-images.githubusercontent.com/69431456/184535718-cdfe6999-8ae1-4c45-8793-6295bcf63984.png)

**Comment by jayantdahiya** [comment]
@bigint, are we looking for something like this in the UI? 🤔
<img width="881" alt="Screenshot 2022-08-15 at 10 00 45 AM" src="https://user-images.githubusercontent.com/31251655/184577294-a1574c5a-cb3b-4ff5-9d81-3211e516d50c.png">

**Comment by bigint** [comment]
@jayantdahiya This is a bit complex one, so I took care and shipped it 🙏🏼 

![image](https://user-images.githubusercontent.com/69431456/184657225-6f519383-967f-43e4-aae3-062e6b21d59a.png)
