### ISSUE TITLE
[ENG-41] About the problem that the format of the copied content is modified

### ISSUE THREAD

**Issue by hbue666** [lensterxyz/lenster#2501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to copy some text content with a fixed format like

-  Copy Liked Tweets from Twitter

-  Copy links from other web pages

-  Or copy the content with spaces before and after and switch between up and down lines

Paste and publish on lenster, the source format will be discarded by default and only the text will be kept

### Expected Behavior

I want to either fully preserve the source formatting of the copied content or give the user the option to keep it

### Steps To Reproduce

1、I want to copy this text and post it on lenster
![image](https://user-images.githubusercontent.com/85141427/231224862-0e04edb8-763d-49d2-974f-250a9870cba8.png)
2、But when I paste it on the lenster, it automatically becomes this text format
![image](https://user-images.githubusercontent.com/85141427/231224975-1ada1dba-9d51-44ee-b516-d042df94c5b2.png)
3、The English content is the same, I am trying to copy this text from my gmail to post to lenster
![image](https://user-images.githubusercontent.com/85141427/231225832-cc8ba5b7-e460-486b-b9d8-3676784f7919.png)
4、But it turned out like this, the original bold text was smoothed out, and the format of the first paragraph was changed to plain text
![image](https://user-images.githubusercontent.com/85141427/231226360-08e4a457-2238-431e-bfdd-3964401329f7.png)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome, Firefox, Edge

### Anything else?

I think this situation is the same on all browsers, but I only use chrome, edge and Firefox, and the Chinese content and English content have been modified; whether it can be changed to let users choose whether to keep the original format，Just like what word does
![image](https://user-images.githubusercontent.com/85141427/231227856-9ab27ffa-b1bc-47e8-a07c-76a3a544f6ae.png)

<sub>[ENG-41](https://linear.app/heyxyz/issue/ENG-41/about-the-problem-that-the-format-of-the-copied-content-is-modified)</sub>

**Comment by hbue666** [comment]
looking forward to ur reply，thx！

**Comment by bigint** [comment]
cc @harish-sethuraman

**Comment by bigint** [comment]
Can't repro
