### ISSUE TITLE
the position order of uploaded images 

### ISSUE THREAD

**Issue by w18529** [lensterxyz/lenster#2521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Unable to adjust the position order of uploaded images when publishing a post

### Expected Behavior

working

### Steps To Reproduce

![Screenshot_2023-04-13-14-17-28-806_com android chrome](https://user-images.githubusercontent.com/129160254/231670389-a8f18303-b680-4f95-98f7-03a7840d25f2.jpg)

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
RN it's not possible, we will look at this later
