### ISSUE TITLE
Collect 

### ISSUE THREAD

**Issue by chola3** [lensterxyz/lenster#2526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Others

### Anything else?

![Screenshot_20230413_214832_MetaMask](https://user-images.githubusercontent.com/116304383/231855513-75e4e264-46eb-4ec3-be53-6248b9822602.jpg)

**Comment by bigint** [comment]
Dupe of #1722
