### ISSUE TITLE
Followers count mismatch between profile details and modal

### ISSUE THREAD

**Issue by einfeiff** [lensterxyz/lenster#2536]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have 3 fans, but when I click to view the list of fans, it tells me that no users follow me, which is obviously a mistake

### Expected Behavior

Display my followers list correctly

### Steps To Reproduce

![image](https://user-images.githubusercontent.com/125732347/232133218-6efe5187-c6ad-47a9-ad07-a5fb6bec909d.png)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

NO

**Comment by foolo** [comment]
Seems that `totalFollowers` in `ProfileStats` is not synced correctly. (`profile?.stats?.totalFollowers` in `apps/web/src/components/Profile/Followerings.tsx`). As for this issue, that's the value that says followers=3

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!

**Comment by foolo** [comment]
@bigint I think that this other issue could be same problem: https://github.com/lensterxyz/lenster/issues/2462 , so maybe that one can be closed for the same reason as this.
