### ISSUE TITLE
The Snapshot widget does not show up for personal spaces.

### ISSUE THREAD

**Issue by bjcd** [lensterxyz/lenster#2558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When pasting a snapshot link on a Lenster post with a known space such as Arbitrum or any other big spaces, the widget will load as expected in the post. With my personal space, the widget does not load, the snapshot URL remains visible and the link thumbnail appears, but not the widget.

I have tried with several different proposals, but no luck.

Example here: https://lenster.xyz/posts/0x01a467-0x0121

### Expected Behavior

The widget should appear, even with personal, less known spaces.

### Steps To Reproduce

- Create a personal space
- Use the single vote strategy
- Copy the url of the proposal
- Paste in a Lenster post

Example here: https://lenster.xyz/posts/0x01a467-0x0121

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

**Comment by bigint** [comment]
Fixed
