### ISSUE TITLE
[ENG-46] Fix other language in notifications

### ISSUE THREAD

**Issue by saagu335** [lensterxyz/lenster#2561]
![Image](https://user-images.githubusercontent.com/69431456/232331583-11144fc5-9016-4a86-8760-43c6e6bc826d.png)

<sub>[ENG-46](https://linear.app/heyxyz/issue/ENG-46/fix-tamil-language-in-notifications)</sub>

**Comment by foolo** [comment]
solved by https://github.com/lensterxyz/lenster/pull/3780
