### ISSUE TITLE
[ENG-64] Fix profile dropdown for other languages

### ISSUE THREAD

**Issue by saagu335** [lensterxyz/lenster#2566]
![Image](https://user-images.githubusercontent.com/69431456/232331894-f117bccc-26b4-4143-bf53-b8489082bae3.png)

<sub>[ENG-64](https://linear.app/heyxyz/issue/ENG-64/fix-profile-dropdown-for-other-languages)</sub>

**Comment by foolo** [comment]
@saagu335 Is this about that some lines break in two? I.e. we want every string to fit on one line?
