### ISSUE TITLE
[ENG-50] Fix profile list in see through lens selector

### ISSUE THREAD

**Issue by saagu335** [lensterxyz/lenster#2567]
![Image](https://user-images.githubusercontent.com/69431456/232332000-95bb3fd0-3f42-4c7d-944f-e8004170c8ed.png)

<sub>[ENG-50](https://linear.app/heyxyz/issue/ENG-50/fix-profile-list-in-see-through-lens-selector)</sub>

**Comment by foolo** [comment]
@saagu335 Is this about changing it so that it shows more than only two profiles?
