### ISSUE TITLE
Add what's new modal for big updates

### ISSUE THREAD

**Issue by saagu335** [lensterxyz/lenster#2569]
![Image](https://user-images.githubusercontent.com/69431456/232332075-890b13b1-07dc-42e7-867e-832e16f5eb52.png)

**Comment by foolo** [comment]
@saagu335 Any thought on where to publish/store the content of each announcement? Should it simply be added in source code, or should it pull news from some kind of source?

**Comment by bigint** [comment]
We can drop this idea IMO
