### ISSUE TITLE
Excuse me, what is the problem that I have to pay for Posting or forwarding?

### ISSUE THREAD

**Issue by ronghai1313** [lensterxyz/lenster#2593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Excuse me, I speak or forward all actions need to pay, this is why?

### Expected Behavior

I hope you can solve my problem, thank you!

### Steps To Reproduce

<img width="848" alt="微信图片_20230418155748" src="https://user-images.githubusercontent.com/128978716/232711208-7bbbd74c-1cf9-45c8-b36a-005c19b24c72.png">

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

<img width="848" alt="微信图片_20230418155748" src="https://user-images.githubusercontent.com/128978716/232711111-baa708a5-eefa-4775-bb7d-a0fc56ea43c1.png">

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
