### ISSUE TITLE
Bug: Cant access DMs on Lenster using WalletConnect v2 and Rainbow - No request to sign

### ISSUE THREAD

**Issue by petermdenton** [lensterxyz/lenster#2609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am not able to access my messages on Lenster.

Steps to reproduce:
- Login to Lenster using WalletConnect v2 (using Rainbow wallet) - I get prompted with a wallet signature
- Login to Lens - I get prompted with a wallet signature
- Navigate to https://lenster.xyz/messages - I do not get a wallet signature

I have cleared the cache/application memory browser to clear everything. This does not work.
Using MetaMask works fine. It appears to be isolated to WalletConnect v2.

### Expected Behavior

I would expect to get a wallet signature prompt on https://lenster.xyz/messages and be able to access messsages.

### Steps To Reproduce

Steps to reproduce:
- Login to Lenster using WalletConnect v2 (using Rainbow wallet) - I get prompted with a wallet signature
- Login to Lens - I get prompted with a wallet signature
- Navigate to https://lenster.xyz/messages - I do not get a wallet signature

I have cleared the cache/application memory browser to clear everything. This does not work.
Using MetaMask works fine. It appears to be isolated to WalletConnect v2.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by galligan** [comment]
I can reproduce this consistently and can confirm that in the same window after a Sign Out I can use MetaMask, which does show the Enable XMTP signature request when navigating to DMs.

The same flow (WC vs. MM) can also be reproduced on mobile with the same results.

**Comment by bigint** [comment]
Fixed
