### ISSUE TITLE
Can't add any cover picture

### ISSUE THREAD

**Issue by Aanostra** [lensterxyz/lenster#2614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, it's impossible to add a cover picture, the click button is not working

### Expected Behavior

should be done asap

### Steps To Reproduce

click on "choose file"

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

### Anything else?

nope

**Comment by foolo** [comment]
@Aanostra If I understand this correctly, nothing happens when you click the "Choose file" button under the cover image preview, is that right?
![Screenshot_2023-04-20_19-52-24](https://user-images.githubusercontent.com/667227/233448118-358338c8-276d-4f73-932f-550a0bd6696a.png)

**Comment by Aanostra** [comment]
Hello, yes exactly !

Le jeu. 20 avr. 2023 à 19:53, Olof Andersson ***@***.***> a
écrit :

**Comment by foolo** [comment]
@Aanostra, That's strange, for me it works fine, so it might be something related to your environment. Are there any error messages in the console that could be relevant? What OS are you on?

**Comment by Aanostra** [comment]
Ohhh it's working now, weird

Sorry, but you can close the issue I think

Le ven. 21 avr. 2023 à 12:45, Olof Andersson ***@***.***> a
écrit :

**Comment by foolo** [comment]
@Aanostra Ok, thanks for checking! I closed the issue.
