### ISSUE TITLE
Overflow hidden issue on mention users dropdown

### ISSUE THREAD

**Issue by mkkmail** [lensterxyz/lenster#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

there is a CSS bug when you want mention user on create post box. dropdown cut because of overflow hidden style on box and user can not see and scroll the dropdown. 

<img width="1353" alt="Screen Shot 1401-05-14 at 11 10 03" src="https://user-images.githubusercontent.com/8843747/183018197-8f44f427-f04d-4e17-ab6f-e1b4cebfb632.png">
 

### Steps To Reproduce

just remove class name "overflow-hidden" from post box.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
<img width="493" alt="Screenshot 2022-08-07 at 3 29 52 PM" src="https://user-images.githubusercontent.com/69431456/183285578-3940b4cd-7702-44cb-9d00-6612c67b09b9.png">

Thanks fren this should be fixed now 🚀
