### ISSUE TITLE
Keep getting charged to interact... post/mirror/comment etc.

### ISSUE THREAD

**Issue by HollywodMeta** [lensterxyz/lenster#2633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I keep having to approve anything I do post/mirror/comment and pay a fee.  It wasn't like this before but now I can't do anything without being charged.  Seems like a good way to drive people like me away how have been here for months.

### Expected Behavior

Not to be charged to use the platform.

### Steps To Reproduce

Almost any interaction.

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome, Brave

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
