### ISSUE TITLE
Duplication in all feeds with fewer results than query limit

### ISSUE THREAD

**Issue by mpaler** [lensterxyz/lenster#2634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://user-images.githubusercontent.com/352390/233748067-223ae674-71b9-4d6e-809d-3c9ddff8ffd7.mov

If user has less than Feed query limit in their feed and toggles b/w tabs on profile page, the items in the feed are duplicated/appended to the feed.

### Expected Behavior

Items in feed should never be duplicated.

### Steps To Reproduce

1. Find a user who has less than 10 publications.
2. View their profile.
3. Toggle between tabs
4. Return to their main feed tab.
5. Observe duplicated items.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

Working locally, I have figured out a possible solution. I will create a PR for this.

**Comment by bigint** [comment]
Fixed
