### ISSUE TITLE
Error 404 when logging out from some pages

### ISSUE THREAD

**Issue by foolo** [lensterxyz/lenster#2670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

1. Go to Notifications page, https://lenster.xyz/notifications (or another page that is only available when logged in, for example https://lenster.xyz/settings )
2. Click Logout in user menu

### Current Behavior

Pages shows "Oops, Lost‽ This page could not be found."
![Screenshot_2023-04-23_12-10-36](https://user-images.githubusercontent.com/667227/233833603-457ba1f3-0d92-4eae-9df1-9d70bd382038.png)

### Expected Behavior

For example, redirect to Lenster start page

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by foolo** [comment]
@bigint, I propose that we redirect to home page in this case, what do you think?

**Comment by bigint** [comment]
@foolo I guess we can add Login button, and make something like login screen

https://lenstube.xyz/settings
