### ISSUE TITLE
Issue while running locally in windows

### ISSUE THREAD

**Issue by KlausMikhaelson** [lensterxyz/lenster#2686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not able to run the repo locally in windows
getting the following error 
` $ lingui compile && PORT=4783 next dev
Compiling message catalogs…
Done!
'PORT' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.`

### Expected Behavior

it should run properly on entering yarn run dev

### Steps To Reproduce

navigate to apps/web and enter `yarn run dev`
you should be on windows

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

### Anything else?

I fixed it by just replacing the scripts with
`"scripts": {
  "dev": "cmd /C \"lingui compile && set PORT=4783 && next dev\"",
  "build": "lingui compile && next build",
  "start": "cmd /C \"set PORT=4783 && next start\"",
  "typecheck": "tsc --pretty --noEmit",
  "lint": "eslint . --ext .ts,.tsx",
  "lint:fix": "eslint . --fix --ext .ts,.tsx",
  "extract": "lingui compile && lingui extract"
}`
and it worked for me so ig just changing it so that it checks the os and than run it should fix this issue maybe ?

**Comment by bigint** [comment]
Fixed
