### ISSUE TITLE
Resolution of Cover

### ISSUE THREAD

**Issue by xbwl20** [lensterxyz/lenster#2707]
![image](https://user-images.githubusercontent.com/74717674/234622783-3682d905-b45e-43b6-9852-b11942ced4d7.png)

**What is the resolution of lenster's cover?**   You can add a reference resolution  to the Settings

Referring to the image above, the image I uploaded looks like this, but does not show the full cover on my profile page

![image](https://user-images.githubusercontent.com/74717674/234623594-ce79b6fe-84f4-4881-840d-c9c813eeed17.png)

**Comment by foolo** [comment]
When a cover image is uploaded, the image is cropped to ratio 3:1, and scaled down to 1500x500px if needed.
When the image is displayed on the profile page, the image is stretched to the browser's full width, but the displayed height is constant 320px, which means that only a part of the image's height is visible.
Also, when you resize the browser width, the cover image is zoomed (see screen recording).
It seems impossible to avoid cropping if we want to show a fixed-ratio image in a variable-ratio area, but if you have any good suggestion, @xbwl20, please let me know.

https://github.com/lensterxyz/lenster/assets/667227/df18fb44-3267-4ae7-a0ae-68308f11bc07

**Comment by bigint** [comment]
This will be fixed in lenster v2
