### ISSUE TITLE
Non nullable field

### ISSUE THREAD

**Issue by krtlp1** [lensterxyz/lenster#2717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i tried to share something, i signed wallet then there was an error like in attachment. You can check the error from attachment. After this error, i can not share my content. I have tried it several time, disconnected and connected wallet etc nothing solved it.
![22651F6B-723E-46A2-8424-03E5D3619CF7](https://user-images.githubusercontent.com/105243184/234755426-395e3af1-43f3-4b64-b2c8-e4d7078a8796.png)

### Expected Behavior

I was able to share couple of days ago.

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Others

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
