### ISSUE TITLE
Doesn't work to post

### ISSUE THREAD

**Issue by RayJang0987** [lensterxyz/lenster#2719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

What is this error, ON the bottom right corner?
This is received after sign-in for Metamsk.

Expected Behavior
![Screenshot_20230428_002823_MetaMask](https://user-images.githubusercontent.com/127759074/234911963-d990148c-e07e-4c5b-80c4-dbc472097ea0.jpg)

Since a few days, The system has asked for transaction fees for every activity on the lenster.
Now they are appearing in this message. I can not post on the lenster.

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!

**Comment by RayJang0987** [comment]
Hello.


Thank you for the prompt reply.

I understand the situation.
And it's backend problem and you're not on charge about it.

Isn't It the problem about the lenster?
If so, why don't you just connect me to the backend team.
Not just close the case even the problem is not solved.

Best regards,



2023년 4월 28일 (금) 오후 9:12, 0x0d ***@***.***>님이 작성:
