### ISSUE TITLE
i enable signless transactions but it's not work.

### ISSUE THREAD

**Issue by Patel1458** [lensterxyz/lenster#2725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i enable signless transactions but it's not work but when i upload post it's saw for sign in and take some matic fee why?

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Edge

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
