### ISSUE TITLE
Add link to google translate in publications

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#2755]

**Comment by foolo** [comment]
Should it look something like this?
https://user-images.githubusercontent.com/667227/235366545-2d9831e2-d97a-4af7-8979-48689f010722.mp4

**Comment by aviroopjana** [comment]
@bigint @foolo Hey, is this issue still open? or anyone working on it... please let me know

**Comment by foolo** [comment]
> @bigint @foolo Hey, is this issue still open? or anyone working on it... please let me know

Hi, I'm actually working on it right now. I'll assign myself. Sorry :)

**Comment by aviroopjana** [comment]
@foolo thanks for the response... best of luck !!
