### ISSUE TITLE
Signing isn't enough, asking for transaction on TESTNET

### ISSUE THREAD

**Issue by Yorden** [lensterxyz/lenster#2759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am adding users I want to follow and it keeps asking me a sign, then a "follow with sig" transaction. Same issue for commenting on post. "Comment with sig" transaction. It was fine before. I also got a error message saying something along the lines of I had "too much" used lenster I think?

also 

 Expected a value of type "ProxyActionId" but received: { reason: "REJECTED" } 

### Expected Behavior

Not asking me for transactions at every actions I do.

### Steps To Reproduce

I made a lot of use of the app. Maybe if too much stress is put on platform this bug happens?

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
