### ISSUE TITLE
repetitive Notifications coming when my friend followed by profile.

### ISSUE THREAD

**Issue by shrinivasdontul** [lensterxyz/lenster#2779]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/41667787/235584974-08df1bd2-f8af-4ac8-8e42-22d0ba19777d.png)

my friend @coco7.lens (cryptosniper08) followed by profile on lenster. but when I checked notifications it shows he has followed 4 times. I have uploaded the screenshot. 

### Expected Behavior

only one notifications should be shown when someone follows me.

### Steps To Reproduce

I gave him my profile link and he followed me. then I checked notifications.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

### Anything else?

![image](https://user-images.githubusercontent.com/41667787/235585380-f1078237-9b81-4eab-85f0-ce76e71a2283.png)

**Comment by bigint** [comment]
Should be fixed
