### ISSUE TITLE
I can't upload pictures when I make a post!

### ISSUE THREAD

**Issue by redazure1990** [lensterxyz/lenster#2792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I can't upload pictures when I make a post!
![123](https://user-images.githubusercontent.com/128831342/236112080-1c369452-7e24-42f1-829f-1cdca64f7196.png)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![123](https://user-images.githubusercontent.com/128831342/236112139-ff0a938a-3ea5-4660-accb-d9eef8e6b726.png)

**Comment by bigint** [comment]
Should be fixed!!
