### ISSUE TITLE
Can't interact with platform for free

### ISSUE THREAD

**Issue by OptimisticRep** [lensterxyz/lenster#2794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi. I can't collect, comment, or react to posts for the second week in a row. Also can't write posts in the feed - every interaction with lenster requires payment of a commission. Is this even legal?

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome

### Anything else?

![Безымянный](https://user-images.githubusercontent.com/122284833/236118463-40db8064-edd6-4593-a258-def4b33e2dbb.jpg)

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
