### ISSUE TITLE
On-chain comment on a data availability publication is not allowed

### ISSUE THREAD

**Issue by LHY-sudo** [lensterxyz/lenster#2798]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This issue occurs when mirror or comments

### Steps To Reproduce

This issue occurs when I comment on voting posts

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![微信截图_20230504221133](https://user-images.githubusercontent.com/63576758/236233905-f29be65c-3c8f-4c90-8a45-65cdbca79e95.png)

**Comment by bigint** [comment]
Fixed
