### ISSUE TITLE
Error Uploading Image on Lenster

### ISSUE THREAD

**Issue by raphaelbperez** [lensterxyz/lenster#2803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying to upload any media file (Image, Audio or Video) in a publication from my Lenster account, I am getting the following error "Something went wrong while uploading".

### Expected Behavior

I've done other publications with media files in Lenster and they worked before.

### Steps To Reproduce

![Error lenster](https://user-images.githubusercontent.com/129208717/236369284-f37e843f-9fda-412a-b22e-8f40614d8009.png)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![Error lenster](https://user-images.githubusercontent.com/129208717/236369205-8ed8f871-469a-492f-8914-f85a666f3e6f.png)

**Comment by bigint** [comment]
Fixed
