### ISSUE TITLE
Unable to Sign in DMs using WalletConnect v2

### ISSUE THREAD

**Issue by petermdenton** [lensterxyz/lenster#2810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I sign in to Lenster via Walletconnect v2, I am not able to access DMs.

- I get no issue in Loging in to Lens. I see a signature on Rainbow and am able to sign the message
- I also get a second signing prompt, on Step 2 of "Sign in with Lens", which appears on Rainbow.
- When I go to DMs, I get no signature prompt. Messages tab then sits with loading spinner idefnitely.

<img width="1250" alt="image" src="https://user-images.githubusercontent.com/4683293/236554469-dc70f8c1-705b-4543-adfe-ccbd12a29167.png">

### Expected Behavior

Typically, when I got to DMs, I see an additional signature to sign with XMTP, and then see my messages.

### Steps To Reproduce

- Sign out of Lens
- Sign back in using Walletconnect v2
- After the two signature steps, visit the messages tab
- You will not see a signature prompt for XMTP and messages tab will be empty.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

One suggestion might be to use Thirdweb SDK here: https://thirdweb.com/wallet-sdk

**Comment by bigint** [comment]
Fixed
