### ISSUE TITLE
lens profile not working

### ISSUE THREAD

**Issue by mirbilal** [lensterxyz/lenster#2811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

my lens profile is restricted and i cannot post,comment or share my thoughts on lens ecosystem without paying fee

### Expected Behavior

it should have been free the old way

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Chrome

**Comment by mirbilal** [comment]
no

**Comment by mirbilal** [comment]
lens profile id ...boyi6888.lens

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
