### ISSUE TITLE
Extend login session duration to improve user experience

### ISSUE THREAD

**Issue by samuveth** [lensterxyz/lenster#2829]
### Description
As a user of the Lenster website, I am experiencing an issue where I have to log in again after a day of not using the site. While the website does remember the user's login status when closing the browser or navigating away, the current session duration is too short. This is inconvenient and time-consuming, as the login process takes multiple steps and a significant amount of time to complete. To improve the user experience, the website should extend the login session duration before requiring the user to log in again.

### Steps to reproduce
1. Open the Lenster website in a browser.
2. Log in with your credentials.
3. Do not use the website for a day.
4. Open the Lenster website again.

### Expected behavior
The website should remember the user's login status for a longer period of time (e.g., 7 days) before requiring them to log in again.

### Actual behavior
The website requires the user to log in again after a day of not using it.

### Possible solution
Extend the login session duration by adjusting the session expiration time or using a persistent login method, such as cookies or local storage, with an extended expiration time. This would significantly improve the user experience by reducing the frequency of logins required.

**Comment by bigint** [comment]
Dupe or https://github.com/lensterxyz/lenster/issues/1795
