### ISSUE TITLE
My GIF artwork keeps getting nerfed... please help <3

### ISSUE THREAD

**Issue by SO-JU** [lensterxyz/lenster#2836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Each time I try to upload my GIF it does not display properly on Lenster. If the image is clicked, it can be seen - but the post itself shoes a blank greyed-out box or a random icon. The file is only 3MB and I've tried uploading smaller versions (dimensions too) with no luck. 

I'm hesitant to try again because I really don't want to have to refund collectors again because of a bugged post. Any chance you frens can help me out? 

I'm assuming it looks like this on all browsers because other's have told me it also looks strange on their end. 

### Expected Behavior

I expected my gif to display properly in a post

### Steps To Reproduce

![aa1](https://user-images.githubusercontent.com/118639656/236962692-4768ecac-94a4-4a8d-8cac-2e25f390d908.gif)

this is the exact file I've been trying to include in my post. 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

<img width="687" alt="Screen Shot 2023-05-06 at 11 15 15 AM" src="https://user-images.githubusercontent.com/118639656/236962409-5b003e06-a4dd-40e0-b51e-e43836a29c3a.png">

![Screen_Shot_2023-05-04_at_9 09 28_PM](https://user-images.githubusercontent.com/118639656/236962526-6b8c8dd8-3e35-4971-9d9d-b10bcbc81e23.png)

**Comment by SO-JU** [comment]
(also this is my original artwork so plz nobody take my file <3)

**Comment by bigint** [comment]
Will be fixed on next release

**Comment by SO-JU** [comment]
> 

Hi fren! I just want to say that I tested things and you guys did a great job fixing it, thank you for your work! 💜🌿
