### ISSUE TITLE
My handle can not be found in search bar

### ISSUE THREAD

**Issue by ajkol** [lensterxyz/lenster#2854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My handle does not return result when I or other people search it on Lenster

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![344](https://github.com/lensterxyz/lenster/assets/105176707/04160b85-048b-4930-a165-5d121f1861d4)

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
