### ISSUE TITLE
Posts don't load

### ISSUE THREAD

**Issue by denis-skripnik** [lensterxyz/lenster#2940]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. I go to profiles - there are no posts.
2. I go to "Explore" - too.
Cookies reset, updated via CTRL +f5 - does not help... I don't want to change the browser, especially since everything worked fine before.
I provide screenshots.

### Expected Behavior

Posts. Right now, just the filtering buttons and that's it: then the lower part of the site...
![atom_DBgql2zvhr](https://github.com/lensterxyz/lenster/assets/13224778/406d4f36-d804-4f82-bc7a-2445cc5d74c2)
![atom_7TkpvpXAhW](https://github.com/lensterxyz/lenster/assets/13224778/1625f0a9-c46a-4eb0-9c75-befcd86a56c2)

### Steps To Reproduce

1. Logged in.
2. Logged in by signing the message.
3. Trying to see posts by clicking on buttons - nothing.
4. I refresh the page - there are no changes.
5. I went to the developer console - there seem to be no errors...

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Others

### Anything else?

Atom browser, but I think there is no difference: it is based on Chrome.

**Comment by bigint** [comment]
But in your screenshot i see posts on profile page

**Comment by denis-skripnik** [comment]
Hello. It turned out that the reason was different. I described it in the post https://lenster.xyz/posts/0xa9fb-0x34-DA-23a35fd8
