### ISSUE TITLE
Optimistically send messages

### ISSUE THREAD

**Issue by elisealix22** [lensterxyz/lenster#2944]
### Summary

Right now when sending attachments thru messages, it takes a while to send which blocks the UI. It would be great if we can add optimistic sending and then handle the error case if it fails (maybe adding an error icon that says failed to send when hovering?).

Use case:
- Send an attachment and immediately unblock input/send button UI to allow sending another message
- Cached attachment should show in the messages list while sending
- If the attachment succeeds to send, do nothing.
- If the attachment fails to send, indicate the failure in the message list.
- Allow multiple in-progress messages by sending an attachment and then immediately sending another

**Comment by bigint** [comment]
Great one to have 🙇🏼
