### ISSUE TITLE
Cache time of PFPs is to long

### ISSUE THREAD

**Issue by DanIsNearby** [lensterxyz/lenster#2956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

PFP from 2 weeks ago of user is displayed next to the content

![image](https://github.com/lensterxyz/lenster/assets/91475837/47ac6c27-299b-49c0-929c-0166733ec7d4)

### Expected Behavior

Users PFP is displayed next to content

![image](https://github.com/lensterxyz/lenster/assets/91475837/41ffc57a-0226-4b6f-b037-48003d71606c)

### Steps To Reproduce

Copy link of ChaoticMonk post (only text) and post in Discord / telegram 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Fixed
