### ISSUE TITLE
4everland.io displayed as dangerous by Chrome

### ISSUE THREAD

**Issue by DanIsNearby** [lensterxyz/lenster#2957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

A warning popup pops up and makes it impossible for the app usage

### Expected Behavior

Nothing pops up 

### Steps To Reproduce

Open chrome with security rules on 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![image](https://github.com/lensterxyz/lenster/assets/91475837/9bab3cba-4013-42b1-bf59-2ef5fec539ae)

**Comment by foolo** [comment]
@DanIsNearby What specific setting you are referring to by "with security rules on"?

**Comment by DanIsNearby** [comment]
It is refering to Meduim and Highest secuiry rules in chrome

**Comment by foolo** [comment]
@DanIsNearby Assuming you mean _Enhanced protection_ in chrome://settings/security , I tried it but can not reproduce it, so any additional info is appreciated.

**Comment by DanIsNearby** [comment]
Can't give any more info but the error has stoped for me so ig it was an temporarry flag issue or something

**Comment by foolo** [comment]
> Can't give any more info but the error has stoped for me so ig it was an temporarry flag issue or something

@DanIsNearby Cool, thanks for checking 👍
