### ISSUE TITLE
cant post

### ISSUE THREAD

**Issue by w18529** [lensterxyz/lenster#2961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I clicked the post button when I posted my post, it didn't respond

### Expected Behavior

work 

### Steps To Reproduce

![Screenshot_2023-05-28-02-25-15-741_com android chrome](https://github.com/lensterxyz/lenster/assets/129160254/2e866cd0-5027-41c8-a9d4-4348d26100d6)

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Chrome

### Anything else?

it is a bug

**Comment by bigint** [comment]
Should be fixed
