### ISSUE TITLE
LensKit is still in zero......

### ISSUE THREAD

**Issue by AprendizCripto** [lensterxyz/lenster#2989]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have some problems with my Lenskit.....the tasks are being done.....some end up being computed by LensGarden.....but the Lenskit is still reset..can you help me please? For example, I already collected some items that I found very relevant, I published them and nothing appears.....thank you very much....my intention really is to help.....

### Expected Behavior

I expected that as I carried out the activities it would be synchronized, I'm loving the platform, I'm finding it really cool

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

[lenskit.docx](https://github.com/lensterxyz/lenster/files/11626685/lenskit.docx)
[lensgarden.docx](https://github.com/lensterxyz/lenster/files/11626708/lensgarden.docx)

**Comment by bigint** [comment]
Please raise with lenskit team
