### ISSUE TITLE
WalletConnect login does not work

### ISSUE THREAD

**Issue by miohtama** [lensterxyz/lenster#3024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I cannot login to Lenster.xyz using WalletConnect

I tried

- MetaMask on Mobile
- TrustWallet

Then I tried 

- Desktop Firefox browser
- Chrome on Android

The result:

- There is no clear error message what's wrong
- MetaMask does not get any notification or sign requests
- TrustWallet gives "Unknown error"

I can connect the same Lens account on Phaver.

### Expected Behavior

- I can log in to Lenster with two of the most popular wallets
- I get an meaningful error message if wallets are somehow not compatible

### Steps To Reproduce

- Go to lenster.xyz mobile browser
- Choose login
- Choose WalletConnect
- Choose MetaMask or Android app on Android selector
 

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Chrome

### Anything else?

Cannot take a screenshot because the wallet app security settings

**Comment by bigint** [comment]
Fixed
