### ISSUE TITLE
Search dropdown in new message modal is transparent

### ISSUE THREAD

**Issue by FindThirteen** [lensterxyz/lenster#3028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/lensterxyz/lenster/assets/4407931/417b3534-0474-41d7-b30e-1dea7a427b37)

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

bug

**Comment by amareshsm** [comment]
@bigint I want to work on this issue can I pick this?
