### ISSUE TITLE
ENS names are not loaded in DMs when we are in `All` tab

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#3031]
<img width="448" alt="image" src="https://github.com/lensterxyz/lenster/assets/69431456/e896c83c-707c-4245-8616-b8e8ff0e1707">

**Comment by Kiranism** [comment]
hey is this still open? i fixed them already, please check

**Comment by foolo** [comment]
For me, ENS names is the only thing that's loaded:
![Screenshot_2023-08-30_19-27-51](https://github.com/lensterxyz/lenster/assets/667227/7714e7cf-7902-4306-be40-1406407f7713)

The problem seems to be that profile names are not loaded, for profiles which has no ENS address.
