### ISSUE TITLE
Height of left and right section is not equal in DMs

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#3033]
<img width="1326" alt="image" src="https://github.com/lensterxyz/lenster/assets/69431456/8a45985a-b10b-4e41-ac38-b2234827082e">

**Comment by amareshsm** [comment]
This is Boz for the right section child element fixed height (87vh) is given. 
![image](https://github.com/lensterxyz/lenster/assets/30730124/a636a16a-c836-48df-a121-de7a1d039267)


For the left one, it is given as 80vh
![image](https://github.com/lensterxyz/lenster/assets/30730124/56281108-2f2c-4f89-82a1-c1211211facc)


Can I pick and try to fix this?
