### ISSUE TITLE
the user is unable to comment on any post using lenster, my lens profile is @flyertsa

### ISSUE THREAD

**Issue by dahiya220** [lensterxyz/lenster#3062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

the user is unable to comment on any post using lenster, my lens profile is @flyertsa

### Expected Behavior

the user is unable to comment on any post using lenster, my lens profile is @flyertsa

### Steps To Reproduce

the user is unable to comment on any post using lenster, my lens profile is @flyertsa

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome, Safari

### Anything else?

please resolve this issue ASAP

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
