### ISSUE TITLE
Limit bio length in settings also truncate in view to not break the UI

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#3080]

**Comment by foolo** [comment]
Seems to be limited to 260 in settings already:
![Screenshot_2023-06-11_17-34-18](https://github.com/lensterxyz/lenster/assets/667227/229d35b4-ee88-4b53-9cc4-aee2205934c3)

User preview becomes a bit too large when the bio is long, I guess that this one should be truncaded?
![Screenshot_2023-06-11_17-32-07](https://github.com/lensterxyz/lenster/assets/667227/f659cc06-b4e7-4d03-bdc5-4b80cba87748)


But the profile page looks quite OK imo:
![Screenshot_2023-06-11_17-31-24](https://github.com/lensterxyz/lenster/assets/667227/abfcef85-8be5-473e-88f4-5850081a0dae)

**Comment by foolo** [comment]
@bigint Seems like it's already truncated in settings (see previous post). But the User Preview  might need truncating, correct?
BTW, unrelated: I wrote to you on Discord 🙂 , have a look.
