### ISSUE TITLE
Fix oembed image height and width and follow aspect ratio

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#3084]

**Comment by foolo** [comment]
Suggestion:
- if the original image is very wide or very tall, then crop it, (for example, if wider than 2:1 or taller than 2:3)
- else, display the image preview with the same aspect ratio as the original image

**Comment by foolo** [comment]
https://lenster.xyz/posts/0x01ce77-0x17
vs twitter:
![Screenshot_2023-09-11_at_9 09 14_PM](https://github.com/lensterxyz/lenster/assets/667227/49e9ef8b-a95a-41de-987b-5811c2ff940c)
