### ISSUE TITLE
Wallet connexion Taho / Metamask bug 

### ISSUE THREAD

**Issue by tochiro92** [lensterxyz/lenster#3090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, there is a conflict between Taho and metamask wallet. When you want to connect to Lenster, Taho has priority. You have to disable Taho in the extensions to be able to use metamask.

### Expected Behavior

Open direct metamatsk or multi choice wallet connexion 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by enzi00965220** [comment]
...
