### ISSUE TITLE
GIF [<10MB] not loading on Lenster

### ISSUE THREAD

**Issue by BasNFTz** [lensterxyz/lenster#3097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

GIF below 10 MB doesnt load.
https://lenster.xyz/posts/0x01b2e3-0x67

### Expected Behavior

GIF should load. It loads on other sites.

### Steps To Reproduce

Upload a GIF below 10 MB. it looks like it loads but then the picture remains blank. If you click it you see it load.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![Screenshot (11)](https://github.com/lensterxyz/lenster/assets/114669007/d7d04cef-99a3-4c29-9735-b764375d004c)

**Comment by bigint** [comment]
Should be fixed
