### ISSUE TITLE
Lens Profile

### ISSUE THREAD

**Issue by Josefverma** [lensterxyz/lenster#3117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not able to do comments on someone's post and restricted on phaver

### Expected Behavior

Unrestricted lens profile on phaver, orb and other apps.
And on lenster i want to use all features on there.

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Others

### Anything else?

![Screenshot_20230616-122959](https://github.com/lensterxyz/lenster/assets/88319935/9bcda61c-8a7d-4308-a97d-aa9daab0ecaa)
![Screenshot_20230616-122152](https://github.com/lensterxyz/lenster/assets/88319935/0c46617e-84fc-41ae-97aa-e8318c675ba6)

**Comment by Josefverma** [comment]
devponga.lens

My profile

**Comment by admiin** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> Not able to do comments on someone's post and restricted on phaver
> 
> ### Expected Behavior
> Unrestricted lens profile on phaver, orb and other apps. And on lenster i want to use all features on there.
> 
> ### Steps To Reproduce
> _No response_
> 
> ### What platform(s) does this occur on?
> Web, Mobile
> 
> ### What browser(s) does this occur on?
> Others
> 
> ### Anything else?
> ![Screenshot_20230616-122959](https://user-images.githubusercontent.com/88319935/246341687-9bcda61c-8a7d-4308-a97d-aa9daab0ecaa.png) ![Screenshot_20230616-122152](https://user-images.githubusercontent.com/88319935/246341709-0c46617e-84fc-41ae-97aa-e8318c675ba6.png)

Same issue with my lens profile, I'm a content creator and it's been about 2 months that I'm not able to use gasless txns

my handle :
https://lenster.xyz/kamil.lens

tried filling up the forms and talking to admins on lens.xyz and still haven't got the satisfying answer, I like lens protocol and I loved what I was doing, but because of some interactions I got bot flagged, please unflag me so I can still make content for my fellow lens followers

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
