### ISSUE TITLE
Quote post

### ISSUE THREAD

**Issue by Jason537** [lensterxyz/lenster#3152]
### Summary

When quoting a post, the author of the original post can’t see the relevant reference record in the comment area, which seems unreasonable, and the record of the quoted post should be displayed
![1687418093831](https://github.com/lensterxyz/lenster/assets/75970087/e1ae92e1-2b53-4453-8c42-f5fe29bf2681)

**Comment by bigint** [comment]
I can't repro this issue, please come with more details 🙇🏼
