### ISSUE TITLE
Race Condition on the Lineaster Platform

### ISSUE THREAD

**Issue by GAMBRUSH** [lensterxyz/lenster#3160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I would like to report a bug that I have discovered within the Lineaster platform. I have identified a race condition that can affect the stability and consistency of the application.

### Expected Behavior

Identifying and resolving the race condition will help improve the platform's stability and reliability, as well as prevent potential bugs or system failures in the future.

### Steps To Reproduce

During the process of liking posts with a series of simultaneous or sequential operations, I noticed that some processes can interfere with each other. This results in a large number of likes being added by a single user. I have conducted tests by following the steps that trigger this condition, and I have successfully reproduced the issue multiple times.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

Post link : https://lineaster.goerli.linea.build/posts/0x0405a5-0x01
Screenshot : 
![lineaster_racecondition](https://github.com/lensterxyz/lenster/assets/47976675/91f390a4-3233-4480-839d-a6981e31ba38)
![lineaster_racecondition(1)](https://github.com/lensterxyz/lenster/assets/47976675/ccab6116-042e-4a4b-b99d-d17e61bff439)

**Comment by bigint** [comment]
Add a reaction to a publication, please note if you pass in another reaction it will toggle it. What I mean by that is if you UPVOTE it then DOWNVOTE it the server will swap the UPVOTE to the DOWNVOTE.
