### ISSUE TITLE
Gasless transactions

### ISSUE THREAD

**Issue by admiin** [lensterxyz/lenster#3176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not able to do comment/collect/mirror on someone's post and restricted on lenster and other lens protocol platforms

### Expected Behavior

gasless transactions 

### Steps To Reproduce

due to some active days and having a little more interaction with my followers I got bot flagged and now I've learned the lesson, I still would like to create content and keep my profile active

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Safari

### Anything else?

I'm a content creator and it's been about 2 months that I'm not able to use gasless transactions

my handle :
https://lenster.xyz/kamil.lens

tried filling up the forms and talking to admins on lens.xyz and still haven't got the satisfying answer, I like lens protocol and I loved what I was doing, but because of some interactions I got bot flagged, please unflag me so I can still make content for my fellow lens followers

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
