### ISSUE TITLE
Disable Signless Transactions doesn't work

### ISSUE THREAD

**Issue by gitey** [lensterxyz/lenster#3191]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i enabled signless transaction but it doesn't work.Every transaction(post,mirror,collect)without like it wants confirn in wallet

### Expected Behavior

when i enabled signless transaction it must be work

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Edge

**Comment by bigint** [comment]
Are you getting any errors?

**Comment by gitey** [comment]
on lenster every time i want to mirror or collect the post it comes my metamask approve sign message although i selected the signless transactions

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
