### ISSUE TITLE
Profile hacked

### ISSUE THREAD

**Issue by tofiquedurrani** [lensterxyz/lenster#3199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My profile has been hacked can i recover it

### What platform(s) does this occur on?

Mobile

### What browser(s) does this occur on?

Brave

### Anything else?

Please help

**Comment by tofiquedurrani** [comment]
My lens profile 668800.lens

My email

tofiquedurrani9@gmail.com

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!

**Comment by Khawar110** [comment]
Greatest project
