### ISSUE TITLE
[ENG-24] Issues with page load/crashing

### ISSUE THREAD

**Issue by daria-github** [lensterxyz/lenster#3227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When loading my Lenster page, I am now experiencing slow load times and frequent crashes. My account now has many images, and I believe it is likely due to that as this wasn't happening previously. When it does load, I get the issue upon clicking into a single conversation.
<img width="1524" alt="Screenshot 2023-07-10 at 2 06 07 PM" src="https://github.com/lensterxyz/lenster/assets/35409260/47b81dd7-b00b-431c-a746-da4aa461226e">

### Expected Behavior

Typical page loading experience without crashing.

### Steps To Reproduce

Load page, if that seems normal try toggling between several conversations and you'll likely experience a freeze.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

<sub>[ENG-24](https://linear.app/heyxyz/issue/ENG-24/issues-with-page-loadcrashing)</sub>

**Comment by bigint** [comment]
Yup we got lot of reports on this, any ideas why its happening?

**Comment by bigint** [comment]
Fixed
