### ISSUE TITLE
Use cmdk for menu

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#328]

**Comment by AdamSchinzel** [comment]
What you think (https://github.com/AdamSchinzel/lenster/commit/f6e536e47f21ebde3bb50f961cb8fe0a39f27061)

https://www.loom.com/share/1459ea3f2b9c440ba9b78ec953c3593f

**Comment by bigint** [comment]
We came to the decision that this will be overkill 🙏🏼 

So closing now!!!
