### ISSUE TITLE
Collected Section doesn't work correct!!!

### ISSUE THREAD

**Issue by hassansazgar** [lensterxyz/lenster#3355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://lenster.xyz/u/1_modifan
 this is my lens account but unfortunately, while I collect some posts we didn't see any changes in my acoount's and lens scan

### Expected Behavior

https://lenster.xyz/u/1_modifan
 this is my lens account but unfortunately, while I collect some posts we didn't see any changes in my acoount's and lens scan

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

https://lenster.xyz/u/1_modifan
 this is my lens account but unfortunately, while I collect some posts we didn't see any changes in my acoount's and lens scan

**Comment by bigint** [comment]
I can see there are posts in collected list
