### ISSUE TITLE
Profile NFTs link is flagged as dangerous by browser

### ISSUE THREAD

**Issue by Pfed-prog** [lensterxyz/lenster#3367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Profile NFTs link is flagged as dangerous by browser

### Expected Behavior

Click link -> show page

### Steps To Reproduce

Follow your personal link similar to
https://lenster.xyz/u/pfed_prog?type=nft

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

### Anything else?

![image](https://github.com/lensterxyz/lenster/assets/66903336/e1000fad-ebfe-4d01-941b-b2f0fc215c08)

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
