### ISSUE TITLE
Profile Page NFTs are displayed twice

### ISSUE THREAD

**Issue by Pfed-prog** [lensterxyz/lenster#3368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Follow the profile nft link -> opens nfts, but opens literally all of them including phishing ones and iterates over the same nfts at least twice. I think its an infinite infinite query

### Expected Behavior

Display only nfts with rep similar to rainbow wallet or metamask once

### Steps To Reproduce

follow your profile link similar to https://lenster.xyz/u/pfed_prog?type=nft

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

### Anything else?

![image](https://github.com/lensterxyz/lenster/assets/66903336/6fbcb3d8-b6d3-41b8-91fb-2e5b010f115d)

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
