### ISSUE TITLE
Scam page routing potential cache compromised

### ISSUE THREAD

**Issue by zcstarr** [lensterxyz/lenster#3433]
When clicking the NFTs tab on some profiles, a scam page would appear. It's seems to be related to some cache, maybe something has been compromised with a service. So the original links linked to in the issue no longer have that spurious routing. I'm linking here so someone can look into it. The date in question it was noticed was 7/26/23, so might be good to check logs. 

Here was the example https://lenster.xyz/u/tinyrainboot?type=nft and https://lenster.xyz/u/refraction?type=nft . If it's DNS related I'm based in LA, if it's like a region of a cache is compromised. The browser was chrome, and brave. As DNS can route to different servers based on user-agents, aka firefox never received the cached compromised page.

![image](https://github.com/lensterxyz/lenster/assets/173187/7d33a0d1-d0bf-491e-bcc7-f527e5cfbe45)

An

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!

**Comment by zcstarr** [comment]
@bigint how does one relay this to the backend folks at lens

**Comment by bigint** [comment]
@zcstarr The NFT url is delivered from API right now
