### ISSUE TITLE
Duplicated search result 

### ISSUE THREAD

**Issue by DanIsNearby** [lensterxyz/lenster#3446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Two entities are shown 
<img width="266" alt="image" src="https://github.com/lensterxyz/lenster/assets/91475837/d060d89f-9c56-4b62-83ea-0f55c8954b02">

### Expected Behavior

One entity should be shown

### Steps To Reproduce

Search an user with his exact handle that no one else has a prefix as so for example gotenks.lens 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by foolo** [comment]
For me it seems to work at the moment. See screenshot. I tried with a few different unique usernames too.
@DanIsNearby Does it still happen for you?

![Screenshot_2023-08-16_12-45-52](https://github.com/lensterxyz/lenster/assets/667227/9448bafa-010b-445f-9ad0-166858145493)

**Comment by DanIsNearby** [comment]
Cant replicate it anymore
