### ISSUE TITLE
Fix click area of invite menu in dropdown

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#3461]
https://github.com/lensterxyz/lenster/assets/69431456/af52bf8d-b2c6-4265-afa9-5e7bc3431335

**Comment by TheNatkat** [comment]
hey if this issue is not resolved i want to work on it

**Comment by bigint** [comment]
Hey @TheNatkat feel free to pick and create a PR 🚀

**Comment by TheNatkat** [comment]
hey @bigint,
I started working on the issue but to do that I have to log in but on Lens protocol it shows me in waitlist, or is there any way to bypass the login in my localhost.
thanks for the help

**Comment by amareshsm** [comment]
Fixed & I have raised PR for this.
