### ISSUE TITLE
Fix code scanning alert - DOM text reinterpreted as HTML

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#348]
Tracking issue for:
- [ ] https://github.com/lensterxyz/lenster/security/code-scanning/7

**Comment by foolo** [comment]
Seems like code scanner is inactive, so the above link doesn't work, but the same error can be found here: https://github.com/foolo/lenster/security/code-scanning/3

![Screenshot_2022-12-17_12-54-28](https://user-images.githubusercontent.com/667227/208240577-81b718ed-bd6f-47f1-8bf2-613c9b12b6d6.png)

**Comment by bigint** [comment]
Closing this cuz we no longer seeing this 🙇
