### ISSUE TITLE
Issue in showing the status of direct messages

### ISSUE THREAD

**Issue by aligh98** [lensterxyz/lenster#3514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Direct messages that have not been sent are displayed in the list without showing the sending status to the user
The picture below is from the direct message in Lenster and Lensport
![image](https://github.com/lensterxyz/lenster/assets/10244953/be931257-2171-4d7e-9a5d-48b32b58d93a)
![image](https://github.com/lensterxyz/lenster/assets/10244953/57409cf7-38c3-4d50-be28-9cf085f75098)
![image](https://github.com/lensterxyz/lenster/assets/10244953/a00d3a34-52b1-44c8-b1c2-6d1ae73f669d)

In Linster Direct messages that have not been sent are displayed as sent for the user.

![image](https://github.com/lensterxyz/lenster/assets/10244953/5194e93f-17ba-46e8-bdb4-a55ecf379570)

### Expected Behavior

Direct messages that have not actually been sent will be displayed in the list with a specific red/yellow indicator.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
This is intentional to show draft in sidebar as well!
