### ISSUE TITLE
Pushing comment to comments feed has wrong stats

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#3541]
https://user-images.githubusercontent.com/69431456/261037607-b21de840-9a74-49e3-aac8-66e021a1972f.mov

**Comment by foolo** [comment]
@bigint  This may have been solved by #3633 , you could try to reproduce this again. I have not been able to reproduce this.

**Comment by bigint** [comment]
Yes @foolo thanks for fixing this 🚀
