### ISSUE TITLE
Mixed capitalization

### ISSUE THREAD

**Issue by foolo** [lensterxyz/lenster#3555]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Menus and titles are using a mix of "Text With Every Word Capitalized" and "Text with just the first word capitalized"
Should probably decide on a common style.

Examples:

![Screenshot_2023-08-17_09-39-40](https://github.com/lensterxyz/lenster/assets/667227/1b14f3e2-d93f-4a23-8790-58574a6db715)
![Screenshot_2023-08-17_09-48-49](https://github.com/lensterxyz/lenster/assets/667227/dc30cd38-2a18-4ce9-ba6f-4c0510ad13b0)

### Expected Behavior

Titles, menu, etc. should follow the same capitalization style

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
do you want to work on this?

**Comment by foolo** [comment]
> do you want to work on this?

@bigint Sure, I can do this one. I'll go with just the first word capitalized unless you say otherwise.
