### ISSUE TITLE
Incorrect size plus scrollbars on some NFTs

### ISSUE THREAD

**Issue by foolo** [lensterxyz/lenster#3556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Image is shown too small, with scrollbars
![Screenshot_2023-08-17_09-55-58](https://github.com/lensterxyz/lenster/assets/667227/8dc79b57-5b52-4df8-83e7-0a1415a415c9)

### Expected Behavior

Should show correct image size without scrollbars

### Steps To Reproduce

Happens for some profiles' NTF list, for example https://lenster.xyz/u/ryanfox?type=nft

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
@foolo is it still happening?

**Comment by foolo** [comment]
> @foolo is it still happening?

@bigint I have not seen it with the new curated NFT page design.
So if the old page design is not used anymore, we can close this.

With the new design, i mean this:
![Screenshot_2023-09-06_08-25-23](https://github.com/lensterxyz/lenster/assets/667227/911dd8b0-b652-4250-a466-b75630e4f0b4)
