### ISSUE TITLE
Settings icon don't have enough space aka margin on right side

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#3583]
![image](https://github.com/lensterxyz/lenster/assets/69431456/1d5ffa95-c910-492f-bfef-7a2762487d41)

**Comment by foolo** [comment]
On some devices it even wraps to the next line:
![Screenshot_2023-08-22_15-24-57](https://github.com/lensterxyz/lenster/assets/667227/e202a0f0-8046-4535-bfbc-7cb297f15efe)
