### ISSUE TITLE
Profile not shown in "Search"

### ISSUE THREAD

**Issue by TechFutureSP** [lensterxyz/lenster#3592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My profile "maticfund.lens" does not appear in the "Search" section of Lenster. I am a supporter of Lenster (my discord is #techfuture). Could you please review the reasoning why it is not shown?
Thank you in advance.

### Expected Behavior

My profile "maticfund.lens" shown in the "Search" section of Lenster

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
