### ISSUE TITLE
[Enhancement] Hide communities from top collected

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#36]

**Comment by andriishupta** [comment]
@bigint 👋 

ready to pick it up

In general, I am a little bit familiar with Lens documentation, but if this issue has something specific for implementation - let me know :)

As I understand, I need to hide those community mentions(the issue name is self-explanatory)
![image](https://user-images.githubusercontent.com/10981565/183609031-d013b3d9-fb9b-4d9c-a123-fa1c1080b37d.png)

**Comment by bigint** [comment]
Exactly we need to hide all those community launches from the Top collected section 🙇🏼

**Comment by andriishupta** [comment]
cool, so I would start and come back with PR when I would have something - should be today 📆

**Comment by andriishupta** [comment]
@bigint, please, check PR #344 

*copying what I did in PR here as a message* 

followed API and added `sources` TOP_COLLECTED Feed
https://docs.lens.xyz/docs/explore-publications#request

as side changes:
- I added .gitignore for my IDE
- I fixed the startup issue with mixpanel.ts
- I added `lensterCommunity` app to keep reference that it exists

**Comment by andriishupta** [comment]
Also, tested - works as expected:
- go to Explore -> default Top Commented -> with communities and no `sources` in the payload
- go to Top Collected -> NO communities, and there are `sources` in the payload
- go back to Top Commented -> cached results
- scroll down - new query without `sources` for Top Commented with communities in results

**Comment by bigint** [comment]
Communities are no more 👋🏼
