### ISSUE TITLE
Free collect post asking me for gas fees

### ISSUE THREAD

**Issue by innsbruckz** [lensterxyz/lenster#3625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Free collect post asking me for gas fees

### Expected Behavior

Free collect posts are not supposed to asking transaction fees.

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

### Anything else?

![46y22](https://github.com/lensterxyz/lenster/assets/134666465/6b9ec6db-152c-4af1-ba3f-5d0ef1fca30b)

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
