### ISSUE TITLE
Doesn't render twitter thread-like comments properly

### ISSUE THREAD

**Issue by h4x3rotab** [lensterxyz/lenster#3639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is an example: https://lenster.xyz/u/h4x3rotab.lens?type=replies

I have written a thread with a chain of comments. When checking the comment list in my profile, it render a lot of duplicated comments.

Also, if open a comment page, it cannot detect the thread and automatically show all of them like twitter. I need to follow the comments one by one to see all of them. If I open any comments after the 3rd one, it will skip the earlier comments, only shows the original post and the last two comments.

### Expected Behavior

Twitter like thread rendering.

### Steps To Reproduce

First problem - duplicated comments in the replies page: https://lenster.xyz/u/h4x3rotab.lens?type=replies

Second problem - skipped comments: https://lenster.xyz/posts/0x82a0-0x0e-DA-64e85e97

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
