### ISSUE TITLE
Git POAP intro to this repo

### ISSUE THREAD

**Issue by lucasverra** [lensterxyz/lenster#374]
### Summary

Since the lens protocol is so fan of POAP it could be a good idea to install GitPOAP! 
form here: https://www.gitpoap.io/#suggest

> Recognize, nurture, and grow your community of contributors through the distribution of GitPOAPs & help them build an unbiased record of their work.

**Comment by bigint** [comment]
Thanks! Done submitted 🚀🤞🏼

**Comment by lucasverra** [comment]
That is fast! 🚝

**Comment by bigint** [comment]
We are now in GitPOAP 🚀
