### ISSUE TITLE
Nfts are duplicating on "Pick nft as profile picture" scrolling

### ISSUE THREAD

**Issue by DanIsNearby** [lensterxyz/lenster#3746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When scrolling trought the NFTs list some of them are getting duplicated 

### Expected Behavior

List goes on and then ends without any duplicates in middle

### Steps To Reproduce

Go to https://lenster.xyz/settings pick nft as profile picture and scroll 

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
Hi 👋

Thank you for bringing this to our attention. It seems that the issue you've reported is related to the backend, and as a frontend team, we don't have direct access to the backend codebase or infrastructure. Therefore, we won't be able to address this issue in the frontend repository.

For this reason, we will be closing this issue.

Please don't hesitate to reach out if you have any other questions or concerns related to the frontend. We appreciate your understanding and contribution!
