### ISSUE TITLE
Add post tagging feature

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#397]

**Comment by DanIsNearby** [comment]
# are tags on top of Lens Protocol imo it makes no sense to add a future that already exists would be cool to utalize the current way it is working 

Here for example was used tag LensAcademy becouse it was also used as # in the post

https://arweave.app/tx/4b3yqBBDYJtGZDMxM-WM_xB6UsmVycM3j1sY_x-GMrI

**Comment by bigint** [comment]
Shipped
