### ISSUE TITLE
Add bottom nav in mobile

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#43]

**Comment by ercwangwh** [comment]
Hi, @bigint . I've designed the bottom nav for mobile below, includes Home/Explore/Msg/Notification from left to right. Let me know what you think. :)
<img width="318" alt="image" src="https://user-images.githubusercontent.com/45984686/200510467-a82054b7-36ed-4521-8b02-390b3959b2ff.png">

**Comment by bigint** [comment]
@ercwangwh feel free to create a PR for this 🙏🏼

**Comment by bigint** [comment]
Done
