### ISSUE TITLE
Replace emojis with twemojis

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#45]

**Comment by IgnisDa** [comment]
@bigint What exactly are the requirements here? How many emojis should be supported? Should they be inline or use an `img` or `svg` element to render the emoji?

**Comment by bigint** [comment]
@IgnisDa, we don't want to display native emojis across the platform. Instead we should display twemoji so it will be standard on multiple devices and OS

Twitter uses this; you can check them.

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/69431456/208368826-427f40b0-a5bc-4ad1-b8eb-2114e971b6e4.png">

**Comment by IgnisDa** [comment]
Twitter does not replace the `:)`, `<3` automatically. Instead it supports an emoji picker. This is also possible with the lexical editor. You can test it in the [playground](https://playground.lexical.dev/) by typing in a `:` character. 

Will that be a more better UX?

**Comment by bigint** [comment]
@IgnisDa we already have that in lenster 🙇🏼 but this issue is not related to that, this is to render the emojis as twemojis in the platform.

**Comment by bigint** [comment]
Emoji popup is a separate feature 🙏🏼

**Comment by foolo** [comment]
Some observations:
Need to parse emojis in output translation methods <Trans> and t()
Need to parse users' posts, comments, etc before displaying them. Probably should  be done by adding a matcher in Markup.tsx.
Need to wrap normal react components.
There are some problems with hosting at the moment: https://github.com/twitter/twemoji/issues/580
