### ISSUE TITLE
bug: cannot collect or disable dispatcher after enabling

### ISSUE THREAD

**Issue by andriishupta** [lensterxyz/lenster#508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After you set up the dispatcher, you cannot collect posts nor disable the dispatcher.
Page reload is not helping.
Only after full logout-login it works

### Expected Behavior

No errors should be preset for post collection

### Steps To Reproduce

- Enable dispatcher
- try to collect posts - "Connector not found" error
- try to disable it - "Connector not found" error
- logout/login
- try again - works

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

### Anything else?

Unusual:
- I was on a fresh browser and just added Polygon as a chain
- I switched from Etherium

But after re-open the browser - I still see the error.

API seems to return correct data

I see a few errors, but even before the button click - there are NO errors during a button press.

<img width="904" alt="image" src="https://user-images.githubusercontent.com/10981565/185896678-3bab9724-9fdb-47d3-a36c-30c75fe14b83.png">

![image](https://user-images.githubusercontent.com/10981565/185896777-a5f3d3cd-56c2-48bb-8519-7d0f1469d4a8.png)

![image](https://user-images.githubusercontent.com/10981565/185896836-e36cb6ae-8de6-4e29-a49e-bc7b2800abf1.png)

![image](https://user-images.githubusercontent.com/10981565/185896875-66fb180b-3179-4cb5-aee5-c332a101b134.png)

**Comment by andriishupta** [comment]
@bigint, I think you could close this issue - I am sure that nobody would be able to reproduce it, and I think it could be something with my setup: it looks like metamask bug

I have noticed the same error on different websites, and error leads to the metamask's inpage.js

**Comment by bigint** [comment]
Ohhhhh then we can close it 🙇🏼 

Thanks 🙏🏼
