### ISSUE TITLE
🎨 Lenster redesign

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#539]
```[tasklist]
### Migration Basics
- [ ] https://github.com/lensterxyz/lenster/issues/2897
- [ ] https://github.com/lensterxyz/lenster/issues/2899
- [ ] https://github.com/lensterxyz/lenster/issues/2900
- [ ] https://github.com/lensterxyz/lenster/issues/2901
```

```[tasklist]
### Components
- [ ] https://github.com/lensterxyz/lenster/issues/2902
- [ ] https://github.com/lensterxyz/lenster/issues/2903
- [ ] https://github.com/lensterxyz/lenster/issues/2904
- [ ] https://github.com/lensterxyz/lenster/issues/2930
- [ ] https://github.com/lensterxyz/lenster/issues/2905
- [ ] https://github.com/lensterxyz/lenster/issues/2906
- [ ] https://github.com/lensterxyz/lenster/issues/2907
- [ ] https://github.com/lensterxyz/lenster/issues/2908
- [ ] https://github.com/lensterxyz/lenster/issues/2917
- [ ] https://github.com/lensterxyz/lenster/issues/2931
- [ ] https://github.com/lensterxyz/lenster/issues/2932
- [ ] https://github.com/lensterxyz/lenster/issues/2933
```

```[tasklist]
### Publication Component
- [ ] https://github.com/lensterxyz/lenster/issues/2909
- [ ] https://github.com/lensterxyz/lenster/issues/2910
- [ ] https://github.com/lensterxyz/lenster/issues/2911
```

```[tasklist]
### Layouts
- [ ] https://github.com/lensterxyz/lenster/issues/2912
- [ ] https://github.com/lensterxyz/lenster/issues/2913
- [ ] https://github.com/lensterxyz/lenster/issues/2914
- [ ] https://github.com/lensterxyz/lenster/issues/2915
- [ ] https://github.com/lensterxyz/lenster/issues/2916
- [ ] https://github.com/lensterxyz/lenster/issues/2918
- [ ] https://github.com/lensterxyz/lenster/issues/2919
- [ ] https://github.com/lensterxyz/lenster/issues/2920
```

```[tasklist]
### Search
- [ ] https://github.com/lensterxyz/lenster/issues/2922
```

```[tasklist]
### Discoverability
- [ ] https://github.com/lensterxyz/lenster/issues/2921
```

**Comment by vinliao** [comment]
Figma (or screenshot) required, or just PR?

**Comment by bigint** [comment]
@vinliao we dont have Figma yet, but its good to have 🙇🏼

**Comment by thethemit** [comment]
what do you think, do you agree if the lens adds an auto translate feature on post or comment?

mybe and i think can help for user if problem to meaning someone say post or comment

**Comment by GrgW** [comment]
Just a comment: 

Would be nice if this Discoverability project could split the work into [1] spec'ing out an interface and [2] providing an (initial) implementation. This would lay some groundwork for Lens client apps to support pluggable modules. It doesen't matter if the interface [1] still moves around a bit, objective it to set a precedent. 

Lenster could then move towards supporting an ecosystem of modules from which users can self-assemble these components e.g. feed that excludes 'gm' posts, a feed that uses AI to exclude repetitive GIFs posts, recommend users that comment more than they post,....

**Comment by vinliao** [comment]
Agree with @GrgW on separating design spec (Figma, or at least screenshot) with implementation. I've seen front-end projects where randos create a PR with bad design and the the maintainer merged it because: "Well, this person has worked hard, and rejecting the PR wouldn't be a polite move." I don't think that's a good position to be in.

**Comment by GrgW** [comment]
@vinliao agree re UI design spec. 

Just to clarify - my comment was about splitting the module code i/f and the code implementation of that i/f. This allows for future implementations of that interface to be developed and then integrated into Lenster with minimal effort.

**Comment by elie222** [comment]
> Agree with @GrgW on separating design spec (Figma, or at least screenshot) with implementation. I've seen front-end projects where randos create a PR with bad design and the the maintainer merged it because: "Well, this person has worked hard, and rejecting the PR wouldn't be a polite move." I don't think that's a good position to be in.

Agreed. Would be a lot better to split this task into design and development. They're usually done by two different sets of people.
The design for Lenster looks pretty good already so it should be definitely be approved as a design first, and only passed off to devs after the Figma has been okayed.

**Comment by bigint** [comment]
Agreed @elie222, I'll update the issue description and split both task and have subtasks for it 🙇🏼

**Comment by balocreation** [comment]
@bigint I know this would be so challenging but at the same time, it’s going to be fun to participate. 
Time to give it a shot. ❤️

**Comment by bigint** [comment]
Creating new issue for this
