### ISSUE TITLE
Able to set meta tags for publications

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#540]

**Comment by benbaessler** [comment]
Can elaborate some more on this issue?

**Comment by kaf-lamed-beyt** [comment]
Hi @bigint, I'd love to take this issue. 

I think this is related to setting appropriate metatags. Kindly let me know how this can be addressed if I'm wrong.

**Comment by kaf-lamed-beyt** [comment]
A first look at The index page.

https://github.com/lensterxyz/lenster/blob/413750f024040a5035b7ab7703ae3bc06325dd04/apps/web/src/pages/index.tsx#L1-L3

 I noticed that the `Home` component already has a `<MetaTags />` component that it depends on. 
 
https://github.com/lensterxyz/lenster/blob/413750f024040a5035b7ab7703ae3bc06325dd04/apps/web/src/components/Common/MetaTags.tsx#L10-L47
 
 To fix this issue, would I need to do the same thing for the publications route &mdash; that's if there's a blog somewhere? Once again, I await your feedback @bigint

**Comment by bigint** [comment]
Not picking this for now 🙇 

@kaf-lamed-beyt this is not related to SEO meta tags 🙇  it's all about lens metadata

**Comment by kaf-lamed-beyt** [comment]
Oh, great! 

Thanks for informing me
