### ISSUE TITLE
Special Privacy Notifications options button 

### ISSUE THREAD

**Issue by izkillaz** [lensterxyz/lenster#594]
### Summary

I want this feature to provide anonymity / privacy for likes , upvotes and etc.

**Comment by izkillaz** [comment]
https://github.com/lensterxyz/lenster/issues/594#issue-1360111377

**Comment by bigint** [comment]
This sounds like protocol/api level feature you can move this issue to Lens's repo 🙏🏼 

https://github.com/lens-protocol/api-examples/
