### ISSUE TITLE
Click on tagged/mentioned user in post,  redirects to wrong page

### ISSUE THREAD

**Issue by RamK777-stack** [lensterxyz/lenster#615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://lenster.xyz/posts/0x05-0x0226

![image](https://user-images.githubusercontent.com/69167444/188540269-0124ac6a-5a4a-4468-bdcf-ff5a55b6ba46.png)

Click on mentioned user will redirect to wrong page.

### Expected Behavior

Need to redirect to profile page

### Steps To Reproduce

https://lenster.xyz/posts/0x05-0x0226

1. Click on [allmylovezoe.lens](http://allmylovezoe.lens/) 
2. It will redirect to wrong page

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by bigint** [comment]
It's not a mention @RamK777-stack 🙏🏼 

If you want to mention someone use `@` before here is an example post https://lenster.xyz/posts/0x8e-0xcb
