### ISSUE TITLE
Add support for unknownModules

### ISSUE THREAD

**Issue by 0xjim** [lensterxyz/lenster#656]
### Summary

[re:meme](https://rememe.lol) uses a new module called `UpdatableOwnableFeeCollectModule` [link](https://github.com/lens-protocol/modules/blob/master/contracts/collect/UpdatableOwnableFeeCollectModule.sol)

It's currently supported by the Lens API through the `unknownCollectModule` method

Would be great if Lenster could also support the new module in order to allow memes to be collectable on Lenster

**Comment by bigint** [comment]
Shipped, thanks @arttu0 🚀
