### ISSUE TITLE
Able to translate post

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#71]

**Comment by bigint** [comment]
Example https://twitter.com/DeFi_LATAM/status/1598088684406190080

**Comment by foolo** [comment]
@bigint Just to clarify, is the use case something like below?
- The user sees a post in a foreign language (a different language than user's active UI language).
- Lenster detects that the post is in a foreign language, using a third-party API, such as Google Translate.
- If so, user will see "Translate this post" button, which translates the post via third-party API, into user's active language, and displays it to the user.
- Possible feature: User can select "Never translate from [language x]"

**Comment by danimesq** [comment]
Will users be able to also translate their bios and other contents, as in #1929?

**Comment by bigint** [comment]
@danimesq RN we dont have priority to translate bios, but for other content yes you can toggle your language

<img width="403" alt="Screenshot 2023-03-13 at 10 41 22 AM" src="https://user-images.githubusercontent.com/69431456/224613296-0184a52c-889f-477c-8e92-d6ed0609540d.png">

**Comment by bigint** [comment]
Added translate link for now, this is not an immediate plan!
