### ISSUE TITLE
Add darkmode support for hero section

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#75]

**Comment by andriishupta** [comment]
@bigint I can take it - as I understand I need to update components/Home/Hero.tsx

**Comment by bigint** [comment]
![Screenshot 2022-08-12 at 4 47 47 PM](https://user-images.githubusercontent.com/69431456/184343622-91a85834-3407-4a32-892f-4d7c3e420e84.png)

Yup this one @andriishupta 

Login => Switch to Dark mode => Logout

**Comment by andriishupta** [comment]
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/10981565/184343745-b05ea606-fba7-46ed-8894-80b9ca845734.png">

the idea for possible enhancement - move color theme outside of logged user
automatic theme switch - like twitter and other apps does

**Comment by andriishupta** [comment]
> ![Screenshot 2022-08-12 at 4 47 47 PM](https://user-images.githubusercontent.com/69431456/184343622-91a85834-3407-4a32-892f-4d7c3e420e84.png)
> 
> Yup this one @andriishupta
> 
> Login => Switch to Dark mode => Logout

Cool, thanks! - that's what I thought!
