### ISSUE TITLE
Add virtualized list for the timeline

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#750]
### Summary

Add virtualized list for the timeline

**Comment by simarpreetsingh-019** [comment]
Can you elaborate a bit or give some more info on what to do?

**Comment by bigint** [comment]
@simarpreetsingh-019 https://blog.logrocket.com/rendering-large-lists-with-react-virtualized-82741907a6b3/

**Comment by tienlenan** [comment]
Hello. Where can I find the coding convention or PR rule?

**Comment by tienlenan** [comment]
> Hello. Where can I find the coding convention or PR rule?

Have just checked at https://github.com/lensterxyz/lenster/blob/main/CONTRIBUTING.md

I will try to do this function

**Comment by bigint** [comment]
@tienlenan are you gonna pick this?

**Comment by tienlenan** [comment]
@bigint Have just finished setting up local env and try to investigate the source.

Yes. Im gonna pick this one.

**Comment by bigint** [comment]
Amazing

**Comment by bigint** [comment]
Dupe of [#837](https://github.com/lensterxyz/lenster/issues/837)
