### ISSUE TITLE
Add image cropper

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#76]
ENG-194

**Comment by 0xkeivin** [comment]
hi @bigint , i assume this is for the profile picture under `Upload Avatar` ? 

i.e. 
![image](https://user-images.githubusercontent.com/65915812/196739141-7321019b-d1ae-4780-af44-f9fa63c2826f.png)

**Comment by bigint** [comment]
Yup @0xkeivin

**Comment by Sagargajare** [comment]
@bigint Can I user third-party library for it?

**Comment by bigint** [comment]
Yes @Sagargajare but we need to make sure the bundle size is minimal
