### ISSUE TITLE
Fix post overflow for threads

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#772]
![Image](https://user-images.githubusercontent.com/69431456/187428891-ffb3d66f-441b-4cfd-8016-c22731b96a07.png)

**Comment by 240p60** [comment]
Has this issue been resolved?
Can't find/replicate the same behavior.
Looks like it's already been done

**Comment by foolo** [comment]
Issue link: https://lenster.xyz/posts/0x02-0x06
@bigint Seems like this is working now. Can probably close this.
![Screenshot_2023-01-14_14-30-13](https://user-images.githubusercontent.com/667227/212474273-802c7b0d-701b-4e0c-b433-41c216e6302d.png)
