### ISSUE TITLE
Duplicate profile in profile menu items after login

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#794]

**Comment by foolo** [comment]
I guess that the profile menu is the menu which pops up when you click your profile picture in the top-right corner of the page?
For me, that menu looks OK:
![Screenshot_2022-11-13_08-37-11](https://user-images.githubusercontent.com/667227/201511239-80a88ec6-fdc5-4ae2-8d38-0445bc446415.png)
Any more info on how to reproduce this?

**Comment by foolo** [comment]
I guess that this is referring to that these two links both lead to the same page:
![Screenshot_2022-11-13_08-37-11](https://user-images.githubusercontent.com/667227/201511377-d10d7038-5f0b-4b58-bbeb-fae8aac83d0e.png)
Can we remove the second item ("Your profile"), and assume that it's intuitively enough that the first one ("Logged in as x") takes the user to their profile?

**Comment by bigint** [comment]
Done ✅
