### ISSUE TITLE
Combined feed items

### ISSUE THREAD

**Issue by jounih** [lensterxyz/lenster#799]
Currently there is a lot of repetition on the feed - every time someone you follow comments, collects, mirrors or likes a post, it creates a duplicate item on your feed.

Recent API additions allow us to bundle these into a single item, here's the proposed design:

**Combined comments from people you follow** 

Show the latest one at the bottom, and collapse the rest into "Username and X others commented

![Image](https://user-images.githubusercontent.com/10109867/195398709-095404b7-48af-4519-aa39-455e93f8c56f.png)

**Combined mirrors/collects/reactions from people you follow**

![Image](https://user-images.githubusercontent.com/10109867/195399459-a0bcd643-9b0b-4a84-b64a-7e3ce0690d9b.png)

![Image](https://user-images.githubusercontent.com/10109867/195399500-d7e1463b-997e-4083-92c8-267b6b06d112.png)

![Image](https://user-images.githubusercontent.com/10109867/195399528-612d5fc5-944b-4e0c-ac05-ad8b53743478.png)

When there are multiple combined actions, we can combine them so it doesn't get too verbose:

![Image](https://user-images.githubusercontent.com/10109867/195399683-420c508a-3397-49eb-a608-1e6f46c5a74b.png)

And these actions can also be combined with multiple comments in the same feed item:

![Image](https://user-images.githubusercontent.com/10109867/195399938-bedc7a3d-5939-4028-b686-76a68103862e.png)

**Comment by sasicodes** [comment]
Comments reactions, collects and mirrors

<img width="981" alt="image" src="https://user-images.githubusercontent.com/29498872/195590383-972d057b-f6d1-49cc-8517-e85d71d326bf.png">

**Comment by bigint** [comment]
@sasicodes @jounih it seems like bit complex here, not sure to show actions in thread 🤔 

<img width="257" alt="Screenshot 2022-10-13 at 7 13 49 PM" src="https://user-images.githubusercontent.com/69431456/195613716-3077f382-b6f8-49bb-8682-b81c42853a82.png">

**Comment by jounih** [comment]
> @sasicodes @jounih it seems like bit complex here, not sure to show actions in thread 🤔
> 
> <img alt="Screenshot 2022-10-13 at 7 13 49 PM" width="257" src="https://user-images.githubusercontent.com/69431456/195613716-3077f382-b6f8-49bb-8682-b81c42853a82.png">

yeah we were debating this too... let's leave out @sasicodes @bigint

**Comment by sasicodes** [comment]
https://github.com/lensterxyz/lenster/pull/796

**Comment by sasicodes** [comment]
@jounih @bigint Only thread reaction labelling is pending in this feature.
