### ISSUE TITLE
New "Highlights" tab for the main feed page

### ISSUE THREAD

**Issue by jounih** [lensterxyz/lenster#807]
There will be a new API endpoint that serves the most interacted with top level items from the last 2 days. Let's add a new tab for this on the main feed page

**Comment by bigint** [comment]
@jounih is this the highlights tab one?

**Comment by jounih** [comment]
@bigint yep same one - looks like it got done already, doesn't need extra design

**Comment by bigint** [comment]
Amazing gonna close this 🚀
