### ISSUE TITLE
"Who can comment" better visualisation

### ISSUE THREAD

**Issue by jounih** [lensterxyz/lenster#809]
![Image](https://user-images.githubusercontent.com/10109867/195557329-4eb4a4c8-7fe4-4a8d-8833-593686160b15.png)

![Image](https://user-images.githubusercontent.com/10109867/195557401-66022d45-1ffc-4323-9d23-9918833387e5.png)

![Image](https://user-images.githubusercontent.com/10109867/195557456-586e8169-3477-4935-98a0-9729c38436e6.png)

**Comment by saurabhdoteth** [comment]
@bigint can you drop figma link?

**Comment by metadimensions** [comment]
please do drop the figma link.. i will work on this

**Comment by the-hedge** [comment]
I don't have a handle. Is there a way I can run in some kind of 'dev-mode' that I don't need to sign-in to develop this?

**Comment by bigint** [comment]
No plans for now, we can reiterate on redesign
