### ISSUE TITLE
Sender's messages are on the left side instead of right

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#831]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/69431456/195966388-92aef165-6446-4d66-9feb-c148a718c790.png">

**Comment by elisealix22** [comment]
@bigint are you still seeing this one? I've been unable to reproduce on `main` 👀

**Comment by bigint** [comment]
This happens because of this https://github.com/lensterxyz/lenster/issues/834
