### ISSUE TITLE
Add virtualized list support for feed, notifications and users list so we will not overload the DOM usage

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#837]

**Comment by benbaessler** [comment]
@bigint Is this not already integrated with the use of `react-infinite-scroll-component` library? For example [here](https://github.com/lensterxyz/lenster/blob/main/apps/web/src/components/Explore/Feed.tsx#L62-L74).

**Comment by bigint** [comment]
@benbaessler They don't have virtual list support 🙇🏼

**Comment by benbaessler** [comment]
@bigint wdyt about using a library like `react-window` (link [here](https://github.com/bvaughn/react-window))? I'll try to integrate it and see if it works as intended.

**Comment by bigint** [comment]
Yup i'm really happy if we are using react-window, aka one of my favorite one

**Comment by yyj2000** [comment]
~~

**Comment by bigint** [comment]
**$250 USD Bounty** https://app.dework.xyz/lenster-23720/lenster?taskId=31e9b837-5f6e-4673-8262-dba88309f0a6

**Comment by rahuldkjain** [comment]
hey @bigint, I would to like to work on this enhancement

**Comment by bigint** [comment]
Amazing @rahuldkjain 🤝 you can go ahead and submit your work here when done

https://app.dework.xyz/lenster-23720/lenster?taskId=31e9b837-5f6e-4673-8262-dba88309f0a6

**Comment by chngln** [comment]
:) i can try it

**Comment by ManyRios** [comment]
@bigint  This is already implemented with react-virtuosa?

**Comment by bigint** [comment]
@ManyRios yes we dont it in all places except feed, closing this issue now!
