### ISSUE TITLE
Improve video integration by not reloading video when it been liked

### ISSUE THREAD

**Issue by NandyBa** [lensterxyz/lenster#848]
### Summary

Improve video integration by not reloading video when it been liked

Inlustration :
https://user-images.githubusercontent.com/11545946/196156666-84a39317-7516-4a19-9fa8-e5e12902b941.mov
Lens post: https://lenster.xyz/posts/0xf1b1-0x011f

P.S: I don't realy know if need to be tag as bug or feature.

**Comment by bigint** [comment]
Fixed
