### ISSUE TITLE
React infinite render is happending.  Looks like some useEffect running in infinite look

### ISSUE THREAD

**Issue by xhzi** [lensterxyz/lenster#862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Seems like some react infinite render is happening. Check the span re-rendering. 
Looks like some useEffect running in infinite look . This happened few days ago. Reported in discord. No one responded and updating it here as instructed by one of the mods. Please refer the video for more info.

https://user-images.githubusercontent.com/109680932/196518301-4227871d-0168-4572-a999-7633d2bea7f8.mp4

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Chrome

**Comment by foolo** [comment]
@xhzi I'm trying to reproduce this, but I don't see the re-rendering of those elements. For me they stay there just fine. Can you still reproduce this? Is it needed to open the emoji menu, as you do in the video?

**Comment by bigint** [comment]
Closing this, I can't reproduce this 🙇
