### ISSUE TITLE
Clean the user key from localstorage in all logout methods

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#912]

**Comment by bigint** [comment]
@elisealix22 we need to add here as well

- https://github.com/lensterxyz/lenster/blob/main/src/components/Layout.tsx#L81
- https://github.com/lensterxyz/lenster/blob/main/src/components/Settings/Delete/index.tsx#L39
- https://github.com/lensterxyz/lenster/blob/main/src/apollo.ts#L45

**Comment by neekolas** [comment]
Will do
