### ISSUE TITLE
cannot switch to another account anymore if i have more than 4 lens profiles

### ISSUE THREAD

**Issue by mega7mega** [lensterxyz/lenster#924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

cannot switch to another account anymore if i have more than 4 lens profiles.
before you could pick it now you can only see the top 4 after that it vanishes behind the DIV,
I had to go into the CSS to expand the div to see all of them.

### Expected Behavior

ideally it would drop to the height of all the accounts available

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Brave

### Anything else?

![image](https://user-images.githubusercontent.com/114383396/197612551-075e95fe-62f3-4916-953d-4869e5d10164.png)

**Comment by bigint** [comment]
You can scroll inside it 🙏🏼
