### ISSUE TITLE
Timeline v2 - Thread with OP post 

### ISSUE THREAD

**Issue by sasicodes** [lensterxyz/lenster#956]
The middle comment in thread is missing now in timeline v2.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/29498872/212031702-3887afd0-32b7-4eae-8568-ab62f44fa701.png">

**Comment by 0xchetan** [comment]
@bigint would it be possible to elaborate on this issue?

**Comment by 0xchetan** [comment]
@sasicodes @bigint do we have an existing design for this?

**Comment by bigint** [comment]
Dupe of #810
