### ISSUE TITLE
Layout shift is happening on selecting a user

### ISSUE THREAD

**Issue by bigint** [lensterxyz/lenster#972]
https://user-images.githubusercontent.com/69431456/198342898-29cf72df-451d-4d76-92e7-ad42c0d2358a.mov

**Comment by saulmc** [comment]
Not seeing this behavior anymore. @bigint did you fix this in https://github.com/lensterxyz/lenster/pull/1014?

**Comment by bigint** [comment]
Yup seems like not happening for me too 😊 I didn't fixed it 😅

**Comment by saulmc** [comment]
🤞
